In [1]:
import pandas as pd
import numpy as np

# Import the first CSV file
fights_df = pd.read_csv('ufc_fights_data.csv')

# Import the second CSV file
fighters_df = pd.read_csv('ufc_fighters_data.csv')
pd.set_option('display.max_columns', None)
fighters_df.drop('url', axis=1, inplace=True)

In [2]:
#clean fighters_df

# Replace '--' with NaN across the whole DataFrame
fighters_df.replace('--', np.nan, inplace=True)

# Remove leading colons
cols_to_clean = ['SLpM', 'Str. Acc.', 'SApM', 'Str. Def','TD Avg.', 'TD Acc.', 'TD Def.', 'Sub. Avg.']
for col in cols_to_clean:
  fighters_df[col] = fighters_df[col].astype(str).str.lstrip(':')

#clean weight, reach, and height
fighters_df['weight'] = fighters_df['weight'].astype(str).str.replace('lbs.', '', regex=False).str.strip()
fighters_df['weight'] = pd.to_numeric(fighters_df['weight'], errors='coerce')

fighters_df['reach'] = pd.to_numeric(
    fighters_df['reach'].astype(str).str.replace('"', '', regex=False).str.strip(),
    errors='coerce'
)

def parse_height(h):
    if isinstance(h, str) and "'" in h:
        ft, inch = h.split("'")
        return int(ft.strip()) * 12 + int(inch.strip().replace('"', ''))
    return None

fighters_df['height'] = fighters_df['height'].apply(parse_height)


#change percents to decimals
percent_cols = ['Str. Acc.', 'Str. Def', 'TD Acc.', 'TD Def.']
for col in percent_cols:
    fighters_df[col] = (
        fighters_df[col]
        .astype(str)
        .str.replace('%', '', regex=False)  # Remove %
        .str.strip()                        # Trim whitespace
        .astype(float) / 100                # Convert to decimal
    )


#format dob
fighters_df['dob'] = pd.to_datetime(fighters_df['dob'], errors='coerce')


#turn record collumn to wins, losses, draws, nc
fighters_df[['wins', 'losses', 'draws', 'nc']] = fighters_df['record'].str.extract(
    r'^(\d+)-(\d+)(?:-(\d+))?(?:\s*\((\d+)\s*NC\))?$'
)
cols = ['wins', 'losses', 'draws', 'nc']
fighters_df[cols] = fighters_df[cols].apply(pd.to_numeric, errors='coerce').fillna(0).astype(int)

fighters_df.head(10)
fighters_df.to_csv('ufc_fighters_cleaned.csv', index=False)

In [3]:
#clean fights_df

#replace '--' values and turn percents to decimals
percent_cols = ['p1_SIG_STR_PCT', 'p2_SIG_STR_PCT', 'p1_TD_PCT', 'p2_TD_PCT', 'p1_R1_SIG_STR_PCT', 'p2_R1_SIG_STR_PCT', 'p1_R1_TD_PCT', 'p2_R1_TD_PCT', 'p1_SIG_STR_PCT_DETAILED', 'p2_SIG_STR_PCT_DETAILED', 'p1_R1_SIG_STR_PCT_DETAILED', 'p2_R1_SIG_STR_PCT_DETAILED']
for col in percent_cols:
    fights_df[col] = (
        fights_df[col]
        .astype(str)
        .replace({'--': np.nan, '---': np.nan})  # Handle missing values first
        .str.replace('%', '', regex=False)  # Remove percentage symbols
        .str.strip()  # Clean whitespace
        .astype(float) / 100  # Convert to decimal
    )


#format event date
fights_df['event_date'] = pd.to_datetime(fights_df['event_date'], errors='coerce')


# columns to split
cols_to_split = ['p1_SIG_STR', 'p2_SIG_STR', 'p1_TOTAL_STR', 'p2_TOTAL_STR', 'p1_TD', 'p2_TD', 'p1_R1_SIG_STR', 'p2_R1_SIG_STR', 'p1_R1_TOTAL_STR', 'p2_R1_TOTAL_STR', 'p1_R1_TD', 'p2_R1_TD', 'p1_SIG_STR_LANDED_ATTEMPTED', 'p2_SIG_STR_LANDED_ATTEMPTED', 'p1_HEAD_LANDED_ATTEMPTED', 'p2_HEAD_LANDED_ATTEMPTED', 'p1_BODY_LANDED_ATTEMPTED', 'p2_BODY_LANDED_ATTEMPTED', 'p1_LEG_LANDED_ATTEMPTED', 'p2_LEG_LANDED_ATTEMPTED', 'p1_DISTANCE_LANDED_ATTEMPTED', 'p2_DISTANCE_LANDED_ATTEMPTED', 'p1_CLINCH_LANDED_ATTEMPTED', 'p2_CLINCH_LANDED_ATTEMPTED', 'p1_GROUND_LANDED_ATTEMPTED', 'p2_GROUND_LANDED_ATTEMPTED', 'p1_R1_SIG_STR_LANDED_ATTEMPTED', 'p2_R1_SIG_STR_LANDED_ATTEMPTED', 'p1_R1_HEAD_LANDED_ATTEMPTED', 'p2_R1_HEAD_LANDED_ATTEMPTED', 'p1_R1_BODY_LANDED_ATTEMPTED', 'p2_R1_BODY_LANDED_ATTEMPTED', 'p1_R1_LEG_LANDED_ATTEMPTED', 'p2_R1_LEG_LANDED_ATTEMPTED', 'p1_R1_DISTANCE_LANDED_ATTEMPTED', 'p2_R1_DISTANCE_LANDED_ATTEMPTED', 'p1_R1_CLINCH_LANDED_ATTEMPTED', 'p2_R1_CLINCH_LANDED_ATTEMPTED', 'p1_R1_GROUND_LANDED_ATTEMPTED', 'p2_R1_GROUND_LANDED_ATTEMPTED']

#Loop over them, split into “_LANDED” and “_ATTEMPTED”, convert to ints
for col in cols_to_split:
    # decide new column names
    if col.endswith('_LANDED_ATTEMPTED'):
        base = col.rsplit('_', 2)[0]       # turns 'p1_HEAD_LANDED_ATTEMPTED' → 'p1_HEAD'
        landed_col    = f"{base}_LANDED"
        attempted_col = f"{base}_ATTEMPTED"
    else:
        # for columns like 'p1_SIG_STR'
        landed_col    = f"{col}_LANDED"
        attempted_col = f"{col}_ATTEMPTED"

    # split “63 of 129” → ['63','129'], then to numeric
    fights_df[[landed_col, attempted_col]] = (
        fights_df[col]
          .str.split(' of ', expand=True)
          .astype(int)
    )

# Drop the originals
fights_df.drop(columns=cols_to_split, inplace=True)


# time collumns needing reformatting
time_cols = ['p1_CTRL', 'p2_CTRL', 'p1_R1_CTRL', 'p2_R1_CTRL' ]

#Convert each to total seconds
for col in time_cols:
    # Replace non-time strings with NaN
    fights_df[col] = fights_df[col].replace({'--': np.nan, '---': np.nan})
    
    # Convert to "00:MM:SS" format then to seconds
    fights_df[col] = (
        pd.to_timedelta('00:' + fights_df[col].fillna('00:00'), errors='coerce')
        .dt.total_seconds()
        .astype('Int64')  # Allows integer NaNs
    )

fights_df.head(10)

,p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,method,referee,winner,event_date,p1_SIG_STR_LANDED,p1_SIG_STR_ATTEMPTED,p2_SIG_STR_LANDED,p2_SIG_STR_ATTEMPTED,p1_TOTAL_STR_LANDED,p1_TOTAL_STR_ATTEMPTED,p2_TOTAL_STR_LANDED,p2_TOTAL_STR_ATTEMPTED,p1_TD_LANDED,p1_TD_ATTEMPTED,p2_TD_LANDED,p2_TD_ATTEMPTED,p1_R1_SIG_STR_LANDED,p1_R1_SIG_STR_ATTEMPTED,p2_R1_SIG_STR_LANDED,p2_R1_SIG_STR_ATTEMPTED,p1_R1_TOTAL_STR_LANDED,p1_R1_TOTAL_STR_ATTEMPTED,p2_R1_TOTAL_STR_LANDED,p2_R1_TOTAL_STR_ATTEMPTED,p1_R1_TD_LANDED,p1_R1_TD_ATTEMPTED,p2_R1_TD_LANDED,p2_R1_TD_ATTEMPTED,p1_HEAD_LANDED,p1_HEAD_ATTEMPTED,p2_HEAD_LANDED,p2_HEAD_ATTEMPTED,p1_BODY_LANDED,p1_BODY_ATTEMPTED,p2_BODY_LANDED,p2_BODY_ATTEMPTED,p1_LEG_LANDED,p1_LEG_ATTEMPTED,p2_LEG_LANDED,p2_LEG_ATTEMPTED,p1_DISTANCE_LANDED,p1_DISTANCE_ATTEMPTED,p2_DISTANCE_LANDED,p2_DISTANCE_ATTEMPTED,p1_CLINCH_LANDED,p1_CLINCH_ATTEMPTED,p2_CLINCH_LANDED,p2_CLINCH_ATTEMPTED,p1_GROUND_LANDED,p1_GROUND_ATTEMPTED,p2_GROUND_LANDED,p2_GROUND_ATTEMPTED,p1_R1_HEAD_LANDED,p1_R1_HEAD_ATTEMPTED,p2_R1_HEAD_LANDED,p2_R1_HEAD_ATTEMPTED,p1_R1_BODY_LANDED,p1_R1_BODY_ATTEMPTED,p2_R1_BODY_LANDED,p2_R1_BODY_ATTEMPTED,p1_R1_LEG_LANDED,p1_R1_LEG_ATTEMPTED,p2_R1_LEG_LANDED,p2_R1_LEG_ATTEMPTED,p1_R1_DISTANCE_LANDED,p1_R1_DISTANCE_ATTEMPTED,p2_R1_DISTANCE_LANDED,p2_R1_DISTANCE_ATTEMPTED,p1_R1_CLINCH_LANDED,p1_R1_CLINCH_ATTEMPTED,p2_R1_CLINCH_LANDED,p2_R1_CLINCH_ATTEMPTED,p1_R1_GROUND_LANDED,p1_R1_GROUND_ATTEMPTED,p2_R1_GROUND_LANDED,p2_R1_GROUND_ATTEMPTED
0,Roman Dolidze,Anthony Hernandez,0,0,0.33,0.59,0.00,0.81,0,1,0,0,45,468,0,0,0.32,0.51,NaN,0.50,0,0,0,0,45,50,0.33,0.59,0.32,0.51,Submission,Herb Dean,0,2025-08-09,36,107,91,152,39,110,120,187,0,1,9,11,10,31,19,37,13,34,21,39,0,0,2,4,25,88,67,128,4,11,6,6,7,8,18,18,34,101,48,102,2,6,13,18,0,0,30,32,5,25,11,29,0,1,1,1,5,5,7,7,9,30,16,34,1,1,3,3,0,0,0,0
1,Steve Erceg,Ode Osbourne,0,0,0.37,0.47,0.30,0.50,1,0,0,1,287,69,0,0,0.27,0.53,0.20,1.00,0,0,0,1,66,46,0.37,0.47,0.27,0.53,Decision - Unanimous,Mark Smith,1,2025-08-09,20,53,35,74,39,82,47,89,3,10,1,2,3,11,17,32,4,14,26,44,1,5,1,1,10,42,20,53,10,11,4,7,0,0,11,14,12,43,29,68,6,8,1,1,2,2,5,5,2,10,10,21,1,1,0,2,0,0,7,9,2,10,12,27,1,1,0,0,0,0,5,5
2,Iasmin Lucindo,Angela Hill,0,0,0.47,0.58,0.42,0.00,0,1,0,0,337,79,0,0,0.39,0.54,0.33,0.00,0,0,0,0,46,33,0.47,0.58,0.39,0.54,Decision - Unanimous,Chris Tognoni,1,2025-08-09,72,151,64,110,100,187,80,129,3,7,0,5,27,68,25,46,28,69,26,47,1,3,0,3,56,128,42,84,12,19,19,23,4,4,3,3,57,130,52,92,11,17,12,18,4,4,0,0,19,57,18,38,6,9,5,6,2,2,2,2,22,58,22,41,5,10,3,5,0,0,0,0
3,Andre Fili,Christian Rodriguez,0,0,0.35,0.47,0.60,0.14,0,0,0,0,102,95,0,0,0.34,0.45,NaN,0.33,0,0,0,0,0,35,0.35,0.47,0.34,0.45,Decision - Split,Mike Beltran,1,2025-08-09,64,182,83,174,74,193,95,190,3,5,1,7,22,63,29,64,27,68,29,66,0,0,1,3,52,164,49,130,6,10,8,13,6,8,26,31,62,179,69,157,2,3,13,16,0,0,1,1,19,56,13,43,1,4,4,6,2,3,12,15,22,63,28,63,0,0,0,0,0,0,1,1
4,Miles Johns,Jean Matsumoto,0,0,0.45,0.40,0.62,0.00,0,2,0,1,192,56,0,0,0.52,0.32,0.50,0.00,0,1,0,0,102,22,0.45,0.40,0.52,0.32,Decision - Split,Herb Dean,0,2025-08-09,83,184,95,233,89,191,109,249,5,8,0,3,22,42,16,49,23,43,20,54,1,2,0,2,70,170,49,160,12,13,27,38,1,1,19,35,78,175,87,224,5,8,8,9,0,1,0,0,17,37,8,29,5,5,5,9,0,0,3,11,20,37,15,48,2,4,1,1,0,1,0,0
5,Eryk Anders,Christian Leroy Duncan,0,1,0.58,0.55,0.33,NaN,0,0,0,0,78,39,0,1,0.58,0.55,0.33,NaN,0,0,0,0,78,39,0.58,0.55,0.58,0.55,KO/TKO,Mark Smith,0,2025-08-09,7,12,24,43,18,24,27,46,1,3,0,0,7,12,24,43,18,24,27,46,1,3,0,0,2,7,9,26,4,4,3,4,1,1,12,13,4,9,20,37,3,3,3,3,0,0,1,3,2,7,9,26,4,4,3,4,1,1,12,13,4,9,20,37,3,3,3,3,0,0,1,3
6,Julius Walker,Rafael Cerqueira,1,0,0.70,0.45,0.60,NaN,0,0,0,0,706,27,0,0,0.59,0.44,0.75,NaN,0,0,0,0,211,18,0.70,0.45,0.59,0.44,Decision - Unanimous,Mike Beltran,1,2025-08-09,44,62,19,42,96,120,30,54,6,10,0,0,13,22,11,25,17,27,12,26,3,4,0,0,26,43,15,37,9,10,0,1,9,9,4,4,18,26,19,42,4,9,0,0,22,27,0,0,5,14,7,21,3,3,0,0,5,5,4,4,8,13,11,25,2,5,0,0,3,4,0,0
7,Elijah Smith,Toshiomi Kazama,0,0,0.80,NaN,NaN,1.00,0,1,1,1,229,5,0,0,0.80,NaN,NaN,1.00,0,1,1,1,229,5,0.80,NaN,0.80,NaN,KO/TKO,Chris Tognoni,1,2025-08-09,37,46,0,0,61,74,2,2,0,0,1,1,37,46,0,0,61,74,2,2,0,0,1,1,35,44,0,0,2,2,0,0,0,0,0,0,1,3,0,0,0,0,0,0,36,43,0,0,35,44,0,0,2,2,0,0,0,0,0,0,1,3,0,0,0,0,0,0,36,43,0,0
8,Joselyne Edwards,Priscila Cachoeira,1,0,0.59,0.36,0.00,NaN,0,0,0,0,1,0,1,0,0.59,0.36,0.00,NaN,0,0,0,0,1,0,0.59,0.36,0.59,0.36,KO/TKO,Herb Dean,1,2025-08-09,26,44,18,50,26,44,18,50,0,2,0,0,26,44,18,50,26,44,18,50,0,2,0,0,16,29,15,47,5,10,1,1,5,5,2,2,24,42,18,50,0,0,0,0,2,2,0,0,16,29,15,47,5,10,1,1,5,5,2,2,24,42,18,50,0,0,0,0,2,2,0,0
9,Uros Medic,Gilbert Urbina,1,1,0.55,0.50,NaN,NaN,0,0,0,0,1,2,1,1,0.55,0.50,NaN,NaN,0,0,0,0,1,2,0.55,0.50,0.55,0.50,KO/TKO,Mark Smith,1,2025-08-09,5,9,5,10,6,10,5,10,0,0,0,0,5,9,5,10,6,10,5,10,0,0,0,0,4,8,3,7,1,1,1,2,0,0,1,1,3,7,5,10,1,1,0,0,1,1,0,0,4,8,3,7,1,1,1,2,0,0,1,1,3,7,5,10,1,1,0,0,1,1,0,0

In [4]:
# merge the two datasets

# First, merge p1 fighter stats
fights_df = fights_df.merge(
    fighters_df,
    left_on='p1_fighter',
    right_on='name',  # This matches p1_fighter with the name column in fighters_df
    how='left'
)
fights_df.drop(columns=['name'], inplace=True)

# Only include the specific columns you want to rename with p1_ prefix
p1_cols = ['height', 'weight', 'reach', 'stance', 'dob', 'SLpM', 'Str. Acc.', 'SApM', 'Str. Def', 'TD Avg.', 'TD Acc.', 'TD Def.', 'Sub. Avg.']
fights_df.rename(columns={col: f'p1_{col}' for col in p1_cols}, inplace=True)

# Then merge p2 fighter stats
fights_df = fights_df.merge(
    fighters_df,
    left_on='p2_fighter',
    right_on='name',  # This matches p2_fighter with the name column in fighters_df
    how='left'
)
fights_df.drop(columns=['name'], inplace=True)

# Use the same columns for p2 as we did for p1
p2_cols = ['height', 'weight', 'reach', 'stance', 'dob', 'SLpM', 'Str. Acc.', 'SApM', 'Str. Def', 'TD Avg.', 'TD Acc.', 'TD Def.', 'Sub. Avg.']
fights_df.rename(columns={col: f'p2_{col}' for col in p2_cols}, inplace=True)


# Drop unwanted columns
columns_to_drop = ['record_x', 'wins_x', 'losses_x', 'draws_x', 'nc_x', 'record_y', 'wins_y', 'losses_y', 'draws_y', 'nc_y']

# Check if columns exist before trying to drop them
existing_columns = [col for col in columns_to_drop if col in fights_df.columns]
if existing_columns:
    fights_df.drop(columns=existing_columns, inplace=True)

fights_df.head(10)

,p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,method,referee,winner,event_date,p1_SIG_STR_LANDED,p1_SIG_STR_ATTEMPTED,p2_SIG_STR_LANDED,p2_SIG_STR_ATTEMPTED,p1_TOTAL_STR_LANDED,p1_TOTAL_STR_ATTEMPTED,p2_TOTAL_STR_LANDED,p2_TOTAL_STR_ATTEMPTED,p1_TD_LANDED,p1_TD_ATTEMPTED,p2_TD_LANDED,p2_TD_ATTEMPTED,p1_R1_SIG_STR_LANDED,p1_R1_SIG_STR_ATTEMPTED,p2_R1_SIG_STR_LANDED,p2_R1_SIG_STR_ATTEMPTED,p1_R1_TOTAL_STR_LANDED,p1_R1_TOTAL_STR_ATTEMPTED,p2_R1_TOTAL_STR_LANDED,p2_R1_TOTAL_STR_ATTEMPTED,p1_R1_TD_LANDED,p1_R1_TD_ATTEMPTED,p2_R1_TD_LANDED,p2_R1_TD_ATTEMPTED,p1_HEAD_LANDED,p1_HEAD_ATTEMPTED,p2_HEAD_LANDED,p2_HEAD_ATTEMPTED,p1_BODY_LANDED,p1_BODY_ATTEMPTED,p2_BODY_LANDED,p2_BODY_ATTEMPTED,p1_LEG_LANDED,p1_LEG_ATTEMPTED,p2_LEG_LANDED,p2_LEG_ATTEMPTED,p1_DISTANCE_LANDED,p1_DISTANCE_ATTEMPTED,p2_DISTANCE_LANDED,p2_DISTANCE_ATTEMPTED,p1_CLINCH_LANDED,p1_CLINCH_ATTEMPTED,p2_CLINCH_LANDED,p2_CLINCH_ATTEMPTED,p1_GROUND_LANDED,p1_GROUND_ATTEMPTED,p2_GROUND_LANDED,p2_GROUND_ATTEMPTED,p1_R1_HEAD_LANDED,p1_R1_HEAD_ATTEMPTED,p2_R1_HEAD_LANDED,p2_R1_HEAD_ATTEMPTED,p1_R1_BODY_LANDED,p1_R1_BODY_ATTEMPTED,p2_R1_BODY_LANDED,p2_R1_BODY_ATTEMPTED,p1_R1_LEG_LANDED,p1_R1_LEG_ATTEMPTED,p2_R1_LEG_LANDED,p2_R1_LEG_ATTEMPTED,p1_R1_DISTANCE_LANDED,p1_R1_DISTANCE_ATTEMPTED,p2_R1_DISTANCE_LANDED,p2_R1_DISTANCE_ATTEMPTED,p1_R1_CLINCH_LANDED,p1_R1_CLINCH_ATTEMPTED,p2_R1_CLINCH_LANDED,p2_R1_CLINCH_ATTEMPTED,p1_R1_GROUND_LANDED,p1_R1_GROUND_ATTEMPTED,p2_R1_GROUND_LANDED,p2_R1_GROUND_ATTEMPTED,p1_height,p1_weight,p1_reach,p1_stance,p1_dob,p1_SLpM,p1_Str. Acc.,p1_SApM,p1_Str. Def,p1_TD Avg.,p1_TD Acc.,p1_TD Def.,p1_Sub. Avg.,p2_height,p2_weight,p2_reach,p2_stance,p2_dob,p2_SLpM,p2_Str. Acc.,p2_SApM,p2_Str. Def,p2_TD Avg.,p2_TD Acc.,p2_TD Def.,p2_Sub. Avg.
0,Roman Dolidze,Anthony Hernandez,0,0,0.33,0.59,0.00,0.81,0,1,0,0,45,468,0,0,0.32,0.51,NaN,0.50,0,0,0,0,45,50,0.33,0.59,0.32,0.51,Submission,Herb Dean,0,2025-08-09,36,107,91,152,39,110,120,187,0,1,9,11,10,31,19,37,13,34,21,39,0,0,2,4,25,88,67,128,4,11,6,6,7,8,18,18,34,101,48,102,2,6,13,18,0,0,30,32,5,25,11,29,0,1,1,1,5,5,7,7,9,30,16,34,1,1,3,3,0,0,0,0,74.0,185.0,76.0,Orthodox,1988-07-15,3.41,0.41,3.72,0.48,0.99,0.39,0.26,0.8,72.0,185.0,75.0,Orthodox,1993-10-18,4.59,0.62,2.53,0.49,6.46,0.48,0.68,1.8
1,Steve Erceg,Ode Osbourne,0,0,0.37,0.47,0.30,0.50,1,0,0,1,287,69,0,0,0.27,0.53,0.20,1.00,0,0,0,1,66,46,0.37,0.47,0.27,0.53,Decision - Unanimous,Mark Smith,1,2025-08-09,20,53,35,74,39,82,47,89,3,10,1,2,3,11,17,32,4,14,26,44,1,5,1,1,10,42,20,53,10,11,4,7,0,0,11,14,12,43,29,68,6,8,1,1,2,2,5,5,2,10,10,21,1,1,0,2,0,0,7,9,2,10,12,27,1,1,0,0,0,0,5,5,68.0,125.0,68.0,Orthodox,1995-07-27,4.00,0.45,3.79,0.52,1.15,0.27,0.62,0.4,67.0,125.0,73.0,Southpaw,1992-01-09,3.07,0.41,3.43,0.47,1.09,0.30,0.66,0.5
2,Iasmin Lucindo,Angela Hill,0,0,0.47,0.58,0.42,0.00,0,1,0,0,337,79,0,0,0.39,0.54,0.33,0.00,0,0,0,0,46,33,0.47,0.58,0.39,0.54,Decision - Unanimous,Chris Tognoni,1,2025-08-09,72,151,64,110,100,187,80,129,3,7,0,5,27,68,25,46,28,69,26,47,1,3,0,3,56,128,42,84,12,19,19,23,4,4,3,3,57,130,52,92,11,17,12,18,4,4,0,0,19,57,18,38,6,9,5,6,2,2,2,2,22,58,22,41,5,10,3,5,0,0,0,0,63.0,115.0,66.0,Orthodox,2002-01-08,3.22,0.45,2.80,0.62,2.28,0.55,0.68,0.1,63.0,115.0,64.0,Orthodox,1985-01-12,5.43,0.50,4.92,0.60,0.78,0.30,0.74,0.1
3,Andre Fili,Christian Rodriguez,0,0,0.35,0.47,0.60,0.14,0,0,0,0,102,95,0,0,0.34,0.45,NaN,0.33,0,0,0,0,0,35,0.35,0.47,0.34,0.45,Decision - Split,Mike Beltran,1,2025-08-09,64,182,83,174,74,193,95,190,3,5,1,7,22,63,29,64,27,68,29,66,0,0,1,3,52,164,49,130,6,10,8,13,6,8,26,31,62,179,69,157,2,3,13,16,0,0,1,1,19,56,13,43,1,4,4,6,2,3,12,15,22,63,28,63,0,0,0,0,0,0,1,1,71.0,145.0,74.0,Orthodox,1990-06-25,3.87,0.37,4.23,0.51,2.22,0.45,0.71,0.2,67.0,145.0,71.0,Orthodox,1997-12-17,3.85,0.50,2.85,0.56,1.75,0.40,0.67,1.1
4,Miles Johns,Jean Matsumoto,0,0,0.45,0.40,0.62,0.00,0,2,0,1,192,56,0,0,0.52,0.32,0.50,0.00,0,1,0,0,102,22,0.45,0.40,0.52,0.32,Decision - Split,Herb Dean,0,2025-08-09,83,184,95,233,89,191,109,249,5,8,0,3,22,42,16,49,23,43,20,54,1,2,0,2,70,170,49,160,12,13,27,38,1,1,19,35,78,175,87,224,5,8,8,9,0,1,0,0,17,37,8,29,5,5,5,9,0,0,3,11,20,37,15,48,2,4,1,1,0,1,0,0,67.0,135.0,68.0,Orthodox,1994-03-30,3.38,0.44,2.99,0.66,1.29,0.26,0.83,0.0,66.0,135.0,68.0,Orthodox,1999-09-09,5.43,0.41,5.43,0.48,2.14,0.41,0.53,0.6
5,Eryk Anders,Christian Leroy Duncan,0,1,0.58,0.55,0.33,NaN,0,0,0,0,78,39,0,1,0.58,0.55,0.33,NaN,0,0,0,0,78,39,0.58,0.55,0.58,0.55,KO/TKO,Mark Smith,0,2025-08-09,7,12,24,43,18,24,27,46,1,3,0,0,7,12,24,43,18,24,27,46,1,3,0,0,2,7,9,26,4,4,3,4,1,1,12,13,4,9,20,37,3,3,3,3,0,0,1,3,2,7,9,26,4,4,3,4,1,1,12,13,4,9,20,37,3,3,3,3,0,0,1,3,73.0,185.0,75.0,Southpaw,1987-04-21,3.51,0.48,4.09,0.50,1.75,0.24,0.80,0.1,74.0,185.0,79.0,Switch,1995-07-24,4.83,0.59,2.94,0.51,0.22,0.11,0.71,0.0
6,Julius Walker,Rafael Cerqueira,1,0,0.70,0.45,0.60,NaN,0,0,0,0,706,27,0,0,0.59,0.44,0.75,NaN,0,0,0,0,211,18,0.70,0.45,0.59,0.44,Decision - Unanimous,Mike Beltran,1,2025-08-09,44,62,19,42,96,120,30,54,6,10,0,0,13,22,11,25,17,27,12,26,3,4,0,0,26,43,15,37,9,10,0,1,9,9,4,4,18,26,19,42,4,9,0,0,22,27,0,0,5,14,7,21,3,3,0,0,5,5,4,4,8,13,11,25,2,5,0,0,3,4,0,0,76.0,205.0,78.0,Orthodox,1999-07-16,4.33,0.55,3.53,0.43,3.50,0.36,1.00,0.0,75.0,205.0,76.0,Southpaw,1990-03-15,1.61,0.44,4.88,0.36,0.00,0.00,0.40,0.0
7,Elijah Smith,Toshiomi Kazama,0,0,0.80,NaN,NaN,1.00,0,1,1,1,229,5,0,0,0.80,NaN,NaN,1.00,0,1,1,1,229,5,0.80,NaN,0.80,NaN,KO/TKO,Chris Tognoni,1,2025-08-09,37,46,0,0,61,74,2,2,0,0,1,1,37,46,0,0,61,74,2,2,0,0,1,1,35,44,0,0,2,2,0,0,0,0,0,0,1,3,0,0,0,0,0,0,36,43,0,0,35,44,0,0,2,2,0,0,0,0,0,0,1,3,0,0,0,0,0,0,36,43,0,0,69.0,135.0,71.0,Orthodox,2002-09-05,4.45,0.47,3.40,0.47,3.51,0.53,0.57,0.9,67.0,135.0,69.0,Orthodox,1997-05-15,1.49,0.53,4.56,0.38,1.94,0.16,0.66,1.0
8,Joselyne Edwards,Priscila Cachoeira,1,0,0.59,0.36,0.00,NaN,0,0,0,0,1,0,1,0,0.59,0.36,0.00,NaN,0,0,0,0,1,0,0.59,0.36,0.59,0.36,KO/TKO,Herb Dean,1,2025-08-09,26,44,18,50,26,44,18,50,0,2,0,0,26,44,18,50,26,44,18,50,0,2,0,0,16,29,15,47,5,10,1,1,5,5,2,2,24,42,18,50,0,0,0,0,2,2,0,0,16,29,15,47,5,10,1,1,5,5,2,2,24,42,18,50,0,0,0,0,2,2,0,0,68.0,135.0,70.0,Orthodox,1995-09-29,4.73,0.53,3.28,0.50,1.29,0.38,0.61,0.5,67.0,135.0,65.0,Orthodox,1988-08-19,4.11,0.44,7.23,0.43,0.15,0.33,0.67,0.0
9,Uros Medic,Gilbert Urbina,1,1,0.55,0.50,NaN,NaN,0,0,0,0,1,2,1,1,0.55,0.50,NaN,NaN,0,0,0,0,1,2,0.55,0.50,0.55,0.50,KO/TKO,Mark Smith,1,2025-08-09,5,9,5,10,6,10,5,10,0,0,0,0,5,9,5,10,6,10,5,10,0,0,0,0,4,8,3,7,1,1,1,2,0,0,1,1,3,7,5,10,1,1,0,0,1,1,0,0,4,8,3,7,1,1,1,2,0,0,1,1,3,7,5,10,1,1,0,0,1,1,0,0,73.0,170.0,71.0,Southpaw,1993-04-25,5.47,0.60,3.50,0.56,0.36,0.50,0.55,0.0,75.0,170.0,75.0,Orthodox,1996-04-05,5.57,0.56,4.62,0.44,2.86,0.44,0.00,0.7

In [5]:
fights_df.to_csv('ufc_cleaned.csv', index=False)