In [17]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
fighters_df = pd.read_csv('ufc_fighters_cleaned.csv')

url = "http://ufcstats.com/statistics/events/completed?page=all"
headers = {'User-Agent': 'Mozilla/5.0'}

response = requests.get(url, headers=headers)
response.raise_for_status()
soup = BeautifulSoup(response.content, 'html.parser')

first_tag = soup.select_one('a.b-link.b-link_style_black[href*="event-details"]')
first_event_link = first_tag['href'] if first_tag else None

print(first_event_link)

http://ufcstats.com/event-details/421ccfc6ddb17958

In [18]:
fight_links = []

if first_event_link:
    # fetch the single event page
    resp = requests.get(first_event_link, headers=headers)
    resp.raise_for_status()
    ev_soup = BeautifulSoup(resp.content, 'html.parser')

    # extract the event date
    date_el = ev_soup.find('li', class_='b-list__box-list-item')
    event_date = date_el.text.split(':')[-1].strip() if date_el else 'N/A'

    # find every fight row and pull out the onclick URL
    for row in ev_soup.select('tr.b-fight-details__table-row'):
        onclick = row.get('onclick','')
        if 'doNav' in onclick:
            fight_url = onclick.split("'")[1]
            fight_links.append({
                'url': fight_url,
                'event_date': event_date
            })

print(fight_links)

[{'url': 'http://ufcstats.com/fight-details/12cedec11b37ddc0', 'event_date': 'August 16, 2025'}, {'url': 'http://ufcstats.com/fight-details/9fa6a029f7f8241c', 'event_date': 'August 16, 2025'}, {'url': 'http://ufcstats.com/fight-details/42585ce706c086de', 'event_date': 'August 16, 2025'}, {'url': 'http://ufcstats.com/fight-details/9939d7073462e07e', 'event_date': 'August 16, 2025'}, {'url': 'http://ufcstats.com/fight-details/82338ba457fbe87f', 'event_date': 'August 16, 2025'}, {'url': 'http://ufcstats.com/fight-details/5efd13a12be06706', 'event_date': 'August 16, 2025'}, {'url': 'http://ufcstats.com/fight-details/5b880d10b0ed7acc', 'event_date': 'August 16, 2025'}, {'url': 'http://ufcstats.com/fight-details/a2eafd9e1d5031b1', 'event_date': 'August 16, 2025'}, {'url': 'http://ufcstats.com/fight-details/1d8dc0fb5d47357f', 'event_date': 'August 16, 2025'}, {'url': 'http://ufcstats.com/fight-details/bc63f1b2e52f603e', 'event_date': 'August 16, 2025'}, {'url': 'http://ufcstats.com/fight-details/88020d22cf905792', 'event_date': 'August 16, 2025'}, {'url': 'http://ufcstats.com/fight-details/68c423c7119004f3', 'event_date': 'August 16, 2025'}]

In [19]:
def scrape_ufc_fight_details(url): # scrapes the stats from the url we input
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Extract method of victory
    method_tag = soup.find('i', class_='b-fight-details__text-item_first')
    method = method_tag.find('i', style="font-style: normal").text.strip() if method_tag else ''
    
    # Extract referee
    referee = ""
    referee_span = soup.select_one('i.b-fight-details__label:-soup-contains("Referee:") + span')
    if referee_span:
        referee = referee_span.text.strip()

    # Find fighter status (W/L) for the first fighter
    fighter_status_tag = soup.find('i', class_='b-fight-details__person-status')
    first_fighter_won = None
    if fighter_status_tag:
        status = fighter_status_tag.text.strip()
        first_fighter_won = 1 if status == "W" else 0
    

    # get the data from round 1 and the totals rows
    all_rows = []
    rows = soup.find_all('tr', class_='b-fight-details__table-row')

    for row in rows:
        columns = row.find_all('p', class_='b-fight-details__table-text')
        data = [col.get_text(strip=True) for col in columns]
        all_rows.append(data)
    
    totals = 1
    r1_totals = 3
    sigTotals = int(len(all_rows) / 2 + 1)
    r1_sigTotals = sigTotals + 2
    
    filtered_rows = []
    
    def is_valid_row(arr):
        needed_indexes = [totals, r1_totals, sigTotals, r1_sigTotals]
        for idx in needed_indexes:
            if idx < len(all_rows):  # Make sure index is valid
                arr.append(all_rows[idx])
    
    is_valid_row(filtered_rows)
    
    # Append method of victory and referee as a new array at the end
    filtered_rows.append([method, referee])
    filtered_rows.append(first_fighter_won)

    return filtered_rows

# Test with the example URL
url = 'http://ufcstats.com/fight-details/d05cb4c4135ce402'
data = scrape_ufc_fight_details(url)
print(data)

[['Michael Chandler', 'Paddy Pimblett', '0', '0', '11 of 28', '80 of 143', '39%', '55%', '20 of 39', '121 of 197', '4 of 7', '1 of 2', '57%', '50%', '0', '0', '0', '1', '2:44', '4:41'], ['Michael Chandler', 'Paddy Pimblett', '0', '0', '5 of 11', '16 of 40', '45%', '40%', '7 of 14', '25 of 50', '2 of 3', '0 of 0', '66%', '---', '0', '0', '0', '0', '2:10', '0:00'], ['Michael Chandler', 'Paddy Pimblett', '11 of 28', '80 of 143', '39%', '55%', '6 of 18', '61 of 119', '3 of 7', '4 of 5', '2 of 3', '15 of 19', '10 of 24', '43 of 96', '0 of 0', '4 of 5', '1 of 4', '33 of 42'], ['Michael Chandler', 'Paddy Pimblett', '5 of 11', '16 of 40', '45%', '40%', '4 of 10', '7 of 28', '1 of 1', '1 of 2', '0 of 0', '8 of 10', '4 of 7', '16 of 40', '0 of 0', '0 of 0', '1 of 4', '0 of 0'], ['KO/TKO', 'Kerry Hatley'], 0]

In [20]:
def format_fight_data_single_row(data): #formats the data extracted from a match into a dictionary
    if not data or len(data) < 4:
        return "Not enough data to format."
    
    # Extract fighter names for reference
    fighter1 = data[0][0]
    fighter2 = data[0][1]
    
    # Create a single row dictionary with p1_ and p2_ prefixes
    formatted_row = {
        "p1_fighter": fighter1,
        "p2_fighter": fighter2,
        
        # Totals (Row 1)
        "p1_KD": data[0][2],
        "p2_KD": data[0][3],
        "p1_SIG_STR": data[0][4],
        "p2_SIG_STR": data[0][5],
        "p1_SIG_STR_PCT": data[0][6],
        "p2_SIG_STR_PCT": data[0][7],
        "p1_TOTAL_STR": data[0][8],
        "p2_TOTAL_STR": data[0][9],
        "p1_TD": data[0][10],
        "p2_TD": data[0][11],
        "p1_TD_PCT": data[0][12],
        "p2_TD_PCT": data[0][13],
        "p1_SUB_ATT": data[0][14],
        "p2_SUB_ATT": data[0][15],
        "p1_REV": data[0][16],
        "p2_REV": data[0][17],
        "p1_CTRL": data[0][18],
        "p2_CTRL": data[0][19],
        
        # Round 1 Totals (Row 2)
        "p1_R1_KD": data[1][2],
        "p2_R1_KD": data[1][3],
        "p1_R1_SIG_STR": data[1][4],
        "p2_R1_SIG_STR": data[1][5],
        "p1_R1_SIG_STR_PCT": data[1][6],
        "p2_R1_SIG_STR_PCT": data[1][7],
        "p1_R1_TOTAL_STR": data[1][8],
        "p2_R1_TOTAL_STR": data[1][9],
        "p1_R1_TD": data[1][10],
        "p2_R1_TD": data[1][11],
        "p1_R1_TD_PCT": data[1][12],
        "p2_R1_TD_PCT": data[1][13],
        "p1_R1_SUB_ATT": data[1][14],
        "p2_R1_SUB_ATT": data[1][15],
        "p1_R1_REV": data[1][16],
        "p2_R1_REV": data[1][17],
        "p1_R1_CTRL": data[1][18],
        "p2_R1_CTRL": data[1][19],
        
        # Significant Strike Details (Row 3)
        "p1_SIG_STR_LANDED_ATTEMPTED": data[2][2],
        "p2_SIG_STR_LANDED_ATTEMPTED": data[2][3],
        "p1_SIG_STR_PCT_DETAILED": data[2][4],
        "p2_SIG_STR_PCT_DETAILED": data[2][5],
        "p1_HEAD_LANDED_ATTEMPTED": data[2][6],
        "p2_HEAD_LANDED_ATTEMPTED": data[2][7],
        "p1_BODY_LANDED_ATTEMPTED": data[2][8],
        "p2_BODY_LANDED_ATTEMPTED": data[2][9],
        "p1_LEG_LANDED_ATTEMPTED": data[2][10],
        "p2_LEG_LANDED_ATTEMPTED": data[2][11],
        "p1_DISTANCE_LANDED_ATTEMPTED": data[2][12],
        "p2_DISTANCE_LANDED_ATTEMPTED": data[2][13],
        "p1_CLINCH_LANDED_ATTEMPTED": data[2][14],
        "p2_CLINCH_LANDED_ATTEMPTED": data[2][15],
        "p1_GROUND_LANDED_ATTEMPTED": data[2][16],
        "p2_GROUND_LANDED_ATTEMPTED": data[2][17],
        
        # Round 1 Significant Strike Details (Row 4)
        "p1_R1_SIG_STR_LANDED_ATTEMPTED": data[3][2],
        "p2_R1_SIG_STR_LANDED_ATTEMPTED": data[3][3],
        "p1_R1_SIG_STR_PCT_DETAILED": data[3][4],
        "p2_R1_SIG_STR_PCT_DETAILED": data[3][5],
        "p1_R1_HEAD_LANDED_ATTEMPTED": data[3][6],
        "p2_R1_HEAD_LANDED_ATTEMPTED": data[3][7],
        "p1_R1_BODY_LANDED_ATTEMPTED": data[3][8],
        "p2_R1_BODY_LANDED_ATTEMPTED": data[3][9],
        "p1_R1_LEG_LANDED_ATTEMPTED": data[3][10],
        "p2_R1_LEG_LANDED_ATTEMPTED": data[3][11],
        "p1_R1_DISTANCE_LANDED_ATTEMPTED": data[3][12],
        "p2_R1_DISTANCE_LANDED_ATTEMPTED": data[3][13],
        "p1_R1_CLINCH_LANDED_ATTEMPTED": data[3][14],
        "p2_R1_CLINCH_LANDED_ATTEMPTED": data[3][15],
        "p1_R1_GROUND_LANDED_ATTEMPTED": data[3][16],
        "p2_R1_GROUND_LANDED_ATTEMPTED": data[3][17],

        "method": data[4][0],
        "referee": data[4][1],
        "winner": data[5]
    }
    
    # Print column headers once (useful for CSV export)
    print(",".join(formatted_row.keys()))
    
    # Print the values as a single row
    print(",".join(str(val) for val in formatted_row.values()))
    
    return formatted_row

# Call the function with your scraped data
formatted_row = format_fight_data_single_row(data)
print(formatted_row)

p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Michael Chandler,Paddy Pimblett,0,0,11 of 28,80 of 143,39%,55%,20 of 39,121 of 197,4 of 7,1 of 2,57%,50%,0,0,0,1,2:44,4:41,0,0,5 of 11,16 of 40,45%,40%,7 of 14,25 of 50,2 of 3,0 of 0,66%,---,0,0,0,0,2:10,0:00,11 of 28,80 of 143,39%,55%,6 of 18,61 of 119,3 of 7,4 of 5,2 of 3,15 of 19,10 of 24,43 of 96,0 of 0,4 of 5,1 of 4,33 of 42,5 of 11,16 of 40,45%,40%,4 of 10,7 of 28,1 of 1,1 of 2,0 of 0,8 of 10,4 of 7,16 of 40,0 of 0,0 of 0,1 of 4,0 of 0,KO/TKO,Kerry Hatley,0
{'p1_fighter': 'Michael Chandler', 'p2_fighter': 'Paddy Pimblett', 'p1_KD': '0', 'p2_KD': '0', 'p1_SIG_STR': '11 of 28', 'p2_SIG_STR': '80 of 143', 'p1_SIG_STR_PCT': '39%', 'p2_SIG_STR_PCT': '55%', 'p1_TOTAL_STR': '20 of 39', 'p2_TOTAL_STR': '121 of 197', 'p1_TD': '4 of 7', 'p2_TD': '1 of 2', 'p1_TD_PCT': '57%', 'p2_TD_PCT': '50%', 'p1_SUB_ATT': '0', 'p2_SUB_ATT': '0', 'p1_REV': '0', 'p2_REV': '1', 'p1_CTRL': '2:44', 'p2_CTRL': '4:41', 'p1_R1_KD': '0', 'p2_R1_KD': '0', 'p1_R1_SIG_STR': '5 of 11', 'p2_R1_SIG_STR': '16 of 40', 'p1_R1_SIG_STR_PCT': '45%', 'p2_R1_SIG_STR_PCT': '40%', 'p1_R1_TOTAL_STR': '7 of 14', 'p2_R1_TOTAL_STR': '25 of 50', 'p1_R1_TD': '2 of 3', 'p2_R1_TD': '0 of 0', 'p1_R1_TD_PCT': '66%', 'p2_R1_TD_PCT': '---', 'p1_R1_SUB_ATT': '0', 'p2_R1_SUB_ATT': '0', 'p1_R1_REV': '0', 'p2_R1_REV': '0', 'p1_R1_CTRL': '2:10', 'p2_R1_CTRL': '0:00', 'p1_SIG_STR_LANDED_ATTEMPTED': '11 of 28', 'p2_SIG_STR_LANDED_ATTEMPTED': '80 of 143', 'p1_SIG_STR_PCT_DETAILED': '39%', 'p2_SIG_STR_PCT_DETAILED': '55%', 'p1_HEAD_LANDED_ATTEMPTED': '6 of 18', 'p2_HEAD_LANDED_ATTEMPTED': '61 of 119', 'p1_BODY_LANDED_ATTEMPTED': '3 of 7', 'p2_BODY_LANDED_ATTEMPTED': '4 of 5', 'p1_LEG_LANDED_ATTEMPTED': '2 of 3', 'p2_LEG_LANDED_ATTEMPTED': '15 of 19', 'p1_DISTANCE_LANDED_ATTEMPTED': '10 of 24', 'p2_DISTANCE_LANDED_ATTEMPTED': '43 of 96', 'p1_CLINCH_LANDED_ATTEMPTED': '0 of 0', 'p2_CLINCH_LANDED_ATTEMPTED': '4 of 5', 'p1_GROUND_LANDED_ATTEMPTED': '1 of 4', 'p2_GROUND_LANDED_ATTEMPTED': '33 of 42', 'p1_R1_SIG_STR_LANDED_ATTEMPTED': '5 of 11', 'p2_R1_SIG_STR_LANDED_ATTEMPTED': '16 of 40', 'p1_R1_SIG_STR_PCT_DETAILED': '45%', 'p2_R1_SIG_STR_PCT_DETAILED': '40%', 'p1_R1_HEAD_LANDED_ATTEMPTED': '4 of 10', 'p2_R1_HEAD_LANDED_ATTEMPTED': '7 of 28', 'p1_R1_BODY_LANDED_ATTEMPTED': '1 of 1', 'p2_R1_BODY_LANDED_ATTEMPTED': '1 of 2', 'p1_R1_LEG_LANDED_ATTEMPTED': '0 of 0', 'p2_R1_LEG_LANDED_ATTEMPTED': '8 of 10', 'p1_R1_DISTANCE_LANDED_ATTEMPTED': '4 of 7', 'p2_R1_DISTANCE_LANDED_ATTEMPTED': '16 of 40', 'p1_R1_CLINCH_LANDED_ATTEMPTED': '0 of 0', 'p2_R1_CLINCH_LANDED_ATTEMPTED': '0 of 0', 'p1_R1_GROUND_LANDED_ATTEMPTED': '1 of 4', 'p2_R1_GROUND_LANDED_ATTEMPTED': '0 of 0', 'method': 'KO/TKO', 'referee': 'Kerry Hatley', 'winner': 0}

In [21]:
def process_multiple_fights_with_date(url_date_list): # gets the data from every match and creates a dataframe from it 
    all_fights_data = []
    
    for item in url_date_list:
        url = item['url']
        event_date = item['event_date']
        try:
            fight_data = scrape_ufc_fight_details(url)
            formatted_row = format_fight_data_single_row(fight_data)  
            if isinstance(formatted_row, dict):
                formatted_row['event_date'] = event_date  # Add date to row
                all_fights_data.append(formatted_row)
            else:
                print(f"Error processing {url}: {formatted_row}")
        except Exception as e:
            print(f"Error processing {url}: {str(e)}")
    
    return pd.DataFrame(all_fights_data) if all_fights_data else "No data processed"

fights_df = process_multiple_fights_with_date(fight_links)
fights_df.head()

p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Dricus Du Plessis,Khamzat Chimaev,0,0,13 of 29,37 of 47,44%,78%,45 of 68,529 of 567,1 of 1,12 of 17,100%,70%,1,0,0,0,0:53,21:40,0,0,0 of 0,1 of 2,---,50%,3 of 3,131 of 137,0 of 0,1 of 1,---,100%,0,0,0,0,0:00,4:47,13 of 29,37 of 47,44%,78%,10 of 24,28 of 36,2 of 4,3 of 5,1 of 1,6 of 6,10 of 25,12 of 19,0 of 0,0 of 0,3 of 4,25 of 28,0 of 0,1 of 2,---,50%,0 of 0,1 of 1,0 of 0,0 of 1,0 of 0,0 of 0,0 of 0,0 of 1,0 of 0,0 of 0,0 of 0,1 of 1,Decision - Unanimous,Marc Goddard,0
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Lerone Murphy,Aaron Pico,1,0,8 of 16,13 of 29,50%,44%,8 of 16,13 of 30,0 of 0,2 of 3,---,66%,1,0,0,0,0:00,2:01,1,0,8 of 16,13 of 29,50%,44%,8 of 16,13 of 30,0 of 0,2 of 3,---,66%,1,0,0,0,0:00,2:01,8 of 16,13 of 29,50%,44%,4 of 9,7 of 23,4 of 6,5 of 5,0 of 1,1 of 1,6 of 14,7 of 21,1 of 1,3 of 5,1 of 1,3 of 3,8 of 16,13 of 29,50%,44%,4 of 9,7 of 23,4 of 6,5 of 5,0 of 1,1 of 1,6 of 14,7 of 21,1 of 1,3 of 5,1 of 1,3 of 3,KO/TKO,Herb Dean,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Geoff Neal,Carlos Prates,0,1,25 of 49,32 of 60,51%,53%,26 of 50,32 of 60,0 of 1,0 of 0,0%,---,0,0,0,0,0:15,0:00,0,1,25 of 49,32 of 60,51%,53%,26 of 50,32 of 60,0 of 1,0 of 0,0%,---,0,0,0,0,0:15,0:00,25 of 49,32 of 60,51%,53%,16 of 38,17 of 45,4 of 6,8 of 8,5 of 5,7 of 7,23 of 45,32 of 58,2 of 4,0 of 2,0 of 0,0 of 0,25 of 49,32 of 60,51%,53%,16 of 38,17 of 45,4 of 6,8 of 8,5 of 5,7 of 7,23 of 45,32 of 58,2 of 4,0 of 2,0 of 0,0 of 0,KO/TKO,Jason Herzog,0
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Jared Cannonier,Michael Page,0,0,20 of 57,29 of 55,35%,52%,46 of 88,36 of 64,2 of 7,0 of 1,28%,0%,0,0,0,0,8:14,0:01,0,0,2 of 16,11 of 20,12%,55%,10 of 24,11 of 21,0 of 3,0 of 1,0%,0%,0,0,0,0,2:10,0:00,20 of 57,29 of 55,35%,52%,10 of 45,19 of 45,4 of 6,8 of 8,6 of 6,2 of 2,11 of 45,27 of 53,3 of 4,2 of 2,6 of 8,0 of 0,2 of 16,11 of 20,12%,55%,0 of 14,5 of 14,1 of 1,5 of 5,1 of 1,1 of 1,2 of 16,10 of 19,0 of 0,1 of 1,0 of 0,0 of 0,Decision - Unanimous,Marc Goddard,0
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Tim Elliott,Kai Asakura,0,0,27 of 71,21 of 87,38%,24%,42 of 88,38 of 104,2 of 3,0 of 0,66%,---,2,0,0,0,1:54,0:01,0,0,16 of 40,11 of 45,40%,24%,24 of 50,20 of 54,1 of 1,0 of 0,100%,---,0,0,0,0,0:49,0:01,27 of 71,21 of 87,38%,24%,18 of 43,17 of 79,2 of 18,3 of 7,7 of 10,1 of 1,26 of 69,21 of 87,0 of 0,0 of 0,1 of 2,0 of 0,16 of 40,11 of 45,40%,24%,9 of 24,8 of 40,1 of 8,3 of 5,6 of 8,0 of 0,15 of 39,11 of 45,0 of 0,0 of 0,1 of 1,0 of 0,Submission,Robert Madrigal,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Baisangur Susurkaev,Eric Nolan,0,0,36 of 62,22 of 56,58%,39%,59 of 89,24 of 58,2 of 7,0 of 1,28%,0%,1,0,0,0,3:19,0:17,0,0,19 of 37,18 of 49,51%,36%,28 of 48,20 of 51,2 of 7,0 of 1,28%,0%,0,0,0,0,1:55,0:17,36 of 62,22 of 56,58%,39%,23 of 46,17 of 51,7 of 10,5 of 5,6 of 6,0 of 0,22 of 42,18 of 47,2 of 3,4 of 9,12 of 17,0 of 0,19 of 37,18 of 49,51%,36%,9 of 24,16 of 47,6 of 9,2 of 2,4 of 4,0 of 0,17 of 34,15 of 41,2 of 3,3 of 8,0 of 0,0 of 0,Submission,Jason Herzog,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Gerald Meerschaert,Michal Oleksiejczuk,0,1,3 of 16,23 of 51,18%,45%,3 of 16,23 of 51,0 of 3,0 of 0,0%,---,0,0,0,0,0:00,0:22,0,1,3 of 16,23 of 51,18%,45%,3 of 16,23 of 51,0 of 3,0 of 0,0%,---,0,0,0,0,0:00,0:22,3 of 16,23 of 51,18%,45%,2 of 14,18 of 46,0 of 0,5 of 5,1 of 2,0 of 0,3 of 16,11 of 31,0 of 0,0 of 0,0 of 0,12 of 20,3 of 16,23 of 51,18%,45%,2 of 14,18 of 46,0 of 0,5 of 5,1 of 2,0 of 0,3 of 16,11 of 31,0 of 0,0 of 0,0 of 0,12 of 20,KO/TKO,Herb Dean,0
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Jessica Andrade,Loopy Godinez,0,0,90 of 287,107 of 213,31%,50%,97 of 297,119 of 226,0 of 1,1 of 14,0%,7%,0,0,0,0,0:17,1:33,0,0,18 of 83,40 of 71,21%,56%,18 of 83,41 of 72,0 of 0,0 of 3,---,0%,0,0,0,0,0:00,0:00,90 of 287,107 of 213,31%,50%,58 of 242,91 of 195,21 of 31,12 of 14,11 of 14,4 of 4,87 of 279,94 of 195,3 of 8,11 of 16,0 of 0,2 of 2,18 of 83,40 of 71,21%,56%,13 of 75,31 of 62,2 of 3,6 of 6,3 of 5,3 of 3,17 of 82,39 of 70,1 of 1,1 of 1,0 of 0,0 of 0,Decision - Unanimous,Nick Cimmarusti,0
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Chase Hooper,Alexander Hernandez,0,1,20 of 82,17 of 38,24%,44%,20 of 82,18 of 39,0 of 2,0 of 0,0%,---,0,0,0,0,0:05,0:02,0,1,20 of 82,17 of 38,24%,44%,20 of 82,18 of 39,0 of 2,0 of 0,0%,---,0,0,0,0,0:05,0:02,20 of 82,17 of 38,24%,44%,7 of 62,14 of 35,7 of 12,3 of 3,6 of 8,0 of 0,20 of 81,13 of 33,0 of 1,0 of 0,0 of 0,4 of 5,20 of 82,17 of 38,24%,44%,7 of 62,14 of 35,7 of 12,3 of 3,6 of 8,0 of 0,20 of 81,13 of 33,0 of 1,0 of 0,0 of 0,4 of 5,KO/TKO,Jason Herzog,0
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Edson Barboza,Drakkar Klose,0,0,71 of 120,53 of 102,59%,51%,73 of 122,147 of 209,0 of 0,0 of 2,---,0%,0,0,0,0,3:50,2:33,0,0,24 of 36,15 of 29,66%,51%,26 of 38,68 of 89,0 of 0,0 of 1,---,0%,0,0,0,0,1:26,0:33,71 of 120,53 of 102,59%,51%,26 of 64,35 of 78,32 of 38,6 of 9,13 of 18,12 of 15,57 of 105,43 of 89,14 of 15,10 of 13,0 of 0,0 of 0,24 of 36,15 of 29,66%,51%,4 of 11,8 of 18,13 of 17,1 of 3,7 of 8,6 of 8,18 of 30,13 of 27,6 of 6,2 of 2,0 of 0,0 of 0,Decision - Unanimous,Marc Goddard,0
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Karine Silva,Dione Barbosa,0,0,26 of 70,31 of 87,37%,35%,90 of 154,67 of 132,1 of 3,3 of 4,33%,75%,2,1,1,1,2:23,5:18,0,0,10 of 30,15 of 41,33%,36%,11 of 31,19 of 47,0 of 1,1 of 1,0%,100%,0,1,0,0,0:00,0:44,26 of 70,31 of 87,37%,35%,11 of 50,11 of 62,9 of 14,15 of 19,6 of 6,5 of 6,22 of 66,26 of 80,4 of 4,4 of 5,0 of 0,1 of 2,10 of 30,15 of 41,33%,36%,6 of 24,4 of 27,3 of 5,7 of 9,1 of 1,4 of 5,10 of 30,15 of 41,0 of 0,0 of 0,0 of 0,0 of 0,Decision - Unanimous,Robert Madrigal,1

,p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner,event_date
0,Dricus Du Plessis,Khamzat Chimaev,0,0,13 of 29,37 of 47,44%,78%,45 of 68,529 of 567,1 of 1,12 of 17,100%,70%,1,0,0,0,0:53,21:40,0,0,0 of 0,1 of 2,---,50%,3 of 3,131 of 137,0 of 0,1 of 1,---,100%,0,0,0,0,0:00,4:47,13 of 29,37 of 47,44%,78%,10 of 24,28 of 36,2 of 4,3 of 5,1 of 1,6 of 6,10 of 25,12 of 19,0 of 0,0 of 0,3 of 4,25 of 28,0 of 0,1 of 2,---,50%,0 of 0,1 of 1,0 of 0,0 of 1,0 of 0,0 of 0,0 of 0,0 of 1,0 of 0,0 of 0,0 of 0,1 of 1,Decision - Unanimous,Marc Goddard,0,"August 16, 2025"
1,Lerone Murphy,Aaron Pico,1,0,8 of 16,13 of 29,50%,44%,8 of 16,13 of 30,0 of 0,2 of 3,---,66%,1,0,0,0,0:00,2:01,1,0,8 of 16,13 of 29,50%,44%,8 of 16,13 of 30,0 of 0,2 of 3,---,66%,1,0,0,0,0:00,2:01,8 of 16,13 of 29,50%,44%,4 of 9,7 of 23,4 of 6,5 of 5,0 of 1,1 of 1,6 of 14,7 of 21,1 of 1,3 of 5,1 of 1,3 of 3,8 of 16,13 of 29,50%,44%,4 of 9,7 of 23,4 of 6,5 of 5,0 of 1,1 of 1,6 of 14,7 of 21,1 of 1,3 of 5,1 of 1,3 of 3,KO/TKO,Herb Dean,1,"August 16, 2025"
2,Geoff Neal,Carlos Prates,0,1,25 of 49,32 of 60,51%,53%,26 of 50,32 of 60,0 of 1,0 of 0,0%,---,0,0,0,0,0:15,0:00,0,1,25 of 49,32 of 60,51%,53%,26 of 50,32 of 60,0 of 1,0 of 0,0%,---,0,0,0,0,0:15,0:00,25 of 49,32 of 60,51%,53%,16 of 38,17 of 45,4 of 6,8 of 8,5 of 5,7 of 7,23 of 45,32 of 58,2 of 4,0 of 2,0 of 0,0 of 0,25 of 49,32 of 60,51%,53%,16 of 38,17 of 45,4 of 6,8 of 8,5 of 5,7 of 7,23 of 45,32 of 58,2 of 4,0 of 2,0 of 0,0 of 0,KO/TKO,Jason Herzog,0,"August 16, 2025"
3,Jared Cannonier,Michael Page,0,0,20 of 57,29 of 55,35%,52%,46 of 88,36 of 64,2 of 7,0 of 1,28%,0%,0,0,0,0,8:14,0:01,0,0,2 of 16,11 of 20,12%,55%,10 of 24,11 of 21,0 of 3,0 of 1,0%,0%,0,0,0,0,2:10,0:00,20 of 57,29 of 55,35%,52%,10 of 45,19 of 45,4 of 6,8 of 8,6 of 6,2 of 2,11 of 45,27 of 53,3 of 4,2 of 2,6 of 8,0 of 0,2 of 16,11 of 20,12%,55%,0 of 14,5 of 14,1 of 1,5 of 5,1 of 1,1 of 1,2 of 16,10 of 19,0 of 0,1 of 1,0 of 0,0 of 0,Decision - Unanimous,Marc Goddard,0,"August 16, 2025"
4,Tim Elliott,Kai Asakura,0,0,27 of 71,21 of 87,38%,24%,42 of 88,38 of 104,2 of 3,0 of 0,66%,---,2,0,0,0,1:54,0:01,0,0,16 of 40,11 of 45,40%,24%,24 of 50,20 of 54,1 of 1,0 of 0,100%,---,0,0,0,0,0:49,0:01,27 of 71,21 of 87,38%,24%,18 of 43,17 of 79,2 of 18,3 of 7,7 of 10,1 of 1,26 of 69,21 of 87,0 of 0,0 of 0,1 of 2,0 of 0,16 of 40,11 of 45,40%,24%,9 of 24,8 of 40,1 of 8,3 of 5,6 of 8,0 of 0,15 of 39,11 of 45,0 of 0,0 of 0,1 of 1,0 of 0,Submission,Robert Madrigal,1,"August 16, 2025"

In [22]:
#clean fights_df

#replace '--' values and turn percents to decimals
percent_cols = ['p1_SIG_STR_PCT', 'p2_SIG_STR_PCT', 'p1_TD_PCT', 'p2_TD_PCT', 'p1_R1_SIG_STR_PCT', 'p2_R1_SIG_STR_PCT', 'p1_R1_TD_PCT', 'p2_R1_TD_PCT', 'p1_SIG_STR_PCT_DETAILED', 'p2_SIG_STR_PCT_DETAILED', 'p1_R1_SIG_STR_PCT_DETAILED', 'p2_R1_SIG_STR_PCT_DETAILED']
for col in percent_cols:
    fights_df[col] = (
        fights_df[col]
        .astype(str)
        .replace({'--': np.nan, '---': np.nan})  # Handle missing values first
        .str.replace('%', '', regex=False)  # Remove percentage symbols
        .str.strip()  # Clean whitespace
        .astype(float) / 100  # Convert to decimal
    )


#format event date
# fights_df['event_date'] = pd.to_datetime(fights_df['event_date'], errors='coerce')
#format event date - clean and standardize first
def clean_date_string(s):
    if pd.isna(s):
        return s
    s = str(s).strip()  # remove leading/trailing spaces
    s = s.strip('"').strip("'")  # remove quotes if any
    s = s.split(' ')[0]  # keep only date part, ignore time
    return s

fights_df['event_date'] = fights_df['event_date'].apply(clean_date_string)
fights_df['event_date'] = pd.to_datetime(fights_df['event_date'], errors='coerce')


# columns to split
cols_to_split = ['p1_SIG_STR', 'p2_SIG_STR', 'p1_TOTAL_STR', 'p2_TOTAL_STR', 'p1_TD', 'p2_TD', 'p1_R1_SIG_STR', 'p2_R1_SIG_STR', 'p1_R1_TOTAL_STR', 'p2_R1_TOTAL_STR', 'p1_R1_TD', 'p2_R1_TD', 'p1_SIG_STR_LANDED_ATTEMPTED', 'p2_SIG_STR_LANDED_ATTEMPTED', 'p1_HEAD_LANDED_ATTEMPTED', 'p2_HEAD_LANDED_ATTEMPTED', 'p1_BODY_LANDED_ATTEMPTED', 'p2_BODY_LANDED_ATTEMPTED', 'p1_LEG_LANDED_ATTEMPTED', 'p2_LEG_LANDED_ATTEMPTED', 'p1_DISTANCE_LANDED_ATTEMPTED', 'p2_DISTANCE_LANDED_ATTEMPTED', 'p1_CLINCH_LANDED_ATTEMPTED', 'p2_CLINCH_LANDED_ATTEMPTED', 'p1_GROUND_LANDED_ATTEMPTED', 'p2_GROUND_LANDED_ATTEMPTED', 'p1_R1_SIG_STR_LANDED_ATTEMPTED', 'p2_R1_SIG_STR_LANDED_ATTEMPTED', 'p1_R1_HEAD_LANDED_ATTEMPTED', 'p2_R1_HEAD_LANDED_ATTEMPTED', 'p1_R1_BODY_LANDED_ATTEMPTED', 'p2_R1_BODY_LANDED_ATTEMPTED', 'p1_R1_LEG_LANDED_ATTEMPTED', 'p2_R1_LEG_LANDED_ATTEMPTED', 'p1_R1_DISTANCE_LANDED_ATTEMPTED', 'p2_R1_DISTANCE_LANDED_ATTEMPTED', 'p1_R1_CLINCH_LANDED_ATTEMPTED', 'p2_R1_CLINCH_LANDED_ATTEMPTED', 'p1_R1_GROUND_LANDED_ATTEMPTED', 'p2_R1_GROUND_LANDED_ATTEMPTED']

#Loop over them, split into “_LANDED” and “_ATTEMPTED”, convert to ints
for col in cols_to_split:
    # decide new column names
    if col.endswith('_LANDED_ATTEMPTED'):
        base = col.rsplit('_', 2)[0]       # turns 'p1_HEAD_LANDED_ATTEMPTED' → 'p1_HEAD'
        landed_col    = f"{base}_LANDED"
        attempted_col = f"{base}_ATTEMPTED"
    else:
        # for columns like 'p1_SIG_STR'
        landed_col    = f"{col}_LANDED"
        attempted_col = f"{col}_ATTEMPTED"

    # split “63 of 129” → ['63','129'], then to numeric
    fights_df[[landed_col, attempted_col]] = (
        fights_df[col]
          .str.split(' of ', expand=True)
          .astype(int)
    )

# Drop the originals
fights_df.drop(columns=cols_to_split, inplace=True)


# time collumns needing reformatting
time_cols = ['p1_CTRL', 'p2_CTRL', 'p1_R1_CTRL', 'p2_R1_CTRL' ]

#Convert each to total seconds
for col in time_cols:
    # Replace non-time strings with NaN
    fights_df[col] = fights_df[col].replace({'--': np.nan, '---': np.nan})
    
    # Convert to "00:MM:SS" format then to seconds
    fights_df[col] = (
        pd.to_timedelta('00:' + fights_df[col].fillna('00:00'), errors='coerce')
        .dt.total_seconds()
        .astype('Int64')  # Allows integer NaNs
    )

fights_df.head(10)

/var/folders/nc/04zwxn450f3cllk4tzq8_fp40000gn/T/ipykernel_75652/588613312.py:28: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  fights_df['event_date'] = pd.to_datetime(fights_df['event_date'], errors='coerce')

,p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,method,referee,winner,event_date,p1_SIG_STR_LANDED,p1_SIG_STR_ATTEMPTED,p2_SIG_STR_LANDED,p2_SIG_STR_ATTEMPTED,p1_TOTAL_STR_LANDED,p1_TOTAL_STR_ATTEMPTED,p2_TOTAL_STR_LANDED,p2_TOTAL_STR_ATTEMPTED,p1_TD_LANDED,p1_TD_ATTEMPTED,p2_TD_LANDED,p2_TD_ATTEMPTED,p1_R1_SIG_STR_LANDED,p1_R1_SIG_STR_ATTEMPTED,p2_R1_SIG_STR_LANDED,p2_R1_SIG_STR_ATTEMPTED,p1_R1_TOTAL_STR_LANDED,p1_R1_TOTAL_STR_ATTEMPTED,p2_R1_TOTAL_STR_LANDED,p2_R1_TOTAL_STR_ATTEMPTED,p1_R1_TD_LANDED,p1_R1_TD_ATTEMPTED,p2_R1_TD_LANDED,p2_R1_TD_ATTEMPTED,p1_HEAD_LANDED,p1_HEAD_ATTEMPTED,p2_HEAD_LANDED,p2_HEAD_ATTEMPTED,p1_BODY_LANDED,p1_BODY_ATTEMPTED,p2_BODY_LANDED,p2_BODY_ATTEMPTED,p1_LEG_LANDED,p1_LEG_ATTEMPTED,p2_LEG_LANDED,p2_LEG_ATTEMPTED,p1_DISTANCE_LANDED,p1_DISTANCE_ATTEMPTED,p2_DISTANCE_LANDED,p2_DISTANCE_ATTEMPTED,p1_CLINCH_LANDED,p1_CLINCH_ATTEMPTED,p2_CLINCH_LANDED,p2_CLINCH_ATTEMPTED,p1_GROUND_LANDED,p1_GROUND_ATTEMPTED,p2_GROUND_LANDED,p2_GROUND_ATTEMPTED,p1_R1_HEAD_LANDED,p1_R1_HEAD_ATTEMPTED,p2_R1_HEAD_LANDED,p2_R1_HEAD_ATTEMPTED,p1_R1_BODY_LANDED,p1_R1_BODY_ATTEMPTED,p2_R1_BODY_LANDED,p2_R1_BODY_ATTEMPTED,p1_R1_LEG_LANDED,p1_R1_LEG_ATTEMPTED,p2_R1_LEG_LANDED,p2_R1_LEG_ATTEMPTED,p1_R1_DISTANCE_LANDED,p1_R1_DISTANCE_ATTEMPTED,p2_R1_DISTANCE_LANDED,p2_R1_DISTANCE_ATTEMPTED,p1_R1_CLINCH_LANDED,p1_R1_CLINCH_ATTEMPTED,p2_R1_CLINCH_LANDED,p2_R1_CLINCH_ATTEMPTED,p1_R1_GROUND_LANDED,p1_R1_GROUND_ATTEMPTED,p2_R1_GROUND_LANDED,p2_R1_GROUND_ATTEMPTED
0,Dricus Du Plessis,Khamzat Chimaev,0,0,0.44,0.78,1.00,0.70,1,0,0,0,53,1300,0,0,NaN,0.50,NaN,1.00,0,0,0,0,0,287,0.44,0.78,NaN,0.50,Decision - Unanimous,Marc Goddard,0,NaT,13,29,37,47,45,68,529,567,1,1,12,17,0,0,1,2,3,3,131,137,0,0,1,1,10,24,28,36,2,4,3,5,1,1,6,6,10,25,12,19,0,0,0,0,3,4,25,28,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1
1,Lerone Murphy,Aaron Pico,1,0,0.50,0.44,NaN,0.66,1,0,0,0,0,121,1,0,0.50,0.44,NaN,0.66,1,0,0,0,0,121,0.50,0.44,0.50,0.44,KO/TKO,Herb Dean,1,NaT,8,16,13,29,8,16,13,30,0,0,2,3,8,16,13,29,8,16,13,30,0,0,2,3,4,9,7,23,4,6,5,5,0,1,1,1,6,14,7,21,1,1,3,5,1,1,3,3,4,9,7,23,4,6,5,5,0,1,1,1,6,14,7,21,1,1,3,5,1,1,3,3
2,Geoff Neal,Carlos Prates,0,1,0.51,0.53,0.00,NaN,0,0,0,0,15,0,0,1,0.51,0.53,0.00,NaN,0,0,0,0,15,0,0.51,0.53,0.51,0.53,KO/TKO,Jason Herzog,0,NaT,25,49,32,60,26,50,32,60,0,1,0,0,25,49,32,60,26,50,32,60,0,1,0,0,16,38,17,45,4,6,8,8,5,5,7,7,23,45,32,58,2,4,0,2,0,0,0,0,16,38,17,45,4,6,8,8,5,5,7,7,23,45,32,58,2,4,0,2,0,0,0,0
3,Jared Cannonier,Michael Page,0,0,0.35,0.52,0.28,0.00,0,0,0,0,494,1,0,0,0.12,0.55,0.00,0.00,0,0,0,0,130,0,0.35,0.52,0.12,0.55,Decision - Unanimous,Marc Goddard,0,NaT,20,57,29,55,46,88,36,64,2,7,0,1,2,16,11,20,10,24,11,21,0,3,0,1,10,45,19,45,4,6,8,8,6,6,2,2,11,45,27,53,3,4,2,2,6,8,0,0,0,14,5,14,1,1,5,5,1,1,1,1,2,16,10,19,0,0,1,1,0,0,0,0
4,Tim Elliott,Kai Asakura,0,0,0.38,0.24,0.66,NaN,2,0,0,0,114,1,0,0,0.40,0.24,1.00,NaN,0,0,0,0,49,1,0.38,0.24,0.40,0.24,Submission,Robert Madrigal,1,NaT,27,71,21,87,42,88,38,104,2,3,0,0,16,40,11,45,24,50,20,54,1,1,0,0,18,43,17,79,2,18,3,7,7,10,1,1,26,69,21,87,0,0,0,0,1,2,0,0,9,24,8,40,1,8,3,5,6,8,0,0,15,39,11,45,0,0,0,0,1,1,0,0
5,Baisangur Susurkaev,Eric Nolan,0,0,0.58,0.39,0.28,0.00,1,0,0,0,199,17,0,0,0.51,0.36,0.28,0.00,0,0,0,0,115,17,0.58,0.39,0.51,0.36,Submission,Jason Herzog,1,NaT,36,62,22,56,59,89,24,58,2,7,0,1,19,37,18,49,28,48,20,51,2,7,0,1,23,46,17,51,7,10,5,5,6,6,0,0,22,42,18,47,2,3,4,9,12,17,0,0,9,24,16,47,6,9,2,2,4,4,0,0,17,34,15,41,2,3,3,8,0,0,0,0
6,Gerald Meerschaert,Michal Oleksiejczuk,0,1,0.18,0.45,0.00,NaN,0,0,0,0,0,22,0,1,0.18,0.45,0.00,NaN,0,0,0,0,0,22,0.18,0.45,0.18,0.45,KO/TKO,Herb Dean,0,NaT,3,16,23,51,3,16,23,51,0,3,0,0,3,16,23,51,3,16,23,51,0,3,0,0,2,14,18,46,0,0,5,5,1,2,0,0,3,16,11,31,0,0,0,0,0,0,12,20,2,14,18,46,0,0,5,5,1,2,0,0,3,16,11,31,0,0,0,0,0,0,12,20
7,Jessica Andrade,Loopy Godinez,0,0,0.31,0.50,0.00,0.07,0,0,0,0,17,93,0,0,0.21,0.56,NaN,0.00,0,0,0,0,0,0,0.31,0.50,0.21,0.56,Decision - Unanimous,Nick Cimmarusti,0,NaT,90,287,107,213,97,297,119,226,0,1,1,14,18,83,40,71,18,83,41,72,0,0,0,3,58,242,91,195,21,31,12,14,11,14,4,4,87,279,94,195,3,8,11,16,0,0,2,2,13,75,31,62,2,3,6,6,3,5,3,3,17,82,39,70,1,1,1,1,0,0,0,0
8,Chase Hooper,Alexander Hernandez,0,1,0.24,0.44,0.00,NaN,0,0,0,0,5,2,0,1,0.24,0.44,0.00,NaN,0,0,0,0,5,2,0.24,0.44,0.24,0.44,KO/TKO,Jason Herzog,0,NaT,20,82,17,38,20,82,18,39,0,2,0,0,20,82,17,38,20,82,18,39,0,2,0,0,7,62,14,35,7,12,3,3,6,8,0,0,20,81,13,33,0,1,0,0,0,0,4,5,7,62,14,35,7,12,3,3,6,8,0,0,20,81,13,33,0,1,0,0,0,0,4,5
9,Edson Barboza,Drakkar Klose,0,0,0.59,0.51,NaN,0.00,0,0,0,0,230,153,0,0,0.66,0.51,NaN,0.00,0,0,0,0,86,33,0.59,0.51,0.66,0.51,Decision - Unanimous,Marc Goddard,0,NaT,71,120,53,102,73,122,147,209,0,0,0,2,24,36,15,29,26,38,68,89,0,0,0,1,26,64,35,78,32,38,6,9,13,18,12,15,57,105,43,89,14,15,10,13,0,0,0,0,4,11,8,18,13,17,1,3,7,8,6,8,18,30,13,27,6,6,2,2,0,0,0,0

In [23]:
# merge the two datasets

# First, merge p1 fighter stats
fights_df = fights_df.merge(
    fighters_df,
    left_on='p1_fighter',
    right_on='name',  # This matches p1_fighter with the name column in fighters_df
    how='left'
)
fights_df.drop(columns=['name'], inplace=True)

# Only include the specific columns you want to rename with p1_ prefix
p1_cols = ['height', 'weight', 'reach', 'stance', 'dob', 'SLpM', 'Str. Acc.', 'SApM', 'Str. Def', 'TD Avg.', 'TD Acc.', 'TD Def.', 'Sub. Avg.']
fights_df.rename(columns={col: f'p1_{col}' for col in p1_cols}, inplace=True)

# Then merge p2 fighter stats
fights_df = fights_df.merge(
    fighters_df,
    left_on='p2_fighter',
    right_on='name',  # This matches p2_fighter with the name column in fighters_df
    how='left'
)
fights_df.drop(columns=['name'], inplace=True)

# Use the same columns for p2 as we did for p1
p2_cols = ['height', 'weight', 'reach', 'stance', 'dob', 'SLpM', 'Str. Acc.', 'SApM', 'Str. Def', 'TD Avg.', 'TD Acc.', 'TD Def.', 'Sub. Avg.']
fights_df.rename(columns={col: f'p2_{col}' for col in p2_cols}, inplace=True)


# Drop unwanted columns
columns_to_drop = ['record_x', 'wins_x', 'losses_x', 'draws_x', 'nc_x', 'record_y', 'wins_y', 'losses_y', 'draws_y', 'nc_y', 'url_x', 'url_y']

# Check if columns exist before trying to drop them
existing_columns = [col for col in columns_to_drop if col in fights_df.columns]
if existing_columns:
    fights_df.drop(columns=existing_columns, inplace=True)


#-------------------------
# cleaned_df = fights_df      # update the cleaned csv so that we cna retarin the features_df to update the model and calculating ema
#-------------------------


fights_df.head()

,p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,method,referee,winner,event_date,p1_SIG_STR_LANDED,p1_SIG_STR_ATTEMPTED,p2_SIG_STR_LANDED,p2_SIG_STR_ATTEMPTED,p1_TOTAL_STR_LANDED,p1_TOTAL_STR_ATTEMPTED,p2_TOTAL_STR_LANDED,p2_TOTAL_STR_ATTEMPTED,p1_TD_LANDED,p1_TD_ATTEMPTED,p2_TD_LANDED,p2_TD_ATTEMPTED,p1_R1_SIG_STR_LANDED,p1_R1_SIG_STR_ATTEMPTED,p2_R1_SIG_STR_LANDED,p2_R1_SIG_STR_ATTEMPTED,p1_R1_TOTAL_STR_LANDED,p1_R1_TOTAL_STR_ATTEMPTED,p2_R1_TOTAL_STR_LANDED,p2_R1_TOTAL_STR_ATTEMPTED,p1_R1_TD_LANDED,p1_R1_TD_ATTEMPTED,p2_R1_TD_LANDED,p2_R1_TD_ATTEMPTED,p1_HEAD_LANDED,p1_HEAD_ATTEMPTED,p2_HEAD_LANDED,p2_HEAD_ATTEMPTED,p1_BODY_LANDED,p1_BODY_ATTEMPTED,p2_BODY_LANDED,p2_BODY_ATTEMPTED,p1_LEG_LANDED,p1_LEG_ATTEMPTED,p2_LEG_LANDED,p2_LEG_ATTEMPTED,p1_DISTANCE_LANDED,p1_DISTANCE_ATTEMPTED,p2_DISTANCE_LANDED,p2_DISTANCE_ATTEMPTED,p1_CLINCH_LANDED,p1_CLINCH_ATTEMPTED,p2_CLINCH_LANDED,p2_CLINCH_ATTEMPTED,p1_GROUND_LANDED,p1_GROUND_ATTEMPTED,p2_GROUND_LANDED,p2_GROUND_ATTEMPTED,p1_R1_HEAD_LANDED,p1_R1_HEAD_ATTEMPTED,p2_R1_HEAD_LANDED,p2_R1_HEAD_ATTEMPTED,p1_R1_BODY_LANDED,p1_R1_BODY_ATTEMPTED,p2_R1_BODY_LANDED,p2_R1_BODY_ATTEMPTED,p1_R1_LEG_LANDED,p1_R1_LEG_ATTEMPTED,p2_R1_LEG_LANDED,p2_R1_LEG_ATTEMPTED,p1_R1_DISTANCE_LANDED,p1_R1_DISTANCE_ATTEMPTED,p2_R1_DISTANCE_LANDED,p2_R1_DISTANCE_ATTEMPTED,p1_R1_CLINCH_LANDED,p1_R1_CLINCH_ATTEMPTED,p2_R1_CLINCH_LANDED,p2_R1_CLINCH_ATTEMPTED,p1_R1_GROUND_LANDED,p1_R1_GROUND_ATTEMPTED,p2_R1_GROUND_LANDED,p2_R1_GROUND_ATTEMPTED,p1_height,p1_weight,p1_reach,p1_stance,p1_dob,p1_SLpM,p1_Str. Acc.,p1_SApM,p1_Str. Def,p1_TD Avg.,p1_TD Acc.,p1_TD Def.,p1_Sub. Avg.,p2_height,p2_weight,p2_reach,p2_stance,p2_dob,p2_SLpM,p2_Str. Acc.,p2_SApM,p2_Str. Def,p2_TD Avg.,p2_TD Acc.,p2_TD Def.,p2_Sub. Avg.
0,Dricus Du Plessis,Khamzat Chimaev,0,0,0.44,0.78,1.00,0.70,1,0,0,0,53,1300,0,0,NaN,0.50,NaN,1.00,0,0,0,0,0,287,0.44,0.78,NaN,0.50,Decision - Unanimous,Marc Goddard,0,NaT,13,29,37,47,45,68,529,567,1,1,12,17,0,0,1,2,3,3,131,137,0,0,1,1,10,24,28,36,2,4,3,5,1,1,6,6,10,25,12,19,0,0,0,0,3,4,25,28,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,73.0,185.0,76.0,Switch,1994-01-14,6.12,0.48,4.90,0.54,2.55,0.50,0.50,0.7,74.0,185.0,75.0,Orthodox,1994-05-01,5.36,0.58,3.25,0.41,4.31,0.46,1.00,2.8
1,Lerone Murphy,Aaron Pico,1,0,0.50,0.44,NaN,0.66,1,0,0,0,0,121,1,0,0.50,0.44,NaN,0.66,1,0,0,0,0,121,0.50,0.44,0.50,0.44,KO/TKO,Herb Dean,1,NaT,8,16,13,29,8,16,13,30,0,0,2,3,8,16,13,29,8,16,13,30,0,0,2,3,4,9,7,23,4,6,5,5,0,1,1,1,6,14,7,21,1,1,3,5,1,1,3,3,4,9,7,23,4,6,5,5,0,1,1,1,6,14,7,21,1,1,3,5,1,1,3,3,69.0,145.0,73.0,Orthodox,1991-07-22,4.53,0.54,2.48,0.61,1.45,0.54,0.52,0.5,NaN,145.0,NaN,Orthodox,1996-09-23,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
2,Geoff Neal,Carlos Prates,0,1,0.51,0.53,0.00,NaN,0,0,0,0,15,0,0,1,0.51,0.53,0.0,NaN,0,0,0,0,15,0,0.51,0.53,0.51,0.53,KO/TKO,Jason Herzog,0,NaT,25,49,32,60,26,50,32,60,0,1,0,0,25,49,32,60,26,50,32,60,0,1,0,0,16,38,17,45,4,6,8,8,5,5,7,7,23,45,32,58,2,4,0,2,0,0,0,0,16,38,17,45,4,6,8,8,5,5,7,7,23,45,32,58,2,4,0,2,0,0,0,0,71.0,170.0,75.0,Southpaw,1990-08-28,5.05,0.51,5.44,0.57,0.56,0.50,0.87,0.1,73.0,170.0,78.0,Switch,1993-08-17,3.60,0.54,4.79,0.48,0.25,1.00,0.83,0.0
3,Jared Cannonier,Michael Page,0,0,0.35,0.52,0.28,0.00,0,0,0,0,494,1,0,0,0.12,0.55,0.0,0.00,0,0,0,0,130,0,0.35,0.52,0.12,0.55,Decision - Unanimous,Marc Goddard,0,NaT,20,57,29,55,46,88,36,64,2,7,0,1,2,16,11,20,10,24,11,21,0,3,0,1,10,45,19,45,4,6,8,8,6,6,2,2,11,45,27,53,3,4,2,2,6,8,0,0,0,14,5,14,1,1,5,5,1,1,1,1,2,16,10,19,0,0,1,1,0,0,0,0,71.0,185.0,77.0,Switch,1984-03-16,4.60,0.50,4.49,0.56,0.46,0.44,0.64,0.0,75.0,185.0,79.0,Switch,1987-04-07,2.53,0.62,1.78,0.55,0.30,0.20,0.63,0.0
4,Tim Elliott,Kai Asakura,0,0,0.38,0.24,0.66,NaN,2,0,0,0,114,1,0,0,0.40,0.24,1.0,NaN,0,0,0,0,49,1,0.38,0.24,0.40,0.24,Submission,Robert Madrigal,1,NaT,27,71,21,87,42,88,38,104,2,3,0,0,16,40,11,45,24,50,20,54,1,1,0,0,18,43,17,79,2,18,3,7,7,10,1,1,26,69,21,87,0,0,0,0,1,2,0,0,9,24,8,40,1,8,3,5,6,8,0,0,15,39,11,45,0,0,0,0,1,1,0,0,67.0,125.0,66.0,Southpaw,1986-12-24,3.39,0.44,2.66,0.56,3.73,0.47,0.59,1.0,68.0,125.0,69.0,Orthodox,1993-10-31,2.40,0.58,4.52,0.38,0.00,0.00,0.57,0.0

In [24]:
f_df = pd.read_csv('ufc_cleaned.csv')

f_df = pd.concat([fights_df, f_df], ignore_index=True)

f_df.to_csv('ufc_cleaned.csv', index=False)