In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
fighters_df = pd.read_csv('ufc_fighters_cleaned.csv')

url = "http://ufcstats.com/statistics/events/completed?page=all"
headers = {'User-Agent': 'Mozilla/5.0'}

response = requests.get(url, headers=headers)
response.raise_for_status()
soup = BeautifulSoup(response.content, 'html.parser')

first_tag = soup.select_one('a.b-link.b-link_style_black[href*="event-details"]')
first_event_link = first_tag['href'] if first_tag else None

print(first_event_link)

http://ufcstats.com/event-details/69108cb8b32efe04

In [2]:
fight_links = []

if first_event_link:
    # fetch the single event page
    resp = requests.get(first_event_link, headers=headers)
    resp.raise_for_status()
    ev_soup = BeautifulSoup(resp.content, 'html.parser')

    # extract the event date
    date_el = ev_soup.find('li', class_='b-list__box-list-item')
    event_date = date_el.text.split(':')[-1].strip() if date_el else 'N/A'

    # find every fight row and pull out the onclick URL
    for row in ev_soup.select('tr.b-fight-details__table-row'):
        onclick = row.get('onclick','')
        if 'doNav' in onclick:
            fight_url = onclick.split("'")[1]
            fight_links.append({
                'url': fight_url,
                'event_date': event_date
            })

print(fight_links)

[{'url': 'http://ufcstats.com/fight-details/346e3897c2ead99a', 'event_date': 'March 21, 2026'}, {'url': 'http://ufcstats.com/fight-details/fa534aaa5b997a69', 'event_date': 'March 21, 2026'}, {'url': 'http://ufcstats.com/fight-details/5ee11b727e89e8ad', 'event_date': 'March 21, 2026'}, {'url': 'http://ufcstats.com/fight-details/43e26b46cbb51985', 'event_date': 'March 21, 2026'}, {'url': 'http://ufcstats.com/fight-details/562d916f55918901', 'event_date': 'March 21, 2026'}, {'url': 'http://ufcstats.com/fight-details/4e58bcc0d27042fd', 'event_date': 'March 21, 2026'}, {'url': 'http://ufcstats.com/fight-details/3ee578ddd071ad4c', 'event_date': 'March 21, 2026'}, {'url': 'http://ufcstats.com/fight-details/3b9f50f07d9a1601', 'event_date': 'March 21, 2026'}, {'url': 'http://ufcstats.com/fight-details/90187edeeda7e6d6', 'event_date': 'March 21, 2026'}, {'url': 'http://ufcstats.com/fight-details/8817bd21b6d0a989', 'event_date': 'March 21, 2026'}, {'url': 'http://ufcstats.com/fight-details/bfd17ed83ec5b598', 'event_date': 'March 21, 2026'}, {'url': 'http://ufcstats.com/fight-details/bbe0f3653de9f6a8', 'event_date': 'March 21, 2026'}, {'url': 'http://ufcstats.com/fight-details/216bc9b661485017', 'event_date': 'March 21, 2026'}]

In [3]:
def scrape_ufc_fight_details(url): # scrapes the stats from the url we input
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Extract method of victory
    method_tag = soup.find('i', class_='b-fight-details__text-item_first')
    method = method_tag.find('i', style="font-style: normal").text.strip() if method_tag else ''
    
    # Extract referee
    referee = ""
    referee_span = soup.select_one('i.b-fight-details__label:-soup-contains("Referee:") + span')
    if referee_span:
        referee = referee_span.text.strip()

    # Find fighter status (W/L) for the first fighter
    fighter_status_tag = soup.find('i', class_='b-fight-details__person-status')
    first_fighter_won = None
    if fighter_status_tag:
        status = fighter_status_tag.text.strip()
        first_fighter_won = 1 if status == "W" else 0
    

    # get the data from round 1 and the totals rows
    all_rows = []
    rows = soup.find_all('tr', class_='b-fight-details__table-row')

    for row in rows:
        columns = row.find_all('p', class_='b-fight-details__table-text')
        data = [col.get_text(strip=True) for col in columns]
        all_rows.append(data)
    
    totals = 1
    r1_totals = 3
    sigTotals = int(len(all_rows) / 2 + 1)
    r1_sigTotals = sigTotals + 2
    
    filtered_rows = []
    
    def is_valid_row(arr):
        needed_indexes = [totals, r1_totals, sigTotals, r1_sigTotals]
        for idx in needed_indexes:
            if idx < len(all_rows):  # Make sure index is valid
                arr.append(all_rows[idx])
    
    is_valid_row(filtered_rows)
    
    # Append method of victory and referee as a new array at the end
    filtered_rows.append([method, referee])
    filtered_rows.append(first_fighter_won)

    return filtered_rows

# Test with the example URL
url = 'http://ufcstats.com/fight-details/d05cb4c4135ce402'
data = scrape_ufc_fight_details(url)
print(data)

[['Michael Chandler', 'Paddy Pimblett', '0', '0', '11 of 28', '80 of 143', '39%', '55%', '20 of 39', '121 of 197', '4 of 7', '1 of 2', '57%', '50%', '0', '0', '0', '1', '2:44', '4:41'], ['Michael Chandler', 'Paddy Pimblett', '0', '0', '5 of 11', '16 of 40', '45%', '40%', '7 of 14', '25 of 50', '2 of 3', '0 of 0', '66%', '---', '0', '0', '0', '0', '2:10', '0:00'], ['Michael Chandler', 'Paddy Pimblett', '11 of 28', '80 of 143', '39%', '55%', '6 of 18', '61 of 119', '3 of 7', '4 of 5', '2 of 3', '15 of 19', '10 of 24', '43 of 96', '0 of 0', '4 of 5', '1 of 4', '33 of 42'], ['Michael Chandler', 'Paddy Pimblett', '5 of 11', '16 of 40', '45%', '40%', '4 of 10', '7 of 28', '1 of 1', '1 of 2', '0 of 0', '8 of 10', '4 of 7', '16 of 40', '0 of 0', '0 of 0', '1 of 4', '0 of 0'], ['KO/TKO', 'Kerry Hatley'], 0]

In [4]:
def format_fight_data_single_row(data): #formats the data extracted from a match into a dictionary
    if not data or len(data) < 4:
        return "Not enough data to format."
    
    # Extract fighter names for reference
    fighter1 = data[0][0]
    fighter2 = data[0][1]
    
    # Create a single row dictionary with p1_ and p2_ prefixes
    formatted_row = {
        "p1_fighter": fighter1,
        "p2_fighter": fighter2,
        
        # Totals (Row 1)
        "p1_KD": data[0][2],
        "p2_KD": data[0][3],
        "p1_SIG_STR": data[0][4],
        "p2_SIG_STR": data[0][5],
        "p1_SIG_STR_PCT": data[0][6],
        "p2_SIG_STR_PCT": data[0][7],
        "p1_TOTAL_STR": data[0][8],
        "p2_TOTAL_STR": data[0][9],
        "p1_TD": data[0][10],
        "p2_TD": data[0][11],
        "p1_TD_PCT": data[0][12],
        "p2_TD_PCT": data[0][13],
        "p1_SUB_ATT": data[0][14],
        "p2_SUB_ATT": data[0][15],
        "p1_REV": data[0][16],
        "p2_REV": data[0][17],
        "p1_CTRL": data[0][18],
        "p2_CTRL": data[0][19],
        
        # Round 1 Totals (Row 2)
        "p1_R1_KD": data[1][2],
        "p2_R1_KD": data[1][3],
        "p1_R1_SIG_STR": data[1][4],
        "p2_R1_SIG_STR": data[1][5],
        "p1_R1_SIG_STR_PCT": data[1][6],
        "p2_R1_SIG_STR_PCT": data[1][7],
        "p1_R1_TOTAL_STR": data[1][8],
        "p2_R1_TOTAL_STR": data[1][9],
        "p1_R1_TD": data[1][10],
        "p2_R1_TD": data[1][11],
        "p1_R1_TD_PCT": data[1][12],
        "p2_R1_TD_PCT": data[1][13],
        "p1_R1_SUB_ATT": data[1][14],
        "p2_R1_SUB_ATT": data[1][15],
        "p1_R1_REV": data[1][16],
        "p2_R1_REV": data[1][17],
        "p1_R1_CTRL": data[1][18],
        "p2_R1_CTRL": data[1][19],
        
        # Significant Strike Details (Row 3)
        "p1_SIG_STR_LANDED_ATTEMPTED": data[2][2],
        "p2_SIG_STR_LANDED_ATTEMPTED": data[2][3],
        "p1_SIG_STR_PCT_DETAILED": data[2][4],
        "p2_SIG_STR_PCT_DETAILED": data[2][5],
        "p1_HEAD_LANDED_ATTEMPTED": data[2][6],
        "p2_HEAD_LANDED_ATTEMPTED": data[2][7],
        "p1_BODY_LANDED_ATTEMPTED": data[2][8],
        "p2_BODY_LANDED_ATTEMPTED": data[2][9],
        "p1_LEG_LANDED_ATTEMPTED": data[2][10],
        "p2_LEG_LANDED_ATTEMPTED": data[2][11],
        "p1_DISTANCE_LANDED_ATTEMPTED": data[2][12],
        "p2_DISTANCE_LANDED_ATTEMPTED": data[2][13],
        "p1_CLINCH_LANDED_ATTEMPTED": data[2][14],
        "p2_CLINCH_LANDED_ATTEMPTED": data[2][15],
        "p1_GROUND_LANDED_ATTEMPTED": data[2][16],
        "p2_GROUND_LANDED_ATTEMPTED": data[2][17],
        
        # Round 1 Significant Strike Details (Row 4)
        "p1_R1_SIG_STR_LANDED_ATTEMPTED": data[3][2],
        "p2_R1_SIG_STR_LANDED_ATTEMPTED": data[3][3],
        "p1_R1_SIG_STR_PCT_DETAILED": data[3][4],
        "p2_R1_SIG_STR_PCT_DETAILED": data[3][5],
        "p1_R1_HEAD_LANDED_ATTEMPTED": data[3][6],
        "p2_R1_HEAD_LANDED_ATTEMPTED": data[3][7],
        "p1_R1_BODY_LANDED_ATTEMPTED": data[3][8],
        "p2_R1_BODY_LANDED_ATTEMPTED": data[3][9],
        "p1_R1_LEG_LANDED_ATTEMPTED": data[3][10],
        "p2_R1_LEG_LANDED_ATTEMPTED": data[3][11],
        "p1_R1_DISTANCE_LANDED_ATTEMPTED": data[3][12],
        "p2_R1_DISTANCE_LANDED_ATTEMPTED": data[3][13],
        "p1_R1_CLINCH_LANDED_ATTEMPTED": data[3][14],
        "p2_R1_CLINCH_LANDED_ATTEMPTED": data[3][15],
        "p1_R1_GROUND_LANDED_ATTEMPTED": data[3][16],
        "p2_R1_GROUND_LANDED_ATTEMPTED": data[3][17],

        "method": data[4][0],
        "referee": data[4][1],
        "winner": data[5]
    }
    
    # Print column headers once (useful for CSV export)
    print(",".join(formatted_row.keys()))
    
    # Print the values as a single row
    print(",".join(str(val) for val in formatted_row.values()))
    
    return formatted_row

# Call the function with your scraped data
formatted_row = format_fight_data_single_row(data)
print(formatted_row)

p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Michael Chandler,Paddy Pimblett,0,0,11 of 28,80 of 143,39%,55%,20 of 39,121 of 197,4 of 7,1 of 2,57%,50%,0,0,0,1,2:44,4:41,0,0,5 of 11,16 of 40,45%,40%,7 of 14,25 of 50,2 of 3,0 of 0,66%,---,0,0,0,0,2:10,0:00,11 of 28,80 of 143,39%,55%,6 of 18,61 of 119,3 of 7,4 of 5,2 of 3,15 of 19,10 of 24,43 of 96,0 of 0,4 of 5,1 of 4,33 of 42,5 of 11,16 of 40,45%,40%,4 of 10,7 of 28,1 of 1,1 of 2,0 of 0,8 of 10,4 of 7,16 of 40,0 of 0,0 of 0,1 of 4,0 of 0,KO/TKO,Kerry Hatley,0
{'p1_fighter': 'Michael Chandler', 'p2_fighter': 'Paddy Pimblett', 'p1_KD': '0', 'p2_KD': '0', 'p1_SIG_STR': '11 of 28', 'p2_SIG_STR': '80 of 143', 'p1_SIG_STR_PCT': '39%', 'p2_SIG_STR_PCT': '55%', 'p1_TOTAL_STR': '20 of 39', 'p2_TOTAL_STR': '121 of 197', 'p1_TD': '4 of 7', 'p2_TD': '1 of 2', 'p1_TD_PCT': '57%', 'p2_TD_PCT': '50%', 'p1_SUB_ATT': '0', 'p2_SUB_ATT': '0', 'p1_REV': '0', 'p2_REV': '1', 'p1_CTRL': '2:44', 'p2_CTRL': '4:41', 'p1_R1_KD': '0', 'p2_R1_KD': '0', 'p1_R1_SIG_STR': '5 of 11', 'p2_R1_SIG_STR': '16 of 40', 'p1_R1_SIG_STR_PCT': '45%', 'p2_R1_SIG_STR_PCT': '40%', 'p1_R1_TOTAL_STR': '7 of 14', 'p2_R1_TOTAL_STR': '25 of 50', 'p1_R1_TD': '2 of 3', 'p2_R1_TD': '0 of 0', 'p1_R1_TD_PCT': '66%', 'p2_R1_TD_PCT': '---', 'p1_R1_SUB_ATT': '0', 'p2_R1_SUB_ATT': '0', 'p1_R1_REV': '0', 'p2_R1_REV': '0', 'p1_R1_CTRL': '2:10', 'p2_R1_CTRL': '0:00', 'p1_SIG_STR_LANDED_ATTEMPTED': '11 of 28', 'p2_SIG_STR_LANDED_ATTEMPTED': '80 of 143', 'p1_SIG_STR_PCT_DETAILED': '39%', 'p2_SIG_STR_PCT_DETAILED': '55%', 'p1_HEAD_LANDED_ATTEMPTED': '6 of 18', 'p2_HEAD_LANDED_ATTEMPTED': '61 of 119', 'p1_BODY_LANDED_ATTEMPTED': '3 of 7', 'p2_BODY_LANDED_ATTEMPTED': '4 of 5', 'p1_LEG_LANDED_ATTEMPTED': '2 of 3', 'p2_LEG_LANDED_ATTEMPTED': '15 of 19', 'p1_DISTANCE_LANDED_ATTEMPTED': '10 of 24', 'p2_DISTANCE_LANDED_ATTEMPTED': '43 of 96', 'p1_CLINCH_LANDED_ATTEMPTED': '0 of 0', 'p2_CLINCH_LANDED_ATTEMPTED': '4 of 5', 'p1_GROUND_LANDED_ATTEMPTED': '1 of 4', 'p2_GROUND_LANDED_ATTEMPTED': '33 of 42', 'p1_R1_SIG_STR_LANDED_ATTEMPTED': '5 of 11', 'p2_R1_SIG_STR_LANDED_ATTEMPTED': '16 of 40', 'p1_R1_SIG_STR_PCT_DETAILED': '45%', 'p2_R1_SIG_STR_PCT_DETAILED': '40%', 'p1_R1_HEAD_LANDED_ATTEMPTED': '4 of 10', 'p2_R1_HEAD_LANDED_ATTEMPTED': '7 of 28', 'p1_R1_BODY_LANDED_ATTEMPTED': '1 of 1', 'p2_R1_BODY_LANDED_ATTEMPTED': '1 of 2', 'p1_R1_LEG_LANDED_ATTEMPTED': '0 of 0', 'p2_R1_LEG_LANDED_ATTEMPTED': '8 of 10', 'p1_R1_DISTANCE_LANDED_ATTEMPTED': '4 of 7', 'p2_R1_DISTANCE_LANDED_ATTEMPTED': '16 of 40', 'p1_R1_CLINCH_LANDED_ATTEMPTED': '0 of 0', 'p2_R1_CLINCH_LANDED_ATTEMPTED': '0 of 0', 'p1_R1_GROUND_LANDED_ATTEMPTED': '1 of 4', 'p2_R1_GROUND_LANDED_ATTEMPTED': '0 of 0', 'method': 'KO/TKO', 'referee': 'Kerry Hatley', 'winner': 0}

In [5]:
def process_multiple_fights_with_date(url_date_list): # gets the data from every match and creates a dataframe from it 
    all_fights_data = []
    
    for item in url_date_list:
        url = item['url']
        event_date = item['event_date']
        try:
            fight_data = scrape_ufc_fight_details(url)
            formatted_row = format_fight_data_single_row(fight_data)  
            if isinstance(formatted_row, dict):
                formatted_row['event_date'] = event_date  # Add date to row
                all_fights_data.append(formatted_row)
            else:
                print(f"Error processing {url}: {formatted_row}")
        except Exception as e:
            print(f"Error processing {url}: {str(e)}")
    
    return pd.DataFrame(all_fights_data) if all_fights_data else "No data processed"

fights_df = process_multiple_fights_with_date(fight_links)

p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Movsar Evloev,Lerone Murphy,0,0,86 of 189,89 of 239,45%,37%,124 of 234,89 of 239,9 of 10,0 of 0,90%,---,0,0,0,0,3:54,0:00,0,0,11 of 31,14 of 49,35%,28%,11 of 31,14 of 49,0 of 0,0 of 0,---,---,0,0,0,0,0:00,0:00,86 of 189,89 of 239,45%,37%,47 of 134,45 of 175,33 of 44,24 of 38,6 of 11,20 of 26,80 of 178,89 of 238,1 of 2,0 of 1,5 of 9,0 of 0,11 of 31,14 of 49,35%,28%,3 of 21,6 of 35,6 of 7,4 of 8,2 of 3,4 of 6,11 of 31,14 of 49,0 of 0,0 of 0,0 of 0,0 of 0,Decision - Majority,Marc Goddard,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Luke Riley,Michael Aswell Jr.,0,0,100 of 177,61 of 180,56%,33%,113 of 192,107 of 233,0 of 0,1 of 1,---,100%,0,0,0,0,0:00,2:49,0,0,33 of 56,20 of 59,58%,33%,45 of 68,54 of 95,0 of 0,0 of 0,---,---,0,0,0,0,0:00,1:05,100 of 177,61 of 180,56%,33%,65 of 134,48 of 158,31 of 36,13 of 21,4 of 7,0 of 1,90 of 166,58 of 169,10 of 11,3 of 11,0 of 0,0 of 0,33 of 56,20 of 59,58%,33%,22 of 42,17 of 52,10 of 11,3 of 6,1 of 3,0 of 1,30 of 53,18 of 53,3 of 3,2 of 6,0 of 0,0 of 0,Decision - Unanimous,Jason Herzog,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Michael Page,Sam Patterson,0,0,27 of 55,12 of 64,49%,18%,33 of 61,25 of 78,0 of 0,0 of 2,---,0%,0,0,0,0,0:26,2:47,0,0,5 of 12,4 of 11,41%,36%,5 of 12,4 of 11,0 of 0,0 of 0,---,---,0,0,0,0,0:00,0:00,27 of 55,12 of 64,49%,18%,17 of 38,4 of 50,4 of 8,4 of 6,6 of 9,4 of 8,27 of 55,10 of 60,0 of 0,2 of 4,0 of 0,0 of 0,5 of 12,4 of 11,41%,36%,3 of 7,2 of 8,1 of 4,1 of 1,1 of 1,1 of 2,5 of 12,4 of 11,0 of 0,0 of 0,0 of 0,0 of 0,Decision - Unanimous,Rich Mitchell,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Iwo Baraniewski,Austen Lane,1,0,10 of 13,0 of 4,76%,0%,10 of 13,0 of 4,0 of 0,0 of 0,---,---,0,0,0,0,0:04,0:00,1,0,10 of 13,0 of 4,76%,0%,10 of 13,0 of 4,0 of 0,0 of 0,---,---,0,0,0,0,0:04,0:00,10 of 13,0 of 4,76%,0%,9 of 12,0 of 3,0 of 0,0 of 0,1 of 1,0 of 1,2 of 5,0 of 4,0 of 0,0 of 0,8 of 8,0 of 0,10 of 13,0 of 4,76%,0%,9 of 12,0 of 3,0 of 0,0 of 0,1 of 1,0 of 1,2 of 5,0 of 4,0 of 0,0 of 0,8 of 8,0 of 0,KO/TKO,Lukasz Bosacki,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Roman Dolidze,Christian Leroy Duncan,0,0,10 of 34,54 of 99,29%,54%,40 of 94,78 of 125,3 of 4,0 of 2,75%,0%,0,0,0,0,7:07,1:08,0,0,2 of 6,16 of 29,33%,55%,3 of 7,23 of 36,2 of 2,0 of 1,100%,0%,0,0,0,0,2:33,0:37,10 of 34,54 of 99,29%,54%,8 of 31,18 of 52,0 of 0,6 of 12,2 of 3,30 of 35,9 of 33,51 of 92,1 of 1,1 of 4,0 of 0,2 of 3,2 of 6,16 of 29,33%,55%,2 of 6,5 of 17,0 of 0,2 of 3,0 of 0,9 of 9,2 of 6,13 of 24,0 of 0,1 of 2,0 of 0,2 of 3,Decision - Unanimous,Jason Herzog,0
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Kurtis Campbell,Danny Silva,0,2,17 of 41,16 of 32,41%,50%,17 of 43,20 of 36,2 of 5,1 of 1,40%,100%,0,0,0,1,1:56,1:05,0,0,15 of 36,6 of 20,41%,30%,15 of 38,9 of 23,2 of 5,1 of 1,40%,100%,0,0,0,1,1:56,0:56,17 of 41,16 of 32,41%,50%,12 of 29,11 of 26,2 of 8,4 of 5,3 of 4,1 of 1,15 of 39,11 of 23,2 of 2,4 of 7,0 of 0,1 of 2,15 of 36,6 of 20,41%,30%,10 of 24,3 of 16,2 of 8,2 of 3,3 of 4,1 of 1,13 of 34,5 of 17,2 of 2,0 of 2,0 of 0,1 of 1,KO/TKO,Rich Mitchell,0
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Mason Jones,Axel Sola,0,0,110 of 236,65 of 135,46%,48%,123 of 251,68 of 141,0 of 0,3 of 7,---,42%,0,0,0,0,0:05,2:19,0,0,18 of 46,15 of 32,39%,46%,27 of 55,18 of 38,0 of 0,2 of 4,---,50%,0,0,0,0,0:00,1:45,110 of 236,65 of 135,46%,48%,76 of 193,49 of 116,29 of 37,16 of 19,5 of 6,0 of 0,83 of 193,61 of 125,26 of 42,4 of 10,1 of 1,0 of 0,18 of 46,15 of 32,39%,46%,12 of 39,13 of 28,4 of 5,2 of 4,2 of 2,0 of 0,16 of 40,14 of 28,2 of 6,1 of 4,0 of 0,0 of 0,Decision - Unanimous,Marc Goddard,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Nathaniel Wood,Losene Keita,0,0,67 of 178,52 of 119,37%,43%,67 of 178,52 of 119,0 of 1,0 of 0,0%,---,0,0,0,0,0:00,0:00,0,0,17 of 56,11 of 26,30%,42%,17 of 56,11 of 26,0 of 1,0 of 0,0%,---,0,0,0,0,0:00,0:00,67 of 178,52 of 119,37%,43%,32 of 128,36 of 101,2 of 3,13 of 15,33 of 47,3 of 3,67 of 177,52 of 119,0 of 1,0 of 0,0 of 0,0 of 0,17 of 56,11 of 26,30%,42%,7 of 42,8 of 22,2 of 3,3 of 4,8 of 11,0 of 0,17 of 55,11 of 26,0 of 1,0 of 0,0 of 0,0 of 0,Decision - Split,Jason Herzog,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Mario Pinto,Felipe Franco,0,0,34 of 58,21 of 60,58%,35%,137 of 166,60 of 100,2 of 14,0 of 1,14%,0%,0,0,0,0,6:15,0:00,0,0,16 of 28,9 of 25,57%,36%,37 of 49,16 of 32,0 of 2,0 of 0,0%,---,0,0,0,0,0:28,0:00,34 of 58,21 of 60,58%,35%,25 of 48,13 of 51,6 of 7,7 of 8,3 of 3,1 of 1,20 of 42,13 of 51,13 of 15,8 of 9,1 of 1,0 of 0,16 of 28,9 of 25,57%,36%,12 of 23,6 of 21,2 of 3,2 of 3,2 of 2,1 of 1,12 of 23,8 of 24,4 of 5,1 of 1,0 of 0,0 of 0,Decision - Unanimous,Lukasz Bosacki,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Mantas Kondratavicius,Antonio Trocoli,1,0,75 of 107,17 of 39,70%,43%,135 of 177,29 of 54,2 of 4,1 of 12,50%,8%,1,0,0,0,6:06,5:03,0,0,28 of 42,6 of 14,66%,42%,41 of 56,9 of 19,0 of 0,0 of 1,---,0%,0,0,0,0,1:52,1:33,75 of 107,17 of 39,70%,43%,61 of 93,10 of 28,14 of 14,3 of 7,0 of 0,4 of 4,42 of 68,15 of 35,17 of 19,2 of 4,16 of 20,0 of 0,28 of 42,6 of 14,66%,42%,19 of 33,2 of 10,9 of 9,2 of 2,0 of 0,2 of 2,19 of 32,4 of 12,9 of 10,2 of 2,0 of 0,0 of 0,Decision - Unanimous,Rich Mitchell,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Louie Sutherland,Brando Pericic,0,0,9 of 18,19 of 26,50%,73%,9 of 18,34 of 46,1 of 3,0 of 0,33%,---,0,0,0,0,0:40,0:19,0,0,9 of 18,19 of 26,50%,73%,9 of 18,34 of 46,1 of 3,0 of 0,33%,---,0,0,0,0,0:40,0:19,9 of 18,19 of 26,50%,73%,5 of 14,13 of 20,2 of 2,6 of 6,2 of 2,0 of 0,7 of 15,5 of 9,2 of 3,9 of 10,0 of 0,5 of 7,9 of 18,19 of 26,50%,73%,5 of 14,13 of 20,2 of 2,6 of 6,2 of 2,0 of 0,7 of 15,5 of 9,2 of 3,9 of 10,0 of 0,5 of 7,KO/TKO,Marc Goddard,0

In [6]:
#clean fights_df

#replace '--' values and turn percents to decimals
percent_cols = ['p1_SIG_STR_PCT', 'p2_SIG_STR_PCT', 'p1_TD_PCT', 'p2_TD_PCT', 'p1_R1_SIG_STR_PCT', 'p2_R1_SIG_STR_PCT', 'p1_R1_TD_PCT', 'p2_R1_TD_PCT', 'p1_SIG_STR_PCT_DETAILED', 'p2_SIG_STR_PCT_DETAILED', 'p1_R1_SIG_STR_PCT_DETAILED', 'p2_R1_SIG_STR_PCT_DETAILED']
for col in percent_cols:
    fights_df[col] = (
        fights_df[col]
        .astype(str)
        .replace({'--': np.nan, '---': np.nan})  # Handle missing values first
        .str.replace('%', '', regex=False)  # Remove percentage symbols
        .str.strip()  # Clean whitespace
        .astype(float) / 100  # Convert to decimal
    )


def clean_date_string(s):
    if pd.isna(s):
        return s
    s = str(s).strip()  # remove leading/trailing spaces
    s = s.strip('"').strip("'")  # remove quotes if any
    return s

fights_df['event_date'] = fights_df['event_date'].apply(clean_date_string)
# First convert from "December 13, 2025" to datetime, then to "YYYY-MM-DD" string format
fights_df['event_date'] = pd.to_datetime(fights_df['event_date'], format='%B %d, %Y', errors='coerce')
# Convert datetime to string in YYYY-MM-DD format to match the existing dataset
fights_df['event_date'] = fights_df['event_date'].dt.strftime('%Y-%m-%d')


# columns to split
cols_to_split = ['p1_SIG_STR', 'p2_SIG_STR', 'p1_TOTAL_STR', 'p2_TOTAL_STR', 'p1_TD', 'p2_TD', 'p1_R1_SIG_STR', 'p2_R1_SIG_STR', 'p1_R1_TOTAL_STR', 'p2_R1_TOTAL_STR', 'p1_R1_TD', 'p2_R1_TD', 'p1_SIG_STR_LANDED_ATTEMPTED', 'p2_SIG_STR_LANDED_ATTEMPTED', 'p1_HEAD_LANDED_ATTEMPTED', 'p2_HEAD_LANDED_ATTEMPTED', 'p1_BODY_LANDED_ATTEMPTED', 'p2_BODY_LANDED_ATTEMPTED', 'p1_LEG_LANDED_ATTEMPTED', 'p2_LEG_LANDED_ATTEMPTED', 'p1_DISTANCE_LANDED_ATTEMPTED', 'p2_DISTANCE_LANDED_ATTEMPTED', 'p1_CLINCH_LANDED_ATTEMPTED', 'p2_CLINCH_LANDED_ATTEMPTED', 'p1_GROUND_LANDED_ATTEMPTED', 'p2_GROUND_LANDED_ATTEMPTED', 'p1_R1_SIG_STR_LANDED_ATTEMPTED', 'p2_R1_SIG_STR_LANDED_ATTEMPTED', 'p1_R1_HEAD_LANDED_ATTEMPTED', 'p2_R1_HEAD_LANDED_ATTEMPTED', 'p1_R1_BODY_LANDED_ATTEMPTED', 'p2_R1_BODY_LANDED_ATTEMPTED', 'p1_R1_LEG_LANDED_ATTEMPTED', 'p2_R1_LEG_LANDED_ATTEMPTED', 'p1_R1_DISTANCE_LANDED_ATTEMPTED', 'p2_R1_DISTANCE_LANDED_ATTEMPTED', 'p1_R1_CLINCH_LANDED_ATTEMPTED', 'p2_R1_CLINCH_LANDED_ATTEMPTED', 'p1_R1_GROUND_LANDED_ATTEMPTED', 'p2_R1_GROUND_LANDED_ATTEMPTED']

#Loop over them, split into “_LANDED” and “_ATTEMPTED”, convert to ints
for col in cols_to_split:
    # decide new column names
    if col.endswith('_LANDED_ATTEMPTED'):
        base = col.rsplit('_', 2)[0]       # turns 'p1_HEAD_LANDED_ATTEMPTED' → 'p1_HEAD'
        landed_col    = f"{base}_LANDED"
        attempted_col = f"{base}_ATTEMPTED"
    else:
        # for columns like 'p1_SIG_STR'
        landed_col    = f"{col}_LANDED"
        attempted_col = f"{col}_ATTEMPTED"

    # split “63 of 129” → ['63','129'], then to numeric
    fights_df[[landed_col, attempted_col]] = (
        fights_df[col]
          .str.split(' of ', expand=True)
          .astype(int)
    )

# Drop the originals
fights_df.drop(columns=cols_to_split, inplace=True)


# time collumns needing reformatting
time_cols = ['p1_CTRL', 'p2_CTRL', 'p1_R1_CTRL', 'p2_R1_CTRL' ]

#Convert each to total seconds
for col in time_cols:
    # Replace non-time strings with NaN
    fights_df[col] = fights_df[col].replace({'--': np.nan, '---': np.nan})
    
    # Convert to "00:MM:SS" format then to seconds
    fights_df[col] = (
        pd.to_timedelta('00:' + fights_df[col].fillna('00:00'), errors='coerce')
        .dt.total_seconds()
        .astype('Int64')  # Allows integer NaNs
    )

fights_df.head(20)

,p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,method,referee,winner,event_date,p1_SIG_STR_LANDED,p1_SIG_STR_ATTEMPTED,p2_SIG_STR_LANDED,p2_SIG_STR_ATTEMPTED,p1_TOTAL_STR_LANDED,p1_TOTAL_STR_ATTEMPTED,p2_TOTAL_STR_LANDED,p2_TOTAL_STR_ATTEMPTED,p1_TD_LANDED,p1_TD_ATTEMPTED,p2_TD_LANDED,p2_TD_ATTEMPTED,p1_R1_SIG_STR_LANDED,p1_R1_SIG_STR_ATTEMPTED,p2_R1_SIG_STR_LANDED,p2_R1_SIG_STR_ATTEMPTED,p1_R1_TOTAL_STR_LANDED,p1_R1_TOTAL_STR_ATTEMPTED,p2_R1_TOTAL_STR_LANDED,p2_R1_TOTAL_STR_ATTEMPTED,p1_R1_TD_LANDED,p1_R1_TD_ATTEMPTED,p2_R1_TD_LANDED,p2_R1_TD_ATTEMPTED,p1_HEAD_LANDED,p1_HEAD_ATTEMPTED,p2_HEAD_LANDED,p2_HEAD_ATTEMPTED,p1_BODY_LANDED,p1_BODY_ATTEMPTED,p2_BODY_LANDED,p2_BODY_ATTEMPTED,p1_LEG_LANDED,p1_LEG_ATTEMPTED,p2_LEG_LANDED,p2_LEG_ATTEMPTED,p1_DISTANCE_LANDED,p1_DISTANCE_ATTEMPTED,p2_DISTANCE_LANDED,p2_DISTANCE_ATTEMPTED,p1_CLINCH_LANDED,p1_CLINCH_ATTEMPTED,p2_CLINCH_LANDED,p2_CLINCH_ATTEMPTED,p1_GROUND_LANDED,p1_GROUND_ATTEMPTED,p2_GROUND_LANDED,p2_GROUND_ATTEMPTED,p1_R1_HEAD_LANDED,p1_R1_HEAD_ATTEMPTED,p2_R1_HEAD_LANDED,p2_R1_HEAD_ATTEMPTED,p1_R1_BODY_LANDED,p1_R1_BODY_ATTEMPTED,p2_R1_BODY_LANDED,p2_R1_BODY_ATTEMPTED,p1_R1_LEG_LANDED,p1_R1_LEG_ATTEMPTED,p2_R1_LEG_LANDED,p2_R1_LEG_ATTEMPTED,p1_R1_DISTANCE_LANDED,p1_R1_DISTANCE_ATTEMPTED,p2_R1_DISTANCE_LANDED,p2_R1_DISTANCE_ATTEMPTED,p1_R1_CLINCH_LANDED,p1_R1_CLINCH_ATTEMPTED,p2_R1_CLINCH_LANDED,p2_R1_CLINCH_ATTEMPTED,p1_R1_GROUND_LANDED,p1_R1_GROUND_ATTEMPTED,p2_R1_GROUND_LANDED,p2_R1_GROUND_ATTEMPTED
0,Movsar Evloev,Lerone Murphy,0,0,0.45,0.37,0.90,NaN,0,0,0,0,234,0,0,0,0.35,0.28,NaN,NaN,0,0,0,0,0,0,0.45,0.37,0.35,0.28,Decision - Majority,Marc Goddard,1,2026-03-21,86,189,89,239,124,234,89,239,9,10,0,0,11,31,14,49,11,31,14,49,0,0,0,0,47,134,45,175,33,44,24,38,6,11,20,26,80,178,89,238,1,2,0,1,5,9,0,0,3,21,6,35,6,7,4,8,2,3,4,6,11,31,14,49,0,0,0,0,0,0,0,0
1,Luke Riley,Michael Aswell Jr.,0,0,0.56,0.33,NaN,1.00,0,0,0,0,0,169,0,0,0.58,0.33,NaN,NaN,0,0,0,0,0,65,0.56,0.33,0.58,0.33,Decision - Unanimous,Jason Herzog,1,2026-03-21,100,177,61,180,113,192,107,233,0,0,1,1,33,56,20,59,45,68,54,95,0,0,0,0,65,134,48,158,31,36,13,21,4,7,0,1,90,166,58,169,10,11,3,11,0,0,0,0,22,42,17,52,10,11,3,6,1,3,0,1,30,53,18,53,3,3,2,6,0,0,0,0
2,Michael Page,Sam Patterson,0,0,0.49,0.18,NaN,0.00,0,0,0,0,26,167,0,0,0.41,0.36,NaN,NaN,0,0,0,0,0,0,0.49,0.18,0.41,0.36,Decision - Unanimous,Rich Mitchell,1,2026-03-21,27,55,12,64,33,61,25,78,0,0,0,2,5,12,4,11,5,12,4,11,0,0,0,0,17,38,4,50,4,8,4,6,6,9,4,8,27,55,10,60,0,0,2,4,0,0,0,0,3,7,2,8,1,4,1,1,1,1,1,2,5,12,4,11,0,0,0,0,0,0,0,0
3,Iwo Baraniewski,Austen Lane,1,0,0.76,0.00,NaN,NaN,0,0,0,0,4,0,1,0,0.76,0.00,NaN,NaN,0,0,0,0,4,0,0.76,0.00,0.76,0.00,KO/TKO,Lukasz Bosacki,1,2026-03-21,10,13,0,4,10,13,0,4,0,0,0,0,10,13,0,4,10,13,0,4,0,0,0,0,9,12,0,3,0,0,0,0,1,1,0,1,2,5,0,4,0,0,0,0,8,8,0,0,9,12,0,3,0,0,0,0,1,1,0,1,2,5,0,4,0,0,0,0,8,8,0,0
4,Roman Dolidze,Christian Leroy Duncan,0,0,0.29,0.54,0.75,0.00,0,0,0,0,427,68,0,0,0.33,0.55,1.00,0.0,0,0,0,0,153,37,0.29,0.54,0.33,0.55,Decision - Unanimous,Jason Herzog,0,2026-03-21,10,34,54,99,40,94,78,125,3,4,0,2,2,6,16,29,3,7,23,36,2,2,0,1,8,31,18,52,0,0,6,12,2,3,30,35,9,33,51,92,1,1,1,4,0,0,2,3,2,6,5,17,0,0,2,3,0,0,9,9,2,6,13,24,0,0,1,2,0,0,2,3
5,Kurtis Campbell,Danny Silva,0,2,0.41,0.50,0.40,1.00,0,0,0,1,116,65,0,0,0.41,0.30,0.40,1.0,0,0,0,1,116,56,0.41,0.50,0.41,0.30,KO/TKO,Rich Mitchell,0,2026-03-21,17,41,16,32,17,43,20,36,2,5,1,1,15,36,6,20,15,38,9,23,2,5,1,1,12,29,11,26,2,8,4,5,3,4,1,1,15,39,11,23,2,2,4,7,0,0,1,2,10,24,3,16,2,8,2,3,3,4,1,1,13,34,5,17,2,2,0,2,0,0,1,1
6,Mason Jones,Axel Sola,0,0,0.46,0.48,NaN,0.42,0,0,0,0,5,139,0,0,0.39,0.46,NaN,0.5,0,0,0,0,0,105,0.46,0.48,0.39,0.46,Decision - Unanimous,Marc Goddard,1,2026-03-21,110,236,65,135,123,251,68,141,0,0,3,7,18,46,15,32,27,55,18,38,0,0,2,4,76,193,49,116,29,37,16,19,5,6,0,0,83,193,61,125,26,42,4,10,1,1,0,0,12,39,13,28,4,5,2,4,2,2,0,0,16,40,14,28,2,6,1,4,0,0,0,0
7,Nathaniel Wood,Losene Keita,0,0,0.37,0.43,0.00,NaN,0,0,0,0,0,0,0,0,0.30,0.42,0.00,NaN,0,0,0,0,0,0,0.37,0.43,0.30,0.42,Decision - Split,Jason Herzog,1,2026-03-21,67,178,52,119,67,178,52,119,0,1,0,0,17,56,11,26,17,56,11,26,0,1,0,0,32,128,36,101,2,3,13,15,33,47,3,3,67,177,52,119,0,1,0,0,0,0,0,0,7,42,8,22,2,3,3,4,8,11,0,0,17,55,11,26,0,1,0,0,0,0,0,0
8,Mario Pinto,Felipe Franco,0,0,0.58,0.35,0.14,0.00,0,0,0,0,375,0,0,0,0.57,0.36,0.00,NaN,0,0,0,0,28,0,0.58,0.35,0.57,0.36,Decision - Unanimous,Lukasz Bosacki,1,2026-03-21,34,58,21,60,137,166,60,100,2,14,0,1,16,28,9,25,37,49,16,32,0,2,0,0,25,48,13,51,6,7,7,8,3,3,1,1,20,42,13,51,13,15,8,9,1,1,0,0,12,23,6,21,2,3,2,3,2,2,1,1,12,23,8,24,4,5,1,1,0,0,0,0
9,Mantas Kondratavicius,Antonio Trocoli,1,0,0.70,0.43,0.50,0.08,1,0,0,0,366,303,0,0,0.66,0.42,NaN,0.0,0,0,0,0,112,93,0.70,0.43,0.66,0.42,Decision - Unanimous,Rich Mitchell,1,2026-03-21,75,107,17,39,135,177,29,54,2,4,1,12,28,42,6,14,41,56,9,19,0,0,0,1,61,93,10,28,14,14,3,7,0,0,4,4,42,68,15,35,17,19,2,4,16,20,0,0,19,33,2,10,9,9,2,2,0,0,2,2,19,32,4,12,9,10,2,2,0,0,0,0
10,Louie Sutherland,Brando Pericic,0,0,0.50,0.73,0.33,NaN,0,0,0,0,40,19,0,0,0.50,0.73,0.33,NaN,0,0,0,0,40,19,0.50,0.73,0.50,0.73,KO/TKO,Marc Goddard,0,2026-03-21,9,18,19,26,9,18,34,46,1,3,0,0,9,18,19,26,9,18,34,46,1,3,0,0,5,14,13,20,2,2,6,6,2,2,0,0,7,15,5,9,2,3,9,10,0,0,5,7,5,14,13,20,2,2,6,6,2,2,0,0,7,15,5,9,2,3,9,10,0,0,5,7
11,Shem Rock,Abdul-Kareem Al-Selwady,0,0,0.36,0.55,0.16,0.00,0,0,0,0,55,19,0,0,0.36,0.51,0.00,0.0,0,0,0,0,30,2,0.36,0.55,0.36,0.51,Decision - Unanimous,Jason Herzog,0,2026-03-21,47,128,81,146,52,134,105,173,1,6,0,4,17,46,27,52,22,51,28,53,0,1,0,1,26,101,48,102,16,22,13,14,5,5,20,30,43,123,71,130,3,3,8,11,1,2,2,5,10,37,16,33,4,6,2,2,3,3,9,17,15,43,25,47,1,1,2,4,1,2,0,1
12,Shanelle Dyer,Ravena Oliveira,0,0,0.62,0.32,1.00,0.00,0,0,0,0,34,12,0,0,0.68,0.29,NaN,0.0,0,0,0,0,28,5,0.62,0.32,0.68,0.29,KO/TKO,Lukasz Bosacki,1,2026-03-21,49,78,26,80,50,79,32,86,1,1,0,1,32,47,20,67,33,48,26,73,0,0,0,1,22,42,16,65,13,17,9,10,14,19,1,5,35,57,24,78,8,11,2,2,6,10,0,0,13,24,11,54,8,8,8,9,11,15,1,4,28,43,18,65,4,4,2,2,0,0,0,0

In [7]:
# merge the two datasets

# First, merge p1 fighter stats
fights_df = fights_df.merge(
    fighters_df,
    left_on='p1_fighter',
    right_on='name',  # This matches p1_fighter with the name column in fighters_df
    how='left'
)
fights_df.drop(columns=['name'], inplace=True)

# Only include the specific columns you want to rename with p1_ prefix
p1_cols = ['height', 'weight', 'reach', 'stance', 'dob', 'SLpM', 'Str. Acc.', 'SApM', 'Str. Def', 'TD Avg.', 'TD Acc.', 'TD Def.', 'Sub. Avg.']
fights_df.rename(columns={col: f'p1_{col}' for col in p1_cols}, inplace=True)

# Then merge p2 fighter stats
fights_df = fights_df.merge(
    fighters_df,
    left_on='p2_fighter',
    right_on='name',  # This matches p2_fighter with the name column in fighters_df
    how='left'
)
fights_df.drop(columns=['name'], inplace=True)

# Use the same columns for p2 as we did for p1
p2_cols = ['height', 'weight', 'reach', 'stance', 'dob', 'SLpM', 'Str. Acc.', 'SApM', 'Str. Def', 'TD Avg.', 'TD Acc.', 'TD Def.', 'Sub. Avg.']
fights_df.rename(columns={col: f'p2_{col}' for col in p2_cols}, inplace=True)


# Drop unwanted columns
columns_to_drop = ['record_x', 'wins_x', 'losses_x', 'draws_x', 'nc_x', 'record_y', 'wins_y', 'losses_y', 'draws_y', 'nc_y', 'url_x', 'url_y']

# Check if columns exist before trying to drop them
existing_columns = [col for col in columns_to_drop if col in fights_df.columns]
if existing_columns:
    fights_df.drop(columns=existing_columns, inplace=True)


#-------------------------
# cleaned_df = fights_df      # update the cleaned csv so that we cna retarin the features_df to update the model and calculating ema
#-------------------------


fights_df.head(15)

,p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,method,referee,winner,event_date,p1_SIG_STR_LANDED,p1_SIG_STR_ATTEMPTED,p2_SIG_STR_LANDED,p2_SIG_STR_ATTEMPTED,p1_TOTAL_STR_LANDED,p1_TOTAL_STR_ATTEMPTED,p2_TOTAL_STR_LANDED,p2_TOTAL_STR_ATTEMPTED,p1_TD_LANDED,p1_TD_ATTEMPTED,p2_TD_LANDED,p2_TD_ATTEMPTED,p1_R1_SIG_STR_LANDED,p1_R1_SIG_STR_ATTEMPTED,p2_R1_SIG_STR_LANDED,p2_R1_SIG_STR_ATTEMPTED,p1_R1_TOTAL_STR_LANDED,p1_R1_TOTAL_STR_ATTEMPTED,p2_R1_TOTAL_STR_LANDED,p2_R1_TOTAL_STR_ATTEMPTED,p1_R1_TD_LANDED,p1_R1_TD_ATTEMPTED,p2_R1_TD_LANDED,p2_R1_TD_ATTEMPTED,p1_HEAD_LANDED,p1_HEAD_ATTEMPTED,p2_HEAD_LANDED,p2_HEAD_ATTEMPTED,p1_BODY_LANDED,p1_BODY_ATTEMPTED,p2_BODY_LANDED,p2_BODY_ATTEMPTED,p1_LEG_LANDED,p1_LEG_ATTEMPTED,p2_LEG_LANDED,p2_LEG_ATTEMPTED,p1_DISTANCE_LANDED,p1_DISTANCE_ATTEMPTED,p2_DISTANCE_LANDED,p2_DISTANCE_ATTEMPTED,p1_CLINCH_LANDED,p1_CLINCH_ATTEMPTED,p2_CLINCH_LANDED,p2_CLINCH_ATTEMPTED,p1_GROUND_LANDED,p1_GROUND_ATTEMPTED,p2_GROUND_LANDED,p2_GROUND_ATTEMPTED,p1_R1_HEAD_LANDED,p1_R1_HEAD_ATTEMPTED,p2_R1_HEAD_LANDED,p2_R1_HEAD_ATTEMPTED,p1_R1_BODY_LANDED,p1_R1_BODY_ATTEMPTED,p2_R1_BODY_LANDED,p2_R1_BODY_ATTEMPTED,p1_R1_LEG_LANDED,p1_R1_LEG_ATTEMPTED,p2_R1_LEG_LANDED,p2_R1_LEG_ATTEMPTED,p1_R1_DISTANCE_LANDED,p1_R1_DISTANCE_ATTEMPTED,p2_R1_DISTANCE_LANDED,p2_R1_DISTANCE_ATTEMPTED,p1_R1_CLINCH_LANDED,p1_R1_CLINCH_ATTEMPTED,p2_R1_CLINCH_LANDED,p2_R1_CLINCH_ATTEMPTED,p1_R1_GROUND_LANDED,p1_R1_GROUND_ATTEMPTED,p2_R1_GROUND_LANDED,p2_R1_GROUND_ATTEMPTED,p1_height,p1_weight,p1_reach,p1_stance,p1_dob,p1_SLpM,p1_Str. Acc.,p1_SApM,p1_Str. Def,p1_TD Avg.,p1_TD Acc.,p1_TD Def.,p1_Sub. Avg.,p2_height,p2_weight,p2_reach,p2_stance,p2_dob,p2_SLpM,p2_Str. Acc.,p2_SApM,p2_Str. Def,p2_TD Avg.,p2_TD Acc.,p2_TD Def.,p2_Sub. Avg.
0,Movsar Evloev,Lerone Murphy,0,0,0.45,0.37,0.90,NaN,0,0,0,0,234,0,0,0,0.35,0.28,NaN,NaN,0,0,0,0,0,0,0.45,0.37,0.35,0.28,Decision - Majority,Marc Goddard,1,2026-03-21,86,189,89,239,124,234,89,239,9,10,0,0,11,31,14,49,11,31,14,49,0,0,0,0,47,134,45,175,33,44,24,38,6,11,20,26,80,178,89,238,1,2,0,1,5,9,0,0,3,21,6,35,6,7,4,8,2,3,4,6,11,31,14,49,0,0,0,0,0,0,0,0,67.0,145.0,72.0,Orthodox,1994-02-11,3.99,0.48,2.66,0.60,4.67,0.48,0.61,0.2,69.0,145.0,73.0,Orthodox,1991-07-22,4.48,0.53,2.51,0.61,1.41,0.54,0.51,0.5
1,Luke Riley,Michael Aswell Jr.,0,0,0.56,0.33,NaN,1.00,0,0,0,0,0,169,0,0,0.58,0.33,NaN,NaN,0,0,0,0,0,65,0.56,0.33,0.58,0.33,Decision - Unanimous,Jason Herzog,1,2026-03-21,100,177,61,180,113,192,107,233,0,0,1,1,33,56,20,59,45,68,54,95,0,0,0,0,65,134,48,158,31,36,13,21,4,7,0,1,90,166,58,169,10,11,3,11,0,0,0,0,22,42,17,52,10,11,3,6,1,3,0,1,30,53,18,53,3,3,2,6,0,0,0,0,69.0,145.0,69.0,Orthodox,1999-06-30,2.55,0.60,1.27,0.46,0.00,0.00,0.42,0.0,68.0,145.0,69.0,Orthodox,2000-09-27,9.56,0.45,7.79,0.54,0.00,0.00,0.57,0.0
2,Michael Page,Sam Patterson,0,0,0.49,0.18,NaN,0.00,0,0,0,0,26,167,0,0,0.41,0.36,NaN,NaN,0,0,0,0,0,0,0.49,0.18,0.41,0.36,Decision - Unanimous,Rich Mitchell,1,2026-03-21,27,55,12,64,33,61,25,78,0,0,0,2,5,12,4,11,5,12,4,11,0,0,0,0,17,38,4,50,4,8,4,6,6,9,4,8,27,55,10,60,0,0,2,4,0,0,0,0,3,7,2,8,1,4,1,1,1,1,1,2,5,12,4,11,0,0,0,0,0,0,0,0,75.0,170.0,79.0,Switch,1987-04-07,2.39,0.60,1.68,0.57,0.23,0.16,0.66,0.0,75.0,170.0,78.0,Orthodox,1996-04-30,3.89,0.43,3.93,0.49,1.39,1.00,0.33,2.8
3,Iwo Baraniewski,Austen Lane,1,0,0.76,0.00,NaN,NaN,0,0,0,0,4,0,1,0,0.76,0.00,NaN,NaN,0,0,0,0,4,0,0.76,0.00,0.76,0.00,KO/TKO,Lukasz Bosacki,1,2026-03-21,10,13,0,4,10,13,0,4,0,0,0,0,10,13,0,4,10,13,0,4,0,0,0,0,9,12,0,3,0,0,0,0,1,1,0,1,2,5,0,4,0,0,0,0,8,8,0,0,9,12,0,3,0,0,0,0,1,1,0,1,2,5,0,4,0,0,0,0,8,8,0,0,72.0,205.0,73.0,Orthodox,1998-11-20,14.31,0.68,17.61,0.42,0.00,0.00,1.00,0.0,78.0,205.0,80.0,Orthodox,1987-11-09,2.74,0.50,2.23,0.40,1.52,0.28,0.33,0.0
4,Roman Dolidze,Christian Leroy Duncan,0,0,0.29,0.54,0.75,0.00,0,0,0,0,427,68,0,0,0.33,0.55,1.00,0.0,0,0,0,0,153,37,0.29,0.54,0.33,0.55,Decision - Unanimous,Jason Herzog,0,2026-03-21,10,34,54,99,40,94,78,125,3,4,0,2,2,6,16,29,3,7,23,36,2,2,0,1,8,31,18,52,0,0,6,12,2,3,30,35,9,33,51,92,1,1,1,4,0,0,2,3,2,6,5,17,0,0,2,3,0,0,9,9,2,6,13,24,0,0,1,2,0,0,2,3,74.0,185.0,76.0,Orthodox,1988-07-15,3.41,0.41,3.72,0.48,0.99,0.39,0.26,0.8,74.0,185.0,79.0,Switch,1995-07-24,4.60,0.58,2.97,0.51,0.40,0.20,0.69,0.0
5,Kurtis Campbell,Danny Silva,0,2,0.41,0.50,0.40,1.00,0,0,0,1,116,65,0,0,0.41,0.30,0.40,1.0,0,0,0,1,116,56,0.41,0.50,0.41,0.30,KO/TKO,Rich Mitchell,0,2026-03-21,17,41,16,32,17,43,20,36,2,5,1,1,15,36,6,20,15,38,9,23,2,5,1,1,12,29,11,26,2,8,4,5,3,4,1,1,15,39,11,23,2,2,4,7,0,0,1,2,10,24,3,16,2,8,2,3,3,4,1,1,13,34,5,17,2,2,0,2,0,0,1,1,69.0,145.0,72.0,Switch,2002-07-29,5.25,0.77,1.50,0.60,22.50,0.40,1.00,0.0,71.0,145.0,70.0,Switch,1997-01-30,6.67,0.55,7.47,0.61,2.00,0.33,0.81,0.2
6,Mason Jones,Axel Sola,0,0,0.46,0.48,NaN,0.42,0,0,0,0,5,139,0,0,0.39,0.46,NaN,0.5,0,0,0,0,0,105,0.46,0.48,0.39,0.46,Decision - Unanimous,Marc Goddard,1,2026-03-21,110,236,65,135,123,251,68,141,0,0,3,7,18,46,15,32,27,55,18,38,0,0,2,4,76,193,49,116,29,37,16,19,5,6,0,0,83,193,61,125,26,42,4,10,1,1,0,0,12,39,13,28,4,5,2,4,2,2,0,0,16,40,14,28,2,6,1,4,0,0,0,0,70.0,155.0,74.0,Orthodox,1995-04-26,5.71,0.41,4.47,0.50,4.17,0.55,0.81,0.2,74.0,155.0,74.0,Southpaw,1997-09-17,3.74,0.42,2.74,0.75,1.25,0.25,0.00,0.0
7,Nathaniel Wood,Losene Keita,0,0,0.37,0.43,0.00,NaN,0,0,0,0,0,0,0,0,0.30,0.42,0.00,NaN,0,0,0,0,0,0,0.37,0.43,0.30,0.42,Decision - Split,Jason Herzog,1,2026-03-21,67,178,52,119,67,178,52,119,0,1,0,0,17,56,11,26,17,56,11,26,0,1,0,0,32,128,36,101,2,3,13,15,33,47,3,3,67,177,52,119,0,1,0,0,0,0,0,0,7,42,8,22,2,3,3,4,8,11,0,0,17,55,11,26,0,1,0,0,0,0,0,0,66.0,145.0,69.0,Orthodox,1993-05-08,5.74,0.52,4.32,0.54,1.46,0.50,0.73,0.5,68.0,145.0,72.0,Orthodox,1997-12-30,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
8,Mario Pinto,Felipe Franco,0,0,0.58,0.35,0.14,0.00,0,0,0,0,375,0,0,0,0.57,0.36,0.00,NaN,0,0,0,0,28,0,0.58,0.35,0.57,0.36,Decision - Unanimous,Lukasz Bosacki,1,2026-03-21,34,58,21,60,137,166,60,100,2,14,0,1,16,28,9,25,37,49,16,32,0,2,0,0,25,48,13,51,6,7,7,8,3,3,1,1,20,42,13,51,13,15,8,9,1,1,0,0,12,23,6,21,2,3,2,3,2,2,1,1,12,23,8,24,4,5,1,1,0,0,0,0,77.0,265.0,79.0,Orthodox,1998-03-14,3.39,0.78,2.42,0.53,2.72,0.60,1.00,1.8,73.0,205.0,76.0,Orthodox,2001-01-22,2.23,0.71,2.84,0.35,6.08,0.40,1.00,0.0
9,Mantas Kondratavicius,Antonio Trocoli,1,0,0.70,0.43,0.50,0.08,1,0,0,0,366,303,0,0,0.66,0.42,NaN,0.0,0,0,0,0,112,93,0.70,0.43,0.66,0.42,Decision - Unanimous,Rich Mitchell,1,2026-03-21,75,107,17,39,135,177,29,54,2,4,1,12,28,42,6,14,41,56,9,19,0,0,0,1,61,93,10,28,14,14,3,7,0,0,4,4,42,68,15,35,17,19,2,4,16,20,0,0,19,33,2,10,9,9,2,2,0,0,2,2,19,32,4,12,9,10,2,2,0,0,0,0,74.0,185.0,75.0,Orthodox,1999-07-17,4.55,0.33,3.64,0.60,13.64,1.00,0.00,0.0,77.0,185.0,80.0,Orthodox,1990-12-06,1.37,0.50,5.55,0.24,0.79,0.10,0.33,0.8
10,Louie Sutherland,Brando Pericic,0,0,0.50,0.73,0.33,NaN,0,0,0,0,40,19,0,0,0.50,0.73,0.33,NaN,0,0,0,0,40,19,0.50,0.73,0.50,0.73,KO/TKO,Marc Goddard,0,2026-03-21,9,18,19,26,9,18,34,46,1,3,0,0,9,18,19,26,9,18,34,46,1,3,0,0,5,14,13,20,2,2,6,6,2,2,0,0,7,15,5,9,2,3,9,10,0,0,5,7,5,14,13,20,2,2,6,6,2,2,0,0,7,15,5,9,2,3,9,10,0,0,5,7,75.0,264.0,76.0,Orthodox,1994-02-08,2.14,0.60,3.57,0.00,0.00,0.00,0.00,0.0,77.0,245.0,79.0,Orthodox,1994-08-03,15.13,0.59,1.57,0.66,0.00,0.00,1.00,0.0
11,Shem Rock,Abdul-Kareem Al-Selwady,0,0,0.36,0.55,0.16,0.00,0,0,0,0,55,19,0,0,0.36,0.51,0.00,0.0,0,0,0,0,30,2,0.36,0.55,0.36,0.51,Decision - Unanimous,Jason Herzog,0,2026-03-21,47,128,81,146,52,134,105,173,1,6,0,4,17,46,27,52,22,51,28,53,0,1,0,1,26,101,48,102,16,22,13,14,5,5,20,30,43,123,71,130,3,3,8,11,1,2,2,5,10,37,16,33,4,6,2,2,3,3,9,17,15,43,25,47,1,1,2,4,1,2,0,1,71.0,155.0,73.0,Southpaw,1993-11-05,2.93,0.42,3.40,0.56,1.00,0.11,0.80,0.0,68.0,155.0,69.0,Orthodox,1995-04-10,4.14,0.34,3.60,0.59,2.32,0.30,0.20,0.0
12,Shanelle Dyer,Ravena Oliveira,0,0,0.62,0.32,1.00,0.00,0,0,0,0,34,12,0,0,0.68,0.29,NaN,0.0,0,0,0,0,28,5,0.62,0.32,0.68,0.29,KO/TKO,Lukasz Bosacki,1,2026-03-21,49,78,26,80,50,79,32,86,1,1,0,1,32,47,20,67,33,48,26,73,0,0,0,1,22,42,16,65,13,17,9,10,14,19,1,5,35,57,24,78,8,11,2,2,6,10,0,0,13,24,11,54,8,8,8,9,11,15,1,4,28,43,18,65,4,4,2,2,0,0,0,0,66.0,115.0,65.0,Orthodox,2001-04-23,7.67,0.41,7.80,0.44,0.00,0.00,0.00,0.0,65.0,115.0,65.0,Orthodox,1997-02-20,1.40,0.29,2.80,0.50,1.08,0.66,0.50,0.0

In [8]:
fights_df.head(25)

,p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,method,referee,winner,event_date,p1_SIG_STR_LANDED,p1_SIG_STR_ATTEMPTED,p2_SIG_STR_LANDED,p2_SIG_STR_ATTEMPTED,p1_TOTAL_STR_LANDED,p1_TOTAL_STR_ATTEMPTED,p2_TOTAL_STR_LANDED,p2_TOTAL_STR_ATTEMPTED,p1_TD_LANDED,p1_TD_ATTEMPTED,p2_TD_LANDED,p2_TD_ATTEMPTED,p1_R1_SIG_STR_LANDED,p1_R1_SIG_STR_ATTEMPTED,p2_R1_SIG_STR_LANDED,p2_R1_SIG_STR_ATTEMPTED,p1_R1_TOTAL_STR_LANDED,p1_R1_TOTAL_STR_ATTEMPTED,p2_R1_TOTAL_STR_LANDED,p2_R1_TOTAL_STR_ATTEMPTED,p1_R1_TD_LANDED,p1_R1_TD_ATTEMPTED,p2_R1_TD_LANDED,p2_R1_TD_ATTEMPTED,p1_HEAD_LANDED,p1_HEAD_ATTEMPTED,p2_HEAD_LANDED,p2_HEAD_ATTEMPTED,p1_BODY_LANDED,p1_BODY_ATTEMPTED,p2_BODY_LANDED,p2_BODY_ATTEMPTED,p1_LEG_LANDED,p1_LEG_ATTEMPTED,p2_LEG_LANDED,p2_LEG_ATTEMPTED,p1_DISTANCE_LANDED,p1_DISTANCE_ATTEMPTED,p2_DISTANCE_LANDED,p2_DISTANCE_ATTEMPTED,p1_CLINCH_LANDED,p1_CLINCH_ATTEMPTED,p2_CLINCH_LANDED,p2_CLINCH_ATTEMPTED,p1_GROUND_LANDED,p1_GROUND_ATTEMPTED,p2_GROUND_LANDED,p2_GROUND_ATTEMPTED,p1_R1_HEAD_LANDED,p1_R1_HEAD_ATTEMPTED,p2_R1_HEAD_LANDED,p2_R1_HEAD_ATTEMPTED,p1_R1_BODY_LANDED,p1_R1_BODY_ATTEMPTED,p2_R1_BODY_LANDED,p2_R1_BODY_ATTEMPTED,p1_R1_LEG_LANDED,p1_R1_LEG_ATTEMPTED,p2_R1_LEG_LANDED,p2_R1_LEG_ATTEMPTED,p1_R1_DISTANCE_LANDED,p1_R1_DISTANCE_ATTEMPTED,p2_R1_DISTANCE_LANDED,p2_R1_DISTANCE_ATTEMPTED,p1_R1_CLINCH_LANDED,p1_R1_CLINCH_ATTEMPTED,p2_R1_CLINCH_LANDED,p2_R1_CLINCH_ATTEMPTED,p1_R1_GROUND_LANDED,p1_R1_GROUND_ATTEMPTED,p2_R1_GROUND_LANDED,p2_R1_GROUND_ATTEMPTED,p1_height,p1_weight,p1_reach,p1_stance,p1_dob,p1_SLpM,p1_Str. Acc.,p1_SApM,p1_Str. Def,p1_TD Avg.,p1_TD Acc.,p1_TD Def.,p1_Sub. Avg.,p2_height,p2_weight,p2_reach,p2_stance,p2_dob,p2_SLpM,p2_Str. Acc.,p2_SApM,p2_Str. Def,p2_TD Avg.,p2_TD Acc.,p2_TD Def.,p2_Sub. Avg.
0,Movsar Evloev,Lerone Murphy,0,0,0.45,0.37,0.90,NaN,0,0,0,0,234,0,0,0,0.35,0.28,NaN,NaN,0,0,0,0,0,0,0.45,0.37,0.35,0.28,Decision - Majority,Marc Goddard,1,2026-03-21,86,189,89,239,124,234,89,239,9,10,0,0,11,31,14,49,11,31,14,49,0,0,0,0,47,134,45,175,33,44,24,38,6,11,20,26,80,178,89,238,1,2,0,1,5,9,0,0,3,21,6,35,6,7,4,8,2,3,4,6,11,31,14,49,0,0,0,0,0,0,0,0,67.0,145.0,72.0,Orthodox,1994-02-11,3.99,0.48,2.66,0.60,4.67,0.48,0.61,0.2,69.0,145.0,73.0,Orthodox,1991-07-22,4.48,0.53,2.51,0.61,1.41,0.54,0.51,0.5
1,Luke Riley,Michael Aswell Jr.,0,0,0.56,0.33,NaN,1.00,0,0,0,0,0,169,0,0,0.58,0.33,NaN,NaN,0,0,0,0,0,65,0.56,0.33,0.58,0.33,Decision - Unanimous,Jason Herzog,1,2026-03-21,100,177,61,180,113,192,107,233,0,0,1,1,33,56,20,59,45,68,54,95,0,0,0,0,65,134,48,158,31,36,13,21,4,7,0,1,90,166,58,169,10,11,3,11,0,0,0,0,22,42,17,52,10,11,3,6,1,3,0,1,30,53,18,53,3,3,2,6,0,0,0,0,69.0,145.0,69.0,Orthodox,1999-06-30,2.55,0.60,1.27,0.46,0.00,0.00,0.42,0.0,68.0,145.0,69.0,Orthodox,2000-09-27,9.56,0.45,7.79,0.54,0.00,0.00,0.57,0.0
2,Michael Page,Sam Patterson,0,0,0.49,0.18,NaN,0.00,0,0,0,0,26,167,0,0,0.41,0.36,NaN,NaN,0,0,0,0,0,0,0.49,0.18,0.41,0.36,Decision - Unanimous,Rich Mitchell,1,2026-03-21,27,55,12,64,33,61,25,78,0,0,0,2,5,12,4,11,5,12,4,11,0,0,0,0,17,38,4,50,4,8,4,6,6,9,4,8,27,55,10,60,0,0,2,4,0,0,0,0,3,7,2,8,1,4,1,1,1,1,1,2,5,12,4,11,0,0,0,0,0,0,0,0,75.0,170.0,79.0,Switch,1987-04-07,2.39,0.60,1.68,0.57,0.23,0.16,0.66,0.0,75.0,170.0,78.0,Orthodox,1996-04-30,3.89,0.43,3.93,0.49,1.39,1.00,0.33,2.8
3,Iwo Baraniewski,Austen Lane,1,0,0.76,0.00,NaN,NaN,0,0,0,0,4,0,1,0,0.76,0.00,NaN,NaN,0,0,0,0,4,0,0.76,0.00,0.76,0.00,KO/TKO,Lukasz Bosacki,1,2026-03-21,10,13,0,4,10,13,0,4,0,0,0,0,10,13,0,4,10,13,0,4,0,0,0,0,9,12,0,3,0,0,0,0,1,1,0,1,2,5,0,4,0,0,0,0,8,8,0,0,9,12,0,3,0,0,0,0,1,1,0,1,2,5,0,4,0,0,0,0,8,8,0,0,72.0,205.0,73.0,Orthodox,1998-11-20,14.31,0.68,17.61,0.42,0.00,0.00,1.00,0.0,78.0,205.0,80.0,Orthodox,1987-11-09,2.74,0.50,2.23,0.40,1.52,0.28,0.33,0.0
4,Roman Dolidze,Christian Leroy Duncan,0,0,0.29,0.54,0.75,0.00,0,0,0,0,427,68,0,0,0.33,0.55,1.00,0.0,0,0,0,0,153,37,0.29,0.54,0.33,0.55,Decision - Unanimous,Jason Herzog,0,2026-03-21,10,34,54,99,40,94,78,125,3,4,0,2,2,6,16,29,3,7,23,36,2,2,0,1,8,31,18,52,0,0,6,12,2,3,30,35,9,33,51,92,1,1,1,4,0,0,2,3,2,6,5,17,0,0,2,3,0,0,9,9,2,6,13,24,0,0,1,2,0,0,2,3,74.0,185.0,76.0,Orthodox,1988-07-15,3.41,0.41,3.72,0.48,0.99,0.39,0.26,0.8,74.0,185.0,79.0,Switch,1995-07-24,4.60,0.58,2.97,0.51,0.40,0.20,0.69,0.0
5,Kurtis Campbell,Danny Silva,0,2,0.41,0.50,0.40,1.00,0,0,0,1,116,65,0,0,0.41,0.30,0.40,1.0,0,0,0,1,116,56,0.41,0.50,0.41,0.30,KO/TKO,Rich Mitchell,0,2026-03-21,17,41,16,32,17,43,20,36,2,5,1,1,15,36,6,20,15,38,9,23,2,5,1,1,12,29,11,26,2,8,4,5,3,4,1,1,15,39,11,23,2,2,4,7,0,0,1,2,10,24,3,16,2,8,2,3,3,4,1,1,13,34,5,17,2,2,0,2,0,0,1,1,69.0,145.0,72.0,Switch,2002-07-29,5.25,0.77,1.50,0.60,22.50,0.40,1.00,0.0,71.0,145.0,70.0,Switch,1997-01-30,6.67,0.55,7.47,0.61,2.00,0.33,0.81,0.2
6,Mason Jones,Axel Sola,0,0,0.46,0.48,NaN,0.42,0,0,0,0,5,139,0,0,0.39,0.46,NaN,0.5,0,0,0,0,0,105,0.46,0.48,0.39,0.46,Decision - Unanimous,Marc Goddard,1,2026-03-21,110,236,65,135,123,251,68,141,0,0,3,7,18,46,15,32,27,55,18,38,0,0,2,4,76,193,49,116,29,37,16,19,5,6,0,0,83,193,61,125,26,42,4,10,1,1,0,0,12,39,13,28,4,5,2,4,2,2,0,0,16,40,14,28,2,6,1,4,0,0,0,0,70.0,155.0,74.0,Orthodox,1995-04-26,5.71,0.41,4.47,0.50,4.17,0.55,0.81,0.2,74.0,155.0,74.0,Southpaw,1997-09-17,3.74,0.42,2.74,0.75,1.25,0.25,0.00,0.0
7,Nathaniel Wood,Losene Keita,0,0,0.37,0.43,0.00,NaN,0,0,0,0,0,0,0,0,0.30,0.42,0.00,NaN,0,0,0,0,0,0,0.37,0.43,0.30,0.42,Decision - Split,Jason Herzog,1,2026-03-21,67,178,52,119,67,178,52,119,0,1,0,0,17,56,11,26,17,56,11,26,0,1,0,0,32,128,36,101,2,3,13,15,33,47,3,3,67,177,52,119,0,1,0,0,0,0,0,0,7,42,8,22,2,3,3,4,8,11,0,0,17,55,11,26,0,1,0,0,0,0,0,0,66.0,145.0,69.0,Orthodox,1993-05-08,5.74,0.52,4.32,0.54,1.46,0.50,0.73,0.5,68.0,145.0,72.0,Orthodox,1997-12-30,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
8,Mario Pinto,Felipe Franco,0,0,0.58,0.35,0.14,0.00,0,0,0,0,375,0,0,0,0.57,0.36,0.00,NaN,0,0,0,0,28,0,0.58,0.35,0.57,0.36,Decision - Unanimous,Lukasz Bosacki,1,2026-03-21,34,58,21,60,137,166,60,100,2,14,0,1,16,28,9,25,37,49,16,32,0,2,0,0,25,48,13,51,6,7,7,8,3,3,1,1,20,42,13,51,13,15,8,9,1,1,0,0,12,23,6,21,2,3,2,3,2,2,1,1,12,23,8,24,4,5,1,1,0,0,0,0,77.0,265.0,79.0,Orthodox,1998-03-14,3.39,0.78,2.42,0.53,2.72,0.60,1.00,1.8,73.0,205.0,76.0,Orthodox,2001-01-22,2.23,0.71,2.84,0.35,6.08,0.40,1.00,0.0
9,Mantas Kondratavicius,Antonio Trocoli,1,0,0.70,0.43,0.50,0.08,1,0,0,0,366,303,0,0,0.66,0.42,NaN,0.0,0,0,0,0,112,93,0.70,0.43,0.66,0.42,Decision - Unanimous,Rich Mitchell,1,2026-03-21,75,107,17,39,135,177,29,54,2,4,1,12,28,42,6,14,41,56,9,19,0,0,0,1,61,93,10,28,14,14,3,7,0,0,4,4,42,68,15,35,17,19,2,4,16,20,0,0,19,33,2,10,9,9,2,2,0,0,2,2,19,32,4,12,9,10,2,2,0,0,0,0,74.0,185.0,75.0,Orthodox,1999-07-17,4.55,0.33,3.64,0.60,13.64,1.00,0.00,0.0,77.0,185.0,80.0,Orthodox,1990-12-06,1.37,0.50,5.55,0.24,0.79,0.10,0.33,0.8
10,Louie Sutherland,Brando Pericic,0,0,0.50,0.73,0.33,NaN,0,0,0,0,40,19,0,0,0.50,0.73,0.33,NaN,0,0,0,0,40,19,0.50,0.73,0.50,0.73,KO/TKO,Marc Goddard,0,2026-03-21,9,18,19,26,9,18,34,46,1,3,0,0,9,18,19,26,9,18,34,46,1,3,0,0,5,14,13,20,2,2,6,6,2,2,0,0,7,15,5,9,2,3,9,10,0,0,5,7,5,14,13,20,2,2,6,6,2,2,0,0,7,15,5,9,2,3,9,10,0,0,5,7,75.0,264.0,76.0,Orthodox,1994-02-08,2.14,0.60,3.57,0.00,0.00,0.00,0.00,0.0,77.0,245.0,79.0,Orthodox,1994-08-03,15.13,0.59,1.57,0.66,0.00,0.00,1.00,0.0
11,Shem Rock,Abdul-Kareem Al-Selwady,0,0,0.36,0.55,0.16,0.00,0,0,0,0,55,19,0,0,0.36,0.51,0.00,0.0,0,0,0,0,30,2,0.36,0.55,0.36,0.51,Decision - Unanimous,Jason Herzog,0,2026-03-21,47,128,81,146,52,134,105,173,1,6,0,4,17,46,27,52,22,51,28,53,0,1,0,1,26,101,48,102,16,22,13,14,5,5,20,30,43,123,71,130,3,3,8,11,1,2,2,5,10,37,16,33,4,6,2,2,3,3,9,17,15,43,25,47,1,1,2,4,1,2,0,1,71.0,155.0,73.0,Southpaw,1993-11-05,2.93,0.42,3.40,0.56,1.00,0.11,0.80,0.0,68.0,155.0,69.0,Orthodox,1995-04-10,4.14,0.34,3.60,0.59,2.32,0.30,0.20,0.0
12,Shanelle Dyer,Ravena Oliveira,0,0,0.62,0.32,1.00,0.00,0,0,0,0,34,12,0,0,0.68,0.29,NaN,0.0,0,0,0,0,28,5,0.62,0.32,0.68,0.29,KO/TKO,Lukasz Bosacki,1,2026-03-21,49,78,26,80,50,79,32,86,1,1,0,1,32,47,20,67,33,48,26,73,0,0,0,1,22,42,16,65,13,17,9,10,14,19,1,5,35,57,24,78,8,11,2,2,6,10,0,0,13,24,11,54,8,8,8,9,11,15,1,4,28,43,18,65,4,4,2,2,0,0,0,0,66.0,115.0,65.0,Orthodox,2001-04-23,7.67,0.41,7.80,0.44,0.00,0.00,0.00,0.0,65.0,115.0,65.0,Orthodox,1997-02-20,1.40,0.29,2.80,0.50,1.08,0.66,0.50,0.0

In [9]:
f_df = pd.read_csv('ufc_cleaned.csv')

f_df = pd.concat([fights_df, f_df], ignore_index=True)

f_df.to_csv('ufc_cleaned.csv', index=False)