In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
fighters_df = pd.read_csv('ufc_fighters_cleaned.csv')

url = "http://ufcstats.com/statistics/events/completed?page=all"
headers = {'User-Agent': 'Mozilla/5.0'}

response = requests.get(url, headers=headers)
response.raise_for_status()
soup = BeautifulSoup(response.content, 'html.parser')

first_tag = soup.select_one('a.b-link.b-link_style_black[href*="event-details"]')
first_event_link = first_tag['href'] if first_tag else None

print(first_event_link)

http://ufcstats.com/event-details/00e11b5c8b7bfeeb

In [2]:
fight_links = []

if first_event_link:
    # fetch the single event page
    resp = requests.get(first_event_link, headers=headers)
    resp.raise_for_status()
    ev_soup = BeautifulSoup(resp.content, 'html.parser')

    # extract the event date
    date_el = ev_soup.find('li', class_='b-list__box-list-item')
    event_date = date_el.text.split(':')[-1].strip() if date_el else 'N/A'

    # find every fight row and pull out the onclick URL
    for row in ev_soup.select('tr.b-fight-details__table-row'):
        onclick = row.get('onclick','')
        if 'doNav' in onclick:
            fight_url = onclick.split("'")[1]
            fight_links.append({
                'url': fight_url,
                'event_date': event_date
            })

print(fight_links)

[{'url': 'http://ufcstats.com/fight-details/fa4b3f5ce8055921', 'event_date': 'January 24, 2026'}, {'url': 'http://ufcstats.com/fight-details/007e8e0d4a39d82c', 'event_date': 'January 24, 2026'}, {'url': 'http://ufcstats.com/fight-details/d93ee3860196c4ae', 'event_date': 'January 24, 2026'}, {'url': 'http://ufcstats.com/fight-details/d63c9aa4f4873001', 'event_date': 'January 24, 2026'}, {'url': 'http://ufcstats.com/fight-details/836a188a90e479a5', 'event_date': 'January 24, 2026'}, {'url': 'http://ufcstats.com/fight-details/6c9f4799990c3c33', 'event_date': 'January 24, 2026'}, {'url': 'http://ufcstats.com/fight-details/33be2456161c14c3', 'event_date': 'January 24, 2026'}, {'url': 'http://ufcstats.com/fight-details/780cab0cd07589e4', 'event_date': 'January 24, 2026'}, {'url': 'http://ufcstats.com/fight-details/b5aafe149bec4306', 'event_date': 'January 24, 2026'}, {'url': 'http://ufcstats.com/fight-details/abfb3ed6dcb0e1f0', 'event_date': 'January 24, 2026'}, {'url': 'http://ufcstats.com/fight-details/210fc45074fba464', 'event_date': 'January 24, 2026'}]

In [3]:
def scrape_ufc_fight_details(url): # scrapes the stats from the url we input
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Extract method of victory
    method_tag = soup.find('i', class_='b-fight-details__text-item_first')
    method = method_tag.find('i', style="font-style: normal").text.strip() if method_tag else ''
    
    # Extract referee
    referee = ""
    referee_span = soup.select_one('i.b-fight-details__label:-soup-contains("Referee:") + span')
    if referee_span:
        referee = referee_span.text.strip()

    # Find fighter status (W/L) for the first fighter
    fighter_status_tag = soup.find('i', class_='b-fight-details__person-status')
    first_fighter_won = None
    if fighter_status_tag:
        status = fighter_status_tag.text.strip()
        first_fighter_won = 1 if status == "W" else 0
    

    # get the data from round 1 and the totals rows
    all_rows = []
    rows = soup.find_all('tr', class_='b-fight-details__table-row')

    for row in rows:
        columns = row.find_all('p', class_='b-fight-details__table-text')
        data = [col.get_text(strip=True) for col in columns]
        all_rows.append(data)
    
    totals = 1
    r1_totals = 3
    sigTotals = int(len(all_rows) / 2 + 1)
    r1_sigTotals = sigTotals + 2
    
    filtered_rows = []
    
    def is_valid_row(arr):
        needed_indexes = [totals, r1_totals, sigTotals, r1_sigTotals]
        for idx in needed_indexes:
            if idx < len(all_rows):  # Make sure index is valid
                arr.append(all_rows[idx])
    
    is_valid_row(filtered_rows)
    
    # Append method of victory and referee as a new array at the end
    filtered_rows.append([method, referee])
    filtered_rows.append(first_fighter_won)

    return filtered_rows

# Test with the example URL
url = 'http://ufcstats.com/fight-details/d05cb4c4135ce402'
data = scrape_ufc_fight_details(url)
print(data)

[['Michael Chandler', 'Paddy Pimblett', '0', '0', '11 of 28', '80 of 143', '39%', '55%', '20 of 39', '121 of 197', '4 of 7', '1 of 2', '57%', '50%', '0', '0', '0', '1', '2:44', '4:41'], ['Michael Chandler', 'Paddy Pimblett', '0', '0', '5 of 11', '16 of 40', '45%', '40%', '7 of 14', '25 of 50', '2 of 3', '0 of 0', '66%', '---', '0', '0', '0', '0', '2:10', '0:00'], ['Michael Chandler', 'Paddy Pimblett', '11 of 28', '80 of 143', '39%', '55%', '6 of 18', '61 of 119', '3 of 7', '4 of 5', '2 of 3', '15 of 19', '10 of 24', '43 of 96', '0 of 0', '4 of 5', '1 of 4', '33 of 42'], ['Michael Chandler', 'Paddy Pimblett', '5 of 11', '16 of 40', '45%', '40%', '4 of 10', '7 of 28', '1 of 1', '1 of 2', '0 of 0', '8 of 10', '4 of 7', '16 of 40', '0 of 0', '0 of 0', '1 of 4', '0 of 0'], ['KO/TKO', 'Kerry Hatley'], 0]

In [4]:
def format_fight_data_single_row(data): #formats the data extracted from a match into a dictionary
    if not data or len(data) < 4:
        return "Not enough data to format."
    
    # Extract fighter names for reference
    fighter1 = data[0][0]
    fighter2 = data[0][1]
    
    # Create a single row dictionary with p1_ and p2_ prefixes
    formatted_row = {
        "p1_fighter": fighter1,
        "p2_fighter": fighter2,
        
        # Totals (Row 1)
        "p1_KD": data[0][2],
        "p2_KD": data[0][3],
        "p1_SIG_STR": data[0][4],
        "p2_SIG_STR": data[0][5],
        "p1_SIG_STR_PCT": data[0][6],
        "p2_SIG_STR_PCT": data[0][7],
        "p1_TOTAL_STR": data[0][8],
        "p2_TOTAL_STR": data[0][9],
        "p1_TD": data[0][10],
        "p2_TD": data[0][11],
        "p1_TD_PCT": data[0][12],
        "p2_TD_PCT": data[0][13],
        "p1_SUB_ATT": data[0][14],
        "p2_SUB_ATT": data[0][15],
        "p1_REV": data[0][16],
        "p2_REV": data[0][17],
        "p1_CTRL": data[0][18],
        "p2_CTRL": data[0][19],
        
        # Round 1 Totals (Row 2)
        "p1_R1_KD": data[1][2],
        "p2_R1_KD": data[1][3],
        "p1_R1_SIG_STR": data[1][4],
        "p2_R1_SIG_STR": data[1][5],
        "p1_R1_SIG_STR_PCT": data[1][6],
        "p2_R1_SIG_STR_PCT": data[1][7],
        "p1_R1_TOTAL_STR": data[1][8],
        "p2_R1_TOTAL_STR": data[1][9],
        "p1_R1_TD": data[1][10],
        "p2_R1_TD": data[1][11],
        "p1_R1_TD_PCT": data[1][12],
        "p2_R1_TD_PCT": data[1][13],
        "p1_R1_SUB_ATT": data[1][14],
        "p2_R1_SUB_ATT": data[1][15],
        "p1_R1_REV": data[1][16],
        "p2_R1_REV": data[1][17],
        "p1_R1_CTRL": data[1][18],
        "p2_R1_CTRL": data[1][19],
        
        # Significant Strike Details (Row 3)
        "p1_SIG_STR_LANDED_ATTEMPTED": data[2][2],
        "p2_SIG_STR_LANDED_ATTEMPTED": data[2][3],
        "p1_SIG_STR_PCT_DETAILED": data[2][4],
        "p2_SIG_STR_PCT_DETAILED": data[2][5],
        "p1_HEAD_LANDED_ATTEMPTED": data[2][6],
        "p2_HEAD_LANDED_ATTEMPTED": data[2][7],
        "p1_BODY_LANDED_ATTEMPTED": data[2][8],
        "p2_BODY_LANDED_ATTEMPTED": data[2][9],
        "p1_LEG_LANDED_ATTEMPTED": data[2][10],
        "p2_LEG_LANDED_ATTEMPTED": data[2][11],
        "p1_DISTANCE_LANDED_ATTEMPTED": data[2][12],
        "p2_DISTANCE_LANDED_ATTEMPTED": data[2][13],
        "p1_CLINCH_LANDED_ATTEMPTED": data[2][14],
        "p2_CLINCH_LANDED_ATTEMPTED": data[2][15],
        "p1_GROUND_LANDED_ATTEMPTED": data[2][16],
        "p2_GROUND_LANDED_ATTEMPTED": data[2][17],
        
        # Round 1 Significant Strike Details (Row 4)
        "p1_R1_SIG_STR_LANDED_ATTEMPTED": data[3][2],
        "p2_R1_SIG_STR_LANDED_ATTEMPTED": data[3][3],
        "p1_R1_SIG_STR_PCT_DETAILED": data[3][4],
        "p2_R1_SIG_STR_PCT_DETAILED": data[3][5],
        "p1_R1_HEAD_LANDED_ATTEMPTED": data[3][6],
        "p2_R1_HEAD_LANDED_ATTEMPTED": data[3][7],
        "p1_R1_BODY_LANDED_ATTEMPTED": data[3][8],
        "p2_R1_BODY_LANDED_ATTEMPTED": data[3][9],
        "p1_R1_LEG_LANDED_ATTEMPTED": data[3][10],
        "p2_R1_LEG_LANDED_ATTEMPTED": data[3][11],
        "p1_R1_DISTANCE_LANDED_ATTEMPTED": data[3][12],
        "p2_R1_DISTANCE_LANDED_ATTEMPTED": data[3][13],
        "p1_R1_CLINCH_LANDED_ATTEMPTED": data[3][14],
        "p2_R1_CLINCH_LANDED_ATTEMPTED": data[3][15],
        "p1_R1_GROUND_LANDED_ATTEMPTED": data[3][16],
        "p2_R1_GROUND_LANDED_ATTEMPTED": data[3][17],

        "method": data[4][0],
        "referee": data[4][1],
        "winner": data[5]
    }
    
    # Print column headers once (useful for CSV export)
    print(",".join(formatted_row.keys()))
    
    # Print the values as a single row
    print(",".join(str(val) for val in formatted_row.values()))
    
    return formatted_row

# Call the function with your scraped data
formatted_row = format_fight_data_single_row(data)
print(formatted_row)

p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Michael Chandler,Paddy Pimblett,0,0,11 of 28,80 of 143,39%,55%,20 of 39,121 of 197,4 of 7,1 of 2,57%,50%,0,0,0,1,2:44,4:41,0,0,5 of 11,16 of 40,45%,40%,7 of 14,25 of 50,2 of 3,0 of 0,66%,---,0,0,0,0,2:10,0:00,11 of 28,80 of 143,39%,55%,6 of 18,61 of 119,3 of 7,4 of 5,2 of 3,15 of 19,10 of 24,43 of 96,0 of 0,4 of 5,1 of 4,33 of 42,5 of 11,16 of 40,45%,40%,4 of 10,7 of 28,1 of 1,1 of 2,0 of 0,8 of 10,4 of 7,16 of 40,0 of 0,0 of 0,1 of 4,0 of 0,KO/TKO,Kerry Hatley,0
{'p1_fighter': 'Michael Chandler', 'p2_fighter': 'Paddy Pimblett', 'p1_KD': '0', 'p2_KD': '0', 'p1_SIG_STR': '11 of 28', 'p2_SIG_STR': '80 of 143', 'p1_SIG_STR_PCT': '39%', 'p2_SIG_STR_PCT': '55%', 'p1_TOTAL_STR': '20 of 39', 'p2_TOTAL_STR': '121 of 197', 'p1_TD': '4 of 7', 'p2_TD': '1 of 2', 'p1_TD_PCT': '57%', 'p2_TD_PCT': '50%', 'p1_SUB_ATT': '0', 'p2_SUB_ATT': '0', 'p1_REV': '0', 'p2_REV': '1', 'p1_CTRL': '2:44', 'p2_CTRL': '4:41', 'p1_R1_KD': '0', 'p2_R1_KD': '0', 'p1_R1_SIG_STR': '5 of 11', 'p2_R1_SIG_STR': '16 of 40', 'p1_R1_SIG_STR_PCT': '45%', 'p2_R1_SIG_STR_PCT': '40%', 'p1_R1_TOTAL_STR': '7 of 14', 'p2_R1_TOTAL_STR': '25 of 50', 'p1_R1_TD': '2 of 3', 'p2_R1_TD': '0 of 0', 'p1_R1_TD_PCT': '66%', 'p2_R1_TD_PCT': '---', 'p1_R1_SUB_ATT': '0', 'p2_R1_SUB_ATT': '0', 'p1_R1_REV': '0', 'p2_R1_REV': '0', 'p1_R1_CTRL': '2:10', 'p2_R1_CTRL': '0:00', 'p1_SIG_STR_LANDED_ATTEMPTED': '11 of 28', 'p2_SIG_STR_LANDED_ATTEMPTED': '80 of 143', 'p1_SIG_STR_PCT_DETAILED': '39%', 'p2_SIG_STR_PCT_DETAILED': '55%', 'p1_HEAD_LANDED_ATTEMPTED': '6 of 18', 'p2_HEAD_LANDED_ATTEMPTED': '61 of 119', 'p1_BODY_LANDED_ATTEMPTED': '3 of 7', 'p2_BODY_LANDED_ATTEMPTED': '4 of 5', 'p1_LEG_LANDED_ATTEMPTED': '2 of 3', 'p2_LEG_LANDED_ATTEMPTED': '15 of 19', 'p1_DISTANCE_LANDED_ATTEMPTED': '10 of 24', 'p2_DISTANCE_LANDED_ATTEMPTED': '43 of 96', 'p1_CLINCH_LANDED_ATTEMPTED': '0 of 0', 'p2_CLINCH_LANDED_ATTEMPTED': '4 of 5', 'p1_GROUND_LANDED_ATTEMPTED': '1 of 4', 'p2_GROUND_LANDED_ATTEMPTED': '33 of 42', 'p1_R1_SIG_STR_LANDED_ATTEMPTED': '5 of 11', 'p2_R1_SIG_STR_LANDED_ATTEMPTED': '16 of 40', 'p1_R1_SIG_STR_PCT_DETAILED': '45%', 'p2_R1_SIG_STR_PCT_DETAILED': '40%', 'p1_R1_HEAD_LANDED_ATTEMPTED': '4 of 10', 'p2_R1_HEAD_LANDED_ATTEMPTED': '7 of 28', 'p1_R1_BODY_LANDED_ATTEMPTED': '1 of 1', 'p2_R1_BODY_LANDED_ATTEMPTED': '1 of 2', 'p1_R1_LEG_LANDED_ATTEMPTED': '0 of 0', 'p2_R1_LEG_LANDED_ATTEMPTED': '8 of 10', 'p1_R1_DISTANCE_LANDED_ATTEMPTED': '4 of 7', 'p2_R1_DISTANCE_LANDED_ATTEMPTED': '16 of 40', 'p1_R1_CLINCH_LANDED_ATTEMPTED': '0 of 0', 'p2_R1_CLINCH_LANDED_ATTEMPTED': '0 of 0', 'p1_R1_GROUND_LANDED_ATTEMPTED': '1 of 4', 'p2_R1_GROUND_LANDED_ATTEMPTED': '0 of 0', 'method': 'KO/TKO', 'referee': 'Kerry Hatley', 'winner': 0}

In [5]:
def process_multiple_fights_with_date(url_date_list): # gets the data from every match and creates a dataframe from it 
    all_fights_data = []
    
    for item in url_date_list:
        url = item['url']
        event_date = item['event_date']
        try:
            fight_data = scrape_ufc_fight_details(url)
            formatted_row = format_fight_data_single_row(fight_data)  
            if isinstance(formatted_row, dict):
                formatted_row['event_date'] = event_date  # Add date to row
                all_fights_data.append(formatted_row)
            else:
                print(f"Error processing {url}: {formatted_row}")
        except Exception as e:
            print(f"Error processing {url}: {str(e)}")
    
    return pd.DataFrame(all_fights_data) if all_fights_data else "No data processed"

fights_df = process_multiple_fights_with_date(fight_links)
fights_df.head()

p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Justin Gaethje,Paddy Pimblett,2,0,144 of 254,156 of 311,56%,50%,200 of 313,170 of 326,3 of 3,0 of 5,100%,0%,0,0,0,0,5:55,0:48,1,0,27 of 45,37 of 65,60%,56%,40 of 58,38 of 66,0 of 0,0 of 1,---,0%,0,0,0,0,1:01,0:00,144 of 254,156 of 311,56%,50%,120 of 222,83 of 221,15 of 21,48 of 63,9 of 11,25 of 27,102 of 198,140 of 284,20 of 27,16 of 27,22 of 29,0 of 0,27 of 45,37 of 65,60%,56%,23 of 40,17 of 43,3 of 3,12 of 14,1 of 2,8 of 8,22 of 37,30 of 58,1 of 1,7 of 7,4 of 7,0 of 0,Decision - Unanimous,Marc Goddard,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Sean O'Malley,Song Yadong,0,0,48 of 92,36 of 94,52%,38%,67 of 111,69 of 130,0 of 0,3 of 7,---,42%,0,0,0,0,0:00,2:06,0,0,16 of 26,10 of 23,61%,43%,22 of 32,23 of 37,0 of 0,1 of 1,---,100%,0,0,0,0,0:00,0:38,48 of 92,36 of 94,52%,38%,23 of 53,15 of 55,16 of 28,2 of 6,9 of 11,19 of 33,48 of 92,36 of 94,0 of 0,0 of 0,0 of 0,0 of 0,16 of 26,10 of 23,61%,43%,6 of 13,0 of 7,6 of 8,0 of 1,4 of 5,10 of 15,16 of 26,10 of 23,0 of 0,0 of 0,0 of 0,0 of 0,Decision - Unanimous,Herb Dean,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Waldo Cortes Acosta,Derrick Lewis,1,0,44 of 62,8 of 43,70%,18%,46 of 64,8 of 43,1 of 1,0 of 0,100%,---,0,0,0,0,0:28,0:00,0,0,12 of 16,4 of 22,75%,18%,14 of 18,4 of 22,1 of 1,0 of 0,100%,---,0,0,0,0,0:16,0:00,44 of 62,8 of 43,70%,18%,35 of 53,6 of 37,5 of 5,2 of 5,4 of 4,0 of 1,27 of 45,8 of 43,1 of 1,0 of 0,16 of 16,0 of 0,12 of 16,4 of 22,75%,18%,7 of 11,3 of 17,3 of 3,1 of 4,2 of 2,0 of 1,11 of 15,4 of 22,0 of 0,0 of 0,1 of 1,0 of 0,KO/TKO,Jason Herzog,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Natalia Silva,Rose Namajunas,0,0,51 of 133,26 of 94,38%,27%,63 of 147,46 of 119,1 of 2,1 of 5,50%,20%,0,0,0,0,1:24,2:09,0,0,15 of 44,13 of 39,34%,33%,15 of 44,13 of 39,0 of 0,0 of 1,---,0%,0,0,0,0,0:00,0:00,51 of 133,26 of 94,38%,27%,25 of 95,11 of 64,8 of 14,3 of 13,18 of 24,12 of 17,50 of 132,26 of 92,1 of 1,0 of 2,0 of 0,0 of 0,15 of 44,13 of 39,34%,33%,10 of 32,4 of 22,1 of 3,1 of 6,4 of 9,8 of 11,15 of 44,13 of 39,0 of 0,0 of 0,0 of 0,0 of 0,Decision - Unanimous,Jason Herzog,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Arnold Allen,Jean Silva,0,0,56 of 116,74 of 136,48%,54%,60 of 121,78 of 141,0 of 0,4 of 6,---,66%,0,0,0,0,0:54,0:32,0,0,22 of 45,16 of 31,48%,51%,22 of 45,16 of 31,0 of 0,0 of 0,---,---,0,0,0,0,0:00,0:00,56 of 116,74 of 136,48%,54%,37 of 86,43 of 103,11 of 22,22 of 23,8 of 8,9 of 10,53 of 113,68 of 127,3 of 3,6 of 9,0 of 0,0 of 0,22 of 45,16 of 31,48%,51%,12 of 33,9 of 23,4 of 6,7 of 8,6 of 6,0 of 0,22 of 45,16 of 31,0 of 0,0 of 0,0 of 0,0 of 0,Decision - Unanimous,Chris Tognoni,0
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Umar Nurmagomedov,Deiveson Figueiredo,0,0,34 of 72,8 of 27,47%,29%,103 of 167,28 of 58,2 of 6,0 of 0,33%,---,0,0,0,0,4:50,0:09,0,0,9 of 19,0 of 6,47%,0%,28 of 46,1 of 10,1 of 2,0 of 0,50%,---,0,0,0,0,1:34,0:00,34 of 72,8 of 27,47%,29%,19 of 50,4 of 18,11 of 17,4 of 8,4 of 5,0 of 1,28 of 58,7 of 26,2 of 3,1 of 1,4 of 11,0 of 0,9 of 19,0 of 6,47%,0%,3 of 11,0 of 3,4 of 6,0 of 2,2 of 2,0 of 1,7 of 12,0 of 6,1 of 1,0 of 0,1 of 6,0 of 0,Decision - Unanimous,Herb Dean,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Ateba Gautier,Andrey Pulyaev,2,0,34 of 112,59 of 123,30%,47%,34 of 112,59 of 123,0 of 0,0 of 0,---,---,0,0,0,0,0:00,0:00,1,0,8 of 42,19 of 37,19%,51%,8 of 42,19 of 37,0 of 0,0 of 0,---,---,0,0,0,0,0:00,0:00,34 of 112,59 of 123,30%,47%,24 of 98,34 of 83,9 of 13,19 of 32,1 of 1,6 of 8,30 of 103,57 of 121,4 of 9,2 of 2,0 of 0,0 of 0,8 of 42,19 of 37,19%,51%,8 of 39,12 of 26,0 of 3,7 of 10,0 of 0,0 of 1,7 of 40,19 of 37,1 of 2,0 of 0,0 of 0,0 of 0,Decision - Unanimous,Mark Smith,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Nikita Krylov,Modestas Bukauskas,1,0,72 of 137,40 of 108,52%,37%,94 of 164,43 of 111,1 of 4,0 of 0,25%,---,0,0,0,0,2:37,0:56,0,0,10 of 28,11 of 21,35%,52%,25 of 48,13 of 23,1 of 4,0 of 0,25%,---,0,0,0,0,1:58,0:00,72 of 137,40 of 108,52%,37%,25 of 76,35 of 101,22 of 34,2 of 4,25 of 27,3 of 3,64 of 128,40 of 108,5 of 6,0 of 0,3 of 3,0 of 0,10 of 28,11 of 21,35%,52%,3 of 17,11 of 21,1 of 5,0 of 0,6 of 6,0 of 0,10 of 27,11 of 21,0 of 1,0 of 0,0 of 0,0 of 0,KO/TKO,Marc Goddard,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Alex Perez,Charles Johnson,2,0,39 of 75,8 of 25,52%,32%,55 of 94,8 of 25,0 of 0,0 of 1,---,0%,0,0,0,0,0:14,0:00,2,0,39 of 75,8 of 25,52%,32%,55 of 94,8 of 25,0 of 0,0 of 1,---,0%,0,0,0,0,0:14,0:00,39 of 75,8 of 25,52%,32%,27 of 60,4 of 14,9 of 10,3 of 9,3 of 5,1 of 2,33 of 67,8 of 25,4 of 6,0 of 0,2 of 2,0 of 0,39 of 75,8 of 25,52%,32%,27 of 60,4 of 14,9 of 10,3 of 9,3 of 5,1 of 2,33 of 67,8 of 25,4 of 6,0 of 0,2 of 2,0 of 0,KO/TKO,Jason Herzog,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Josh Hokit,Denzel Freeman,0,0,37 of 57,0 of 7,64%,0%,71 of 97,0 of 8,1 of 2,0 of 1,50%,0%,0,0,0,0,3:47,0:00,0,0,37 of 57,0 of 7,64%,0%,71 of 97,0 of 8,1 of 2,0 of 1,50%,0%,0,0,0,0,3:47,0:00,37 of 57,0 of 7,64%,0%,31 of 48,0 of 7,6 of 9,0 of 0,0 of 0,0 of 0,17 of 31,0 of 7,9 of 11,0 of 0,11 of 15,0 of 0,37 of 57,0 of 7,64%,0%,31 of 48,0 of 7,6 of 9,0 of 0,0 of 0,0 of 0,17 of 31,0 of 7,9 of 11,0 of 0,11 of 15,0 of 0,KO/TKO,Mark Smith,1
p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner
Adam Fugitt,Ty Miller,0,1,36 of 73,59 of 121,49%,48%,39 of 76,65 of 129,0 of 2,0 of 0,0%,---,0,0,0,0,0:00,0:03,0,1,36 of 73,59 of 121,49%,48%,39 of 76,65 of 129,0 of 2,0 of 0,0%,---,0,0,0,0,0:00,0:03,36 of 73,59 of 121,49%,48%,10 of 42,55 of 115,21 of 26,4 of 6,5 of 5,0 of 0,30 of 67,55 of 115,6 of 6,3 of 4,0 of 0,1 of 2,36 of 73,59 of 121,49%,48%,10 of 42,55 of 115,21 of 26,4 of 6,5 of 5,0 of 0,30 of 67,55 of 115,6 of 6,3 of 4,0 of 0,1 of 2,KO/TKO,Chris Tognoni,0

,p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR,p2_SIG_STR,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TOTAL_STR,p2_TOTAL_STR,p1_TD,p2_TD,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR,p2_R1_SIG_STR,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TOTAL_STR,p2_R1_TOTAL_STR,p1_R1_TD,p2_R1_TD,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_LANDED_ATTEMPTED,p2_SIG_STR_LANDED_ATTEMPTED,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_HEAD_LANDED_ATTEMPTED,p2_HEAD_LANDED_ATTEMPTED,p1_BODY_LANDED_ATTEMPTED,p2_BODY_LANDED_ATTEMPTED,p1_LEG_LANDED_ATTEMPTED,p2_LEG_LANDED_ATTEMPTED,p1_DISTANCE_LANDED_ATTEMPTED,p2_DISTANCE_LANDED_ATTEMPTED,p1_CLINCH_LANDED_ATTEMPTED,p2_CLINCH_LANDED_ATTEMPTED,p1_GROUND_LANDED_ATTEMPTED,p2_GROUND_LANDED_ATTEMPTED,p1_R1_SIG_STR_LANDED_ATTEMPTED,p2_R1_SIG_STR_LANDED_ATTEMPTED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,p1_R1_HEAD_LANDED_ATTEMPTED,p2_R1_HEAD_LANDED_ATTEMPTED,p1_R1_BODY_LANDED_ATTEMPTED,p2_R1_BODY_LANDED_ATTEMPTED,p1_R1_LEG_LANDED_ATTEMPTED,p2_R1_LEG_LANDED_ATTEMPTED,p1_R1_DISTANCE_LANDED_ATTEMPTED,p2_R1_DISTANCE_LANDED_ATTEMPTED,p1_R1_CLINCH_LANDED_ATTEMPTED,p2_R1_CLINCH_LANDED_ATTEMPTED,p1_R1_GROUND_LANDED_ATTEMPTED,p2_R1_GROUND_LANDED_ATTEMPTED,method,referee,winner,event_date
0,Justin Gaethje,Paddy Pimblett,2,0,144 of 254,156 of 311,56%,50%,200 of 313,170 of 326,3 of 3,0 of 5,100%,0%,0,0,0,0,5:55,0:48,1,0,27 of 45,37 of 65,60%,56%,40 of 58,38 of 66,0 of 0,0 of 1,---,0%,0,0,0,0,1:01,0:00,144 of 254,156 of 311,56%,50%,120 of 222,83 of 221,15 of 21,48 of 63,9 of 11,25 of 27,102 of 198,140 of 284,20 of 27,16 of 27,22 of 29,0 of 0,27 of 45,37 of 65,60%,56%,23 of 40,17 of 43,3 of 3,12 of 14,1 of 2,8 of 8,22 of 37,30 of 58,1 of 1,7 of 7,4 of 7,0 of 0,Decision - Unanimous,Marc Goddard,1,"January 24, 2026"
1,Sean O'Malley,Song Yadong,0,0,48 of 92,36 of 94,52%,38%,67 of 111,69 of 130,0 of 0,3 of 7,---,42%,0,0,0,0,0:00,2:06,0,0,16 of 26,10 of 23,61%,43%,22 of 32,23 of 37,0 of 0,1 of 1,---,100%,0,0,0,0,0:00,0:38,48 of 92,36 of 94,52%,38%,23 of 53,15 of 55,16 of 28,2 of 6,9 of 11,19 of 33,48 of 92,36 of 94,0 of 0,0 of 0,0 of 0,0 of 0,16 of 26,10 of 23,61%,43%,6 of 13,0 of 7,6 of 8,0 of 1,4 of 5,10 of 15,16 of 26,10 of 23,0 of 0,0 of 0,0 of 0,0 of 0,Decision - Unanimous,Herb Dean,1,"January 24, 2026"
2,Waldo Cortes Acosta,Derrick Lewis,1,0,44 of 62,8 of 43,70%,18%,46 of 64,8 of 43,1 of 1,0 of 0,100%,---,0,0,0,0,0:28,0:00,0,0,12 of 16,4 of 22,75%,18%,14 of 18,4 of 22,1 of 1,0 of 0,100%,---,0,0,0,0,0:16,0:00,44 of 62,8 of 43,70%,18%,35 of 53,6 of 37,5 of 5,2 of 5,4 of 4,0 of 1,27 of 45,8 of 43,1 of 1,0 of 0,16 of 16,0 of 0,12 of 16,4 of 22,75%,18%,7 of 11,3 of 17,3 of 3,1 of 4,2 of 2,0 of 1,11 of 15,4 of 22,0 of 0,0 of 0,1 of 1,0 of 0,KO/TKO,Jason Herzog,1,"January 24, 2026"
3,Natalia Silva,Rose Namajunas,0,0,51 of 133,26 of 94,38%,27%,63 of 147,46 of 119,1 of 2,1 of 5,50%,20%,0,0,0,0,1:24,2:09,0,0,15 of 44,13 of 39,34%,33%,15 of 44,13 of 39,0 of 0,0 of 1,---,0%,0,0,0,0,0:00,0:00,51 of 133,26 of 94,38%,27%,25 of 95,11 of 64,8 of 14,3 of 13,18 of 24,12 of 17,50 of 132,26 of 92,1 of 1,0 of 2,0 of 0,0 of 0,15 of 44,13 of 39,34%,33%,10 of 32,4 of 22,1 of 3,1 of 6,4 of 9,8 of 11,15 of 44,13 of 39,0 of 0,0 of 0,0 of 0,0 of 0,Decision - Unanimous,Jason Herzog,1,"January 24, 2026"
4,Arnold Allen,Jean Silva,0,0,56 of 116,74 of 136,48%,54%,60 of 121,78 of 141,0 of 0,4 of 6,---,66%,0,0,0,0,0:54,0:32,0,0,22 of 45,16 of 31,48%,51%,22 of 45,16 of 31,0 of 0,0 of 0,---,---,0,0,0,0,0:00,0:00,56 of 116,74 of 136,48%,54%,37 of 86,43 of 103,11 of 22,22 of 23,8 of 8,9 of 10,53 of 113,68 of 127,3 of 3,6 of 9,0 of 0,0 of 0,22 of 45,16 of 31,48%,51%,12 of 33,9 of 23,4 of 6,7 of 8,6 of 6,0 of 0,22 of 45,16 of 31,0 of 0,0 of 0,0 of 0,0 of 0,Decision - Unanimous,Chris Tognoni,0,"January 24, 2026"

In [6]:
#clean fights_df

#replace '--' values and turn percents to decimals
percent_cols = ['p1_SIG_STR_PCT', 'p2_SIG_STR_PCT', 'p1_TD_PCT', 'p2_TD_PCT', 'p1_R1_SIG_STR_PCT', 'p2_R1_SIG_STR_PCT', 'p1_R1_TD_PCT', 'p2_R1_TD_PCT', 'p1_SIG_STR_PCT_DETAILED', 'p2_SIG_STR_PCT_DETAILED', 'p1_R1_SIG_STR_PCT_DETAILED', 'p2_R1_SIG_STR_PCT_DETAILED']
for col in percent_cols:
    fights_df[col] = (
        fights_df[col]
        .astype(str)
        .replace({'--': np.nan, '---': np.nan})  # Handle missing values first
        .str.replace('%', '', regex=False)  # Remove percentage symbols
        .str.strip()  # Clean whitespace
        .astype(float) / 100  # Convert to decimal
    )


def clean_date_string(s):
    if pd.isna(s):
        return s
    s = str(s).strip()  # remove leading/trailing spaces
    s = s.strip('"').strip("'")  # remove quotes if any
    return s

fights_df['event_date'] = fights_df['event_date'].apply(clean_date_string)
# First convert from "December 13, 2025" to datetime, then to "YYYY-MM-DD" string format
fights_df['event_date'] = pd.to_datetime(fights_df['event_date'], format='%B %d, %Y', errors='coerce')
# Convert datetime to string in YYYY-MM-DD format to match the existing dataset
fights_df['event_date'] = fights_df['event_date'].dt.strftime('%Y-%m-%d')


# columns to split
cols_to_split = ['p1_SIG_STR', 'p2_SIG_STR', 'p1_TOTAL_STR', 'p2_TOTAL_STR', 'p1_TD', 'p2_TD', 'p1_R1_SIG_STR', 'p2_R1_SIG_STR', 'p1_R1_TOTAL_STR', 'p2_R1_TOTAL_STR', 'p1_R1_TD', 'p2_R1_TD', 'p1_SIG_STR_LANDED_ATTEMPTED', 'p2_SIG_STR_LANDED_ATTEMPTED', 'p1_HEAD_LANDED_ATTEMPTED', 'p2_HEAD_LANDED_ATTEMPTED', 'p1_BODY_LANDED_ATTEMPTED', 'p2_BODY_LANDED_ATTEMPTED', 'p1_LEG_LANDED_ATTEMPTED', 'p2_LEG_LANDED_ATTEMPTED', 'p1_DISTANCE_LANDED_ATTEMPTED', 'p2_DISTANCE_LANDED_ATTEMPTED', 'p1_CLINCH_LANDED_ATTEMPTED', 'p2_CLINCH_LANDED_ATTEMPTED', 'p1_GROUND_LANDED_ATTEMPTED', 'p2_GROUND_LANDED_ATTEMPTED', 'p1_R1_SIG_STR_LANDED_ATTEMPTED', 'p2_R1_SIG_STR_LANDED_ATTEMPTED', 'p1_R1_HEAD_LANDED_ATTEMPTED', 'p2_R1_HEAD_LANDED_ATTEMPTED', 'p1_R1_BODY_LANDED_ATTEMPTED', 'p2_R1_BODY_LANDED_ATTEMPTED', 'p1_R1_LEG_LANDED_ATTEMPTED', 'p2_R1_LEG_LANDED_ATTEMPTED', 'p1_R1_DISTANCE_LANDED_ATTEMPTED', 'p2_R1_DISTANCE_LANDED_ATTEMPTED', 'p1_R1_CLINCH_LANDED_ATTEMPTED', 'p2_R1_CLINCH_LANDED_ATTEMPTED', 'p1_R1_GROUND_LANDED_ATTEMPTED', 'p2_R1_GROUND_LANDED_ATTEMPTED']

#Loop over them, split into “_LANDED” and “_ATTEMPTED”, convert to ints
for col in cols_to_split:
    # decide new column names
    if col.endswith('_LANDED_ATTEMPTED'):
        base = col.rsplit('_', 2)[0]       # turns 'p1_HEAD_LANDED_ATTEMPTED' → 'p1_HEAD'
        landed_col    = f"{base}_LANDED"
        attempted_col = f"{base}_ATTEMPTED"
    else:
        # for columns like 'p1_SIG_STR'
        landed_col    = f"{col}_LANDED"
        attempted_col = f"{col}_ATTEMPTED"

    # split “63 of 129” → ['63','129'], then to numeric
    fights_df[[landed_col, attempted_col]] = (
        fights_df[col]
          .str.split(' of ', expand=True)
          .astype(int)
    )

# Drop the originals
fights_df.drop(columns=cols_to_split, inplace=True)


# time collumns needing reformatting
time_cols = ['p1_CTRL', 'p2_CTRL', 'p1_R1_CTRL', 'p2_R1_CTRL' ]

#Convert each to total seconds
for col in time_cols:
    # Replace non-time strings with NaN
    fights_df[col] = fights_df[col].replace({'--': np.nan, '---': np.nan})
    
    # Convert to "00:MM:SS" format then to seconds
    fights_df[col] = (
        pd.to_timedelta('00:' + fights_df[col].fillna('00:00'), errors='coerce')
        .dt.total_seconds()
        .astype('Int64')  # Allows integer NaNs
    )

fights_df.head(10)

,p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,method,referee,winner,event_date,p1_SIG_STR_LANDED,p1_SIG_STR_ATTEMPTED,p2_SIG_STR_LANDED,p2_SIG_STR_ATTEMPTED,p1_TOTAL_STR_LANDED,p1_TOTAL_STR_ATTEMPTED,p2_TOTAL_STR_LANDED,p2_TOTAL_STR_ATTEMPTED,p1_TD_LANDED,p1_TD_ATTEMPTED,p2_TD_LANDED,p2_TD_ATTEMPTED,p1_R1_SIG_STR_LANDED,p1_R1_SIG_STR_ATTEMPTED,p2_R1_SIG_STR_LANDED,p2_R1_SIG_STR_ATTEMPTED,p1_R1_TOTAL_STR_LANDED,p1_R1_TOTAL_STR_ATTEMPTED,p2_R1_TOTAL_STR_LANDED,p2_R1_TOTAL_STR_ATTEMPTED,p1_R1_TD_LANDED,p1_R1_TD_ATTEMPTED,p2_R1_TD_LANDED,p2_R1_TD_ATTEMPTED,p1_HEAD_LANDED,p1_HEAD_ATTEMPTED,p2_HEAD_LANDED,p2_HEAD_ATTEMPTED,p1_BODY_LANDED,p1_BODY_ATTEMPTED,p2_BODY_LANDED,p2_BODY_ATTEMPTED,p1_LEG_LANDED,p1_LEG_ATTEMPTED,p2_LEG_LANDED,p2_LEG_ATTEMPTED,p1_DISTANCE_LANDED,p1_DISTANCE_ATTEMPTED,p2_DISTANCE_LANDED,p2_DISTANCE_ATTEMPTED,p1_CLINCH_LANDED,p1_CLINCH_ATTEMPTED,p2_CLINCH_LANDED,p2_CLINCH_ATTEMPTED,p1_GROUND_LANDED,p1_GROUND_ATTEMPTED,p2_GROUND_LANDED,p2_GROUND_ATTEMPTED,p1_R1_HEAD_LANDED,p1_R1_HEAD_ATTEMPTED,p2_R1_HEAD_LANDED,p2_R1_HEAD_ATTEMPTED,p1_R1_BODY_LANDED,p1_R1_BODY_ATTEMPTED,p2_R1_BODY_LANDED,p2_R1_BODY_ATTEMPTED,p1_R1_LEG_LANDED,p1_R1_LEG_ATTEMPTED,p2_R1_LEG_LANDED,p2_R1_LEG_ATTEMPTED,p1_R1_DISTANCE_LANDED,p1_R1_DISTANCE_ATTEMPTED,p2_R1_DISTANCE_LANDED,p2_R1_DISTANCE_ATTEMPTED,p1_R1_CLINCH_LANDED,p1_R1_CLINCH_ATTEMPTED,p2_R1_CLINCH_LANDED,p2_R1_CLINCH_ATTEMPTED,p1_R1_GROUND_LANDED,p1_R1_GROUND_ATTEMPTED,p2_R1_GROUND_LANDED,p2_R1_GROUND_ATTEMPTED
0,Justin Gaethje,Paddy Pimblett,2,0,0.56,0.50,1.00,0.00,0,0,0,0,355,48,1,0,0.60,0.56,NaN,0.0,0,0,0,0,61,0,0.56,0.50,0.60,0.56,Decision - Unanimous,Marc Goddard,1,2026-01-24,144,254,156,311,200,313,170,326,3,3,0,5,27,45,37,65,40,58,38,66,0,0,0,1,120,222,83,221,15,21,48,63,9,11,25,27,102,198,140,284,20,27,16,27,22,29,0,0,23,40,17,43,3,3,12,14,1,2,8,8,22,37,30,58,1,1,7,7,4,7,0,0
1,Sean O'Malley,Song Yadong,0,0,0.52,0.38,NaN,0.42,0,0,0,0,0,126,0,0,0.61,0.43,NaN,1.0,0,0,0,0,0,38,0.52,0.38,0.61,0.43,Decision - Unanimous,Herb Dean,1,2026-01-24,48,92,36,94,67,111,69,130,0,0,3,7,16,26,10,23,22,32,23,37,0,0,1,1,23,53,15,55,16,28,2,6,9,11,19,33,48,92,36,94,0,0,0,0,0,0,0,0,6,13,0,7,6,8,0,1,4,5,10,15,16,26,10,23,0,0,0,0,0,0,0,0
2,Waldo Cortes Acosta,Derrick Lewis,1,0,0.70,0.18,1.00,NaN,0,0,0,0,28,0,0,0,0.75,0.18,1.00,NaN,0,0,0,0,16,0,0.70,0.18,0.75,0.18,KO/TKO,Jason Herzog,1,2026-01-24,44,62,8,43,46,64,8,43,1,1,0,0,12,16,4,22,14,18,4,22,1,1,0,0,35,53,6,37,5,5,2,5,4,4,0,1,27,45,8,43,1,1,0,0,16,16,0,0,7,11,3,17,3,3,1,4,2,2,0,1,11,15,4,22,0,0,0,0,1,1,0,0
3,Natalia Silva,Rose Namajunas,0,0,0.38,0.27,0.50,0.20,0,0,0,0,84,129,0,0,0.34,0.33,NaN,0.0,0,0,0,0,0,0,0.38,0.27,0.34,0.33,Decision - Unanimous,Jason Herzog,1,2026-01-24,51,133,26,94,63,147,46,119,1,2,1,5,15,44,13,39,15,44,13,39,0,0,0,1,25,95,11,64,8,14,3,13,18,24,12,17,50,132,26,92,1,1,0,2,0,0,0,0,10,32,4,22,1,3,1,6,4,9,8,11,15,44,13,39,0,0,0,0,0,0,0,0
4,Arnold Allen,Jean Silva,0,0,0.48,0.54,NaN,0.66,0,0,0,0,54,32,0,0,0.48,0.51,NaN,NaN,0,0,0,0,0,0,0.48,0.54,0.48,0.51,Decision - Unanimous,Chris Tognoni,0,2026-01-24,56,116,74,136,60,121,78,141,0,0,4,6,22,45,16,31,22,45,16,31,0,0,0,0,37,86,43,103,11,22,22,23,8,8,9,10,53,113,68,127,3,3,6,9,0,0,0,0,12,33,9,23,4,6,7,8,6,6,0,0,22,45,16,31,0,0,0,0,0,0,0,0
5,Umar Nurmagomedov,Deiveson Figueiredo,0,0,0.47,0.29,0.33,NaN,0,0,0,0,290,9,0,0,0.47,0.00,0.50,NaN,0,0,0,0,94,0,0.47,0.29,0.47,0.00,Decision - Unanimous,Herb Dean,1,2026-01-24,34,72,8,27,103,167,28,58,2,6,0,0,9,19,0,6,28,46,1,10,1,2,0,0,19,50,4,18,11,17,4,8,4,5,0,1,28,58,7,26,2,3,1,1,4,11,0,0,3,11,0,3,4,6,0,2,2,2,0,1,7,12,0,6,1,1,0,0,1,6,0,0
6,Ateba Gautier,Andrey Pulyaev,2,0,0.30,0.47,NaN,NaN,0,0,0,0,0,0,1,0,0.19,0.51,NaN,NaN,0,0,0,0,0,0,0.30,0.47,0.19,0.51,Decision - Unanimous,Mark Smith,1,2026-01-24,34,112,59,123,34,112,59,123,0,0,0,0,8,42,19,37,8,42,19,37,0,0,0,0,24,98,34,83,9,13,19,32,1,1,6,8,30,103,57,121,4,9,2,2,0,0,0,0,8,39,12,26,0,3,7,10,0,0,0,1,7,40,19,37,1,2,0,0,0,0,0,0
7,Nikita Krylov,Modestas Bukauskas,1,0,0.52,0.37,0.25,NaN,0,0,0,0,157,56,0,0,0.35,0.52,0.25,NaN,0,0,0,0,118,0,0.52,0.37,0.35,0.52,KO/TKO,Marc Goddard,1,2026-01-24,72,137,40,108,94,164,43,111,1,4,0,0,10,28,11,21,25,48,13,23,1,4,0,0,25,76,35,101,22,34,2,4,25,27,3,3,64,128,40,108,5,6,0,0,3,3,0,0,3,17,11,21,1,5,0,0,6,6,0,0,10,27,11,21,0,1,0,0,0,0,0,0
8,Alex Perez,Charles Johnson,2,0,0.52,0.32,NaN,0.00,0,0,0,0,14,0,2,0,0.52,0.32,NaN,0.0,0,0,0,0,14,0,0.52,0.32,0.52,0.32,KO/TKO,Jason Herzog,1,2026-01-24,39,75,8,25,55,94,8,25,0,0,0,1,39,75,8,25,55,94,8,25,0,0,0,1,27,60,4,14,9,10,3,9,3,5,1,2,33,67,8,25,4,6,0,0,2,2,0,0,27,60,4,14,9,10,3,9,3,5,1,2,33,67,8,25,4,6,0,0,2,2,0,0
9,Josh Hokit,Denzel Freeman,0,0,0.64,0.00,0.50,0.00,0,0,0,0,227,0,0,0,0.64,0.00,0.50,0.0,0,0,0,0,227,0,0.64,0.00,0.64,0.00,KO/TKO,Mark Smith,1,2026-01-24,37,57,0,7,71,97,0,8,1,2,0,1,37,57,0,7,71,97,0,8,1,2,0,1,31,48,0,7,6,9,0,0,0,0,0,0,17,31,0,7,9,11,0,0,11,15,0,0,31,48,0,7,6,9,0,0,0,0,0,0,17,31,0,7,9,11,0,0,11,15,0,0

In [7]:
# merge the two datasets

# First, merge p1 fighter stats
fights_df = fights_df.merge(
    fighters_df,
    left_on='p1_fighter',
    right_on='name',  # This matches p1_fighter with the name column in fighters_df
    how='left'
)
fights_df.drop(columns=['name'], inplace=True)

# Only include the specific columns you want to rename with p1_ prefix
p1_cols = ['height', 'weight', 'reach', 'stance', 'dob', 'SLpM', 'Str. Acc.', 'SApM', 'Str. Def', 'TD Avg.', 'TD Acc.', 'TD Def.', 'Sub. Avg.']
fights_df.rename(columns={col: f'p1_{col}' for col in p1_cols}, inplace=True)

# Then merge p2 fighter stats
fights_df = fights_df.merge(
    fighters_df,
    left_on='p2_fighter',
    right_on='name',  # This matches p2_fighter with the name column in fighters_df
    how='left'
)
fights_df.drop(columns=['name'], inplace=True)

# Use the same columns for p2 as we did for p1
p2_cols = ['height', 'weight', 'reach', 'stance', 'dob', 'SLpM', 'Str. Acc.', 'SApM', 'Str. Def', 'TD Avg.', 'TD Acc.', 'TD Def.', 'Sub. Avg.']
fights_df.rename(columns={col: f'p2_{col}' for col in p2_cols}, inplace=True)


# Drop unwanted columns
columns_to_drop = ['record_x', 'wins_x', 'losses_x', 'draws_x', 'nc_x', 'record_y', 'wins_y', 'losses_y', 'draws_y', 'nc_y', 'url_x', 'url_y']

# Check if columns exist before trying to drop them
existing_columns = [col for col in columns_to_drop if col in fights_df.columns]
if existing_columns:
    fights_df.drop(columns=existing_columns, inplace=True)


#-------------------------
# cleaned_df = fights_df      # update the cleaned csv so that we cna retarin the features_df to update the model and calculating ema
#-------------------------


fights_df.head(15)

,p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,method,referee,winner,event_date,p1_SIG_STR_LANDED,p1_SIG_STR_ATTEMPTED,p2_SIG_STR_LANDED,p2_SIG_STR_ATTEMPTED,p1_TOTAL_STR_LANDED,p1_TOTAL_STR_ATTEMPTED,p2_TOTAL_STR_LANDED,p2_TOTAL_STR_ATTEMPTED,p1_TD_LANDED,p1_TD_ATTEMPTED,p2_TD_LANDED,p2_TD_ATTEMPTED,p1_R1_SIG_STR_LANDED,p1_R1_SIG_STR_ATTEMPTED,p2_R1_SIG_STR_LANDED,p2_R1_SIG_STR_ATTEMPTED,p1_R1_TOTAL_STR_LANDED,p1_R1_TOTAL_STR_ATTEMPTED,p2_R1_TOTAL_STR_LANDED,p2_R1_TOTAL_STR_ATTEMPTED,p1_R1_TD_LANDED,p1_R1_TD_ATTEMPTED,p2_R1_TD_LANDED,p2_R1_TD_ATTEMPTED,p1_HEAD_LANDED,p1_HEAD_ATTEMPTED,p2_HEAD_LANDED,p2_HEAD_ATTEMPTED,p1_BODY_LANDED,p1_BODY_ATTEMPTED,p2_BODY_LANDED,p2_BODY_ATTEMPTED,p1_LEG_LANDED,p1_LEG_ATTEMPTED,p2_LEG_LANDED,p2_LEG_ATTEMPTED,p1_DISTANCE_LANDED,p1_DISTANCE_ATTEMPTED,p2_DISTANCE_LANDED,p2_DISTANCE_ATTEMPTED,p1_CLINCH_LANDED,p1_CLINCH_ATTEMPTED,p2_CLINCH_LANDED,p2_CLINCH_ATTEMPTED,p1_GROUND_LANDED,p1_GROUND_ATTEMPTED,p2_GROUND_LANDED,p2_GROUND_ATTEMPTED,p1_R1_HEAD_LANDED,p1_R1_HEAD_ATTEMPTED,p2_R1_HEAD_LANDED,p2_R1_HEAD_ATTEMPTED,p1_R1_BODY_LANDED,p1_R1_BODY_ATTEMPTED,p2_R1_BODY_LANDED,p2_R1_BODY_ATTEMPTED,p1_R1_LEG_LANDED,p1_R1_LEG_ATTEMPTED,p2_R1_LEG_LANDED,p2_R1_LEG_ATTEMPTED,p1_R1_DISTANCE_LANDED,p1_R1_DISTANCE_ATTEMPTED,p2_R1_DISTANCE_LANDED,p2_R1_DISTANCE_ATTEMPTED,p1_R1_CLINCH_LANDED,p1_R1_CLINCH_ATTEMPTED,p2_R1_CLINCH_LANDED,p2_R1_CLINCH_ATTEMPTED,p1_R1_GROUND_LANDED,p1_R1_GROUND_ATTEMPTED,p2_R1_GROUND_LANDED,p2_R1_GROUND_ATTEMPTED,p1_height,p1_weight,p1_reach,p1_stance,p1_dob,p1_SLpM,p1_Str. Acc.,p1_SApM,p1_Str. Def,p1_TD Avg.,p1_TD Acc.,p1_TD Def.,p1_Sub. Avg.,p2_height,p2_weight,p2_reach,p2_stance,p2_dob,p2_SLpM,p2_Str. Acc.,p2_SApM,p2_Str. Def,p2_TD Avg.,p2_TD Acc.,p2_TD Def.,p2_Sub. Avg.
0,Justin Gaethje,Paddy Pimblett,2,0,0.56,0.50,1.00,0.00,0,0,0,0,355,48,1,0,0.60,0.56,NaN,0.0,0,0,0,0,61,0,0.56,0.50,0.60,0.56,Decision - Unanimous,Marc Goddard,1,2026-01-24,144,254,156,311,200,313,170,326,3,3,0,5,27,45,37,65,40,58,38,66,0,0,0,1,120,222,83,221,15,21,48,63,9,11,25,27,102,198,140,284,20,27,16,27,22,29,0,0,23,40,17,43,3,3,12,14,1,2,8,8,22,37,30,58,1,1,7,7,4,7,0,0,71.0,155.0,70.0,Orthodox,1988-11-14,6.59,0.58,7.18,0.51,0.10,0.14,0.68,0.0,70.0,155.0,73.0,Orthodox,1995-01-03,5.19,0.53,3.14,0.42,0.96,0.28,0.50,1.7
1,Sean O'Malley,Song Yadong,0,0,0.52,0.38,NaN,0.42,0,0,0,0,0,126,0,0,0.61,0.43,NaN,1.0,0,0,0,0,0,38,0.52,0.38,0.61,0.43,Decision - Unanimous,Herb Dean,1,2026-01-24,48,92,36,94,67,111,69,130,0,0,3,7,16,26,10,23,22,32,23,37,0,0,1,1,23,53,15,55,16,28,2,6,9,11,19,33,48,92,36,94,0,0,0,0,0,0,0,0,6,13,0,7,6,8,0,1,4,5,10,15,16,26,10,23,0,0,0,0,0,0,0,0,71.0,135.0,72.0,Switch,1994-10-24,6.30,0.61,3.48,0.60,0.27,0.42,0.61,0.3,68.0,135.0,67.0,Orthodox,1997-12-02,4.58,0.43,4.00,0.55,0.61,0.38,0.73,0.1
2,Waldo Cortes Acosta,Derrick Lewis,1,0,0.70,0.18,1.00,NaN,0,0,0,0,28,0,0,0,0.75,0.18,1.00,NaN,0,0,0,0,16,0,0.70,0.18,0.75,0.18,KO/TKO,Jason Herzog,1,2026-01-24,44,62,8,43,46,64,8,43,1,1,0,0,12,16,4,22,14,18,4,22,1,1,0,0,35,53,6,37,5,5,2,5,4,4,0,1,27,45,8,43,1,1,0,0,16,16,0,0,7,11,3,17,3,3,1,4,2,2,0,1,11,15,4,22,0,0,0,0,1,1,0,0,76.0,260.0,78.0,Orthodox,1991-10-03,5.53,0.48,3.52,0.55,0.36,0.50,0.72,0.1,75.0,260.0,79.0,Orthodox,1985-02-07,2.51,0.50,2.49,0.40,0.56,0.26,0.52,0.0
3,Natalia Silva,Rose Namajunas,0,0,0.38,0.27,0.50,0.20,0,0,0,0,84,129,0,0,0.34,0.33,NaN,0.0,0,0,0,0,0,0,0.38,0.27,0.34,0.33,Decision - Unanimous,Jason Herzog,1,2026-01-24,51,133,26,94,63,147,46,119,1,2,1,5,15,44,13,39,15,44,13,39,0,0,0,1,25,95,11,64,8,14,3,13,18,24,12,17,50,132,26,92,1,1,0,2,0,0,0,0,10,32,4,22,1,3,1,6,4,9,8,11,15,44,13,39,0,0,0,0,0,0,0,0,64.0,125.0,65.0,Southpaw,1997-02-03,5.04,0.46,2.46,0.65,0.34,0.25,0.92,0.0,65.0,125.0,65.0,Orthodox,1992-06-29,3.60,0.41,3.38,0.63,1.49,0.50,0.62,0.4
4,Arnold Allen,Jean Silva,0,0,0.48,0.54,NaN,0.66,0,0,0,0,54,32,0,0,0.48,0.51,NaN,NaN,0,0,0,0,0,0,0.48,0.54,0.48,0.51,Decision - Unanimous,Chris Tognoni,0,2026-01-24,56,116,74,136,60,121,78,141,0,0,4,6,22,45,16,31,22,45,16,31,0,0,0,0,37,86,43,103,11,22,22,23,8,8,9,10,53,113,68,127,3,3,6,9,0,0,0,0,12,33,9,23,4,6,7,8,6,6,0,0,22,45,16,31,0,0,0,0,0,0,0,0,68.0,145.0,70.0,Southpaw,1994-01-22,3.45,0.41,2.88,0.61,0.93,0.47,0.75,0.3,67.0,145.0,69.0,Orthodox,1996-12-27,4.79,0.51,4.69,0.54,0.50,0.50,0.78,0.8
5,Arnold Allen,Jean Silva,0,0,0.48,0.54,NaN,0.66,0,0,0,0,54,32,0,0,0.48,0.51,NaN,NaN,0,0,0,0,0,0,0.48,0.54,0.48,0.51,Decision - Unanimous,Chris Tognoni,0,2026-01-24,56,116,74,136,60,121,78,141,0,0,4,6,22,45,16,31,22,45,16,31,0,0,0,0,37,86,43,103,11,22,22,23,8,8,9,10,53,113,68,127,3,3,6,9,0,0,0,0,12,33,9,23,4,6,7,8,6,6,0,0,22,45,16,31,0,0,0,0,0,0,0,0,68.0,145.0,70.0,Southpaw,1994-01-22,3.45,0.41,2.88,0.61,0.93,0.47,0.75,0.3,66.0,160.0,NaN,Orthodox,1977-10-08,0.73,0.22,2.93,0.52,0.00,0.00,0.00,0.0
6,Umar Nurmagomedov,Deiveson Figueiredo,0,0,0.47,0.29,0.33,NaN,0,0,0,0,290,9,0,0,0.47,0.00,0.50,NaN,0,0,0,0,94,0,0.47,0.29,0.47,0.00,Decision - Unanimous,Herb Dean,1,2026-01-24,34,72,8,27,103,167,28,58,2,6,0,0,9,19,0,6,28,46,1,10,1,2,0,0,19,50,4,18,11,17,4,8,4,5,0,1,28,58,7,26,2,3,1,1,4,11,0,0,3,11,0,3,4,6,0,2,2,2,0,1,7,12,0,6,1,1,0,0,1,6,0,0,68.0,135.0,69.0,Orthodox,1996-01-03,4.08,0.57,2.04,0.60,4.30,0.47,0.79,0.3,65.0,135.0,68.0,Orthodox,1987-12-18,2.75,0.54,3.54,0.49,1.71,0.35,0.57,1.3
7,Ateba Gautier,Andrey Pulyaev,2,0,0.30,0.47,NaN,NaN,0,0,0,0,0,0,1,0,0.19,0.51,NaN,NaN,0,0,0,0,0,0,0.30,0.47,0.19,0.51,Decision - Unanimous,Mark Smith,1,2026-01-24,34,112,59,123,34,112,59,123,0,0,0,0,8,42,19,37,8,42,19,37,0,0,0,0,24,98,34,83,9,13,19,32,1,1,6,8,30,103,57,121,4,9,2,2,0,0,0,0,8,39,12,26,0,3,7,10,0,0,0,1,7,40,19,37,1,2,0,0,0,0,0,0,76.0,185.0,81.0,Switch,2002-04-10,6.57,0.60,1.95,0.53,0.98,1.00,0.92,0.0,76.0,185.0,78.0,Southpaw,1997-09-10,3.81,0.60,3.51,0.48,0.41,0.16,0.64,0.0
8,Nikita Krylov,Modestas Bukauskas,1,0,0.52,0.37,0.25,NaN,0,0,0,0,157,56,0,0,0.35,0.52,0.25,NaN,0,0,0,0,118,0,0.52,0.37,0.35,0.52,KO/TKO,Marc Goddard,1,2026-01-24,72,137,40,108,94,164,43,111,1,4,0,0,10,28,11,21,25,48,13,23,1,4,0,0,25,76,35,101,22,34,2,4,25,27,3,3,64,128,40,108,5,6,0,0,3,3,0,0,3,17,11,21,1,5,0,0,6,6,0,0,10,27,11,21,0,1,0,0,0,0,0,0,75.0,205.0,77.0,Orthodox,1992-03-07,4.31,0.54,2.58,0.44,2.17,0.38,0.53,1.4,75.0,205.0,76.0,Switch,1994-02-10,3.32,0.43,3.93,0.51,0.30,0.66,0.80,0.1
9,Alex Perez,Charles Johnson,2,0,0.52,0.32,NaN,0.00,0,0,0,0,14,0,2,0,0.52,0.32,NaN,0.0,0,0,0,0,14,0,0.52,0.32,0.52,0.32,KO/TKO,Jason Herzog,1,2026-01-24,39,75,8,25,55,94,8,25,0,0,0,1,39,75,8,25,55,94,8,25,0,0,0,1,27,60,4,14,9,10,3,9,3,5,1,2,33,67,8,25,4,6,0,0,2,2,0,0,27,60,4,14,9,10,3,9,3,5,1,2,33,67,8,25,4,6,0,0,2,2,0,0,66.0,125.0,65.0,Orthodox,1992-03-21,4.19,0.46,3.20,0.58,2.04,0.46,0.77,0.8,69.0,125.0,70.0,Switch,1991-01-10,4.73,0.49,3.78,0.56,0.56,0.20,0.66,0.4
10,Josh Hokit,Denzel Freeman,0,0,0.64,0.00,0.50,0.00,0,0,0,0,227,0,0,0,0.64,0.00,0.50,0.0,0,0,0,0,227,0,0.64,0.00,0.64,0.00,KO/TKO,Mark Smith,1,2026-01-24,37,57,0,7,71,97,0,8,1,2,0,1,37,57,0,7,71,97,0,8,1,2,0,1,31,48,0,7,6,9,0,0,0,0,0,0,17,31,0,7,9,11,0,0,11,15,0,0,31,48,0,7,6,9,0,0,0,0,0,0,17,31,0,7,9,11,0,0,11,15,0,0,73.0,236.0,73.0,Orthodox,1997-11-12,5.12,0.69,1.42,0.56,12.80,0.46,0.00,0.0,NaN,265.0,NaN,Southpaw,1991-11-10,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
11,Adam Fugitt,Ty Miller,0,1,0.49,0.48,0.00,NaN,0,0,0,0,0,3,0,1,0.49,0.48,0.00,NaN,0,0,0,0,0,3,0.49,0.48,0.49,0.48,KO/TKO,Chris Tognoni,0,2026-01-24,36,73,59,121,39,76,65,129,0,2,0,0,36,73,59,121,39,76,65,129,0,2,0,0,10,42,55,115,21,26,4,6,5,5,0,0,30,67,55,115,6,6,3,4,0,0,1,2,10,42,55,115,21,26,4,6,5,5,0,0,30,67,55,115,6,6,3,4,0,0,1,2,73.0,170.0,77.0,Southpaw,1989-01-12,4.59,0.46,4.54,0.51,1.83,0.25,0.50,0.0,74.0,170.0,77.0,Orthodox,2000-06-04,5.60,0.34,3.80,0.70,0.00,0.00,0.50,0.0

In [16]:
fights_df.head(15)

,p1_fighter,p2_fighter,p1_KD,p2_KD,p1_SIG_STR_PCT,p2_SIG_STR_PCT,p1_TD_PCT,p2_TD_PCT,p1_SUB_ATT,p2_SUB_ATT,p1_REV,p2_REV,p1_CTRL,p2_CTRL,p1_R1_KD,p2_R1_KD,p1_R1_SIG_STR_PCT,p2_R1_SIG_STR_PCT,p1_R1_TD_PCT,p2_R1_TD_PCT,p1_R1_SUB_ATT,p2_R1_SUB_ATT,p1_R1_REV,p2_R1_REV,p1_R1_CTRL,p2_R1_CTRL,p1_SIG_STR_PCT_DETAILED,p2_SIG_STR_PCT_DETAILED,p1_R1_SIG_STR_PCT_DETAILED,p2_R1_SIG_STR_PCT_DETAILED,method,referee,winner,event_date,p1_SIG_STR_LANDED,p1_SIG_STR_ATTEMPTED,p2_SIG_STR_LANDED,p2_SIG_STR_ATTEMPTED,p1_TOTAL_STR_LANDED,p1_TOTAL_STR_ATTEMPTED,p2_TOTAL_STR_LANDED,p2_TOTAL_STR_ATTEMPTED,p1_TD_LANDED,p1_TD_ATTEMPTED,p2_TD_LANDED,p2_TD_ATTEMPTED,p1_R1_SIG_STR_LANDED,p1_R1_SIG_STR_ATTEMPTED,p2_R1_SIG_STR_LANDED,p2_R1_SIG_STR_ATTEMPTED,p1_R1_TOTAL_STR_LANDED,p1_R1_TOTAL_STR_ATTEMPTED,p2_R1_TOTAL_STR_LANDED,p2_R1_TOTAL_STR_ATTEMPTED,p1_R1_TD_LANDED,p1_R1_TD_ATTEMPTED,p2_R1_TD_LANDED,p2_R1_TD_ATTEMPTED,p1_HEAD_LANDED,p1_HEAD_ATTEMPTED,p2_HEAD_LANDED,p2_HEAD_ATTEMPTED,p1_BODY_LANDED,p1_BODY_ATTEMPTED,p2_BODY_LANDED,p2_BODY_ATTEMPTED,p1_LEG_LANDED,p1_LEG_ATTEMPTED,p2_LEG_LANDED,p2_LEG_ATTEMPTED,p1_DISTANCE_LANDED,p1_DISTANCE_ATTEMPTED,p2_DISTANCE_LANDED,p2_DISTANCE_ATTEMPTED,p1_CLINCH_LANDED,p1_CLINCH_ATTEMPTED,p2_CLINCH_LANDED,p2_CLINCH_ATTEMPTED,p1_GROUND_LANDED,p1_GROUND_ATTEMPTED,p2_GROUND_LANDED,p2_GROUND_ATTEMPTED,p1_R1_HEAD_LANDED,p1_R1_HEAD_ATTEMPTED,p2_R1_HEAD_LANDED,p2_R1_HEAD_ATTEMPTED,p1_R1_BODY_LANDED,p1_R1_BODY_ATTEMPTED,p2_R1_BODY_LANDED,p2_R1_BODY_ATTEMPTED,p1_R1_LEG_LANDED,p1_R1_LEG_ATTEMPTED,p2_R1_LEG_LANDED,p2_R1_LEG_ATTEMPTED,p1_R1_DISTANCE_LANDED,p1_R1_DISTANCE_ATTEMPTED,p2_R1_DISTANCE_LANDED,p2_R1_DISTANCE_ATTEMPTED,p1_R1_CLINCH_LANDED,p1_R1_CLINCH_ATTEMPTED,p2_R1_CLINCH_LANDED,p2_R1_CLINCH_ATTEMPTED,p1_R1_GROUND_LANDED,p1_R1_GROUND_ATTEMPTED,p2_R1_GROUND_LANDED,p2_R1_GROUND_ATTEMPTED,p1_height,p1_weight,p1_reach,p1_stance,p1_dob,p1_SLpM,p1_Str. Acc.,p1_SApM,p1_Str. Def,p1_TD Avg.,p1_TD Acc.,p1_TD Def.,p1_Sub. Avg.,p2_height,p2_weight,p2_reach,p2_stance,p2_dob,p2_SLpM,p2_Str. Acc.,p2_SApM,p2_Str. Def,p2_TD Avg.,p2_TD Acc.,p2_TD Def.,p2_Sub. Avg.
0,Brandon Royval,Manel Kape,0,1,0.65,0.73,NaN,NaN,0,0,0,0,0,4,0,1,0.65,0.73,NaN,NaN,0,0,0,0,0,4,0.65,0.73,0.65,0.73,KO/TKO,Herb Dean,0,2025-12-13,17,26,17,23,17,26,18,24,0,0,0,0,17,26,17,23,17,26,18,24,0,0,0,0,5,10,6,10,6,8,5,6,6,8,6,7,17,26,15,21,0,0,0,0,0,0,2,2,5,10,6,10,6,8,5,6,6,8,6,7,17,26,15,21,0,0,0,0,0,0,2,2,69.0,125.0,68.0,Southpaw,1992-08-16,5.55,0.41,4.23,0.43,0.67,0.75,0.45,1.1,65.0,125.0,68.0,Southpaw,1993-11-14,5.04,0.55,4.05,0.57,0.42,0.30,0.81,0.3
1,Giga Chikadze,Kevin Vallejos,0,1,0.54,0.62,NaN,0.00,0,0,0,0,0,88,0,0,0.52,0.50,NaN,0.00,0,0,0,0,0,87,0.54,0.62,0.52,0.50,KO/TKO,Mark Smith,0,2025-12-13,12,22,20,32,19,29,23,35,0,0,0,1,9,17,9,18,16,24,12,21,0,0,0,1,2,10,14,24,10,10,2,3,0,2,4,5,12,22,15,26,0,0,1,2,0,0,4,4,1,8,6,13,8,8,1,2,0,1,2,3,9,17,8,16,0,0,1,2,0,0,0,0,72.0,145.0,74.0,Orthodox,1988-08-25,3.82,0.42,3.48,0.60,0.19,0.33,0.65,0.2,67.0,145.0,68.0,Switch,2001-12-08,6.28,0.45,5.23,0.57,0.84,0.33,0.83,0.0
2,Cesar Almeida,Cezary Oleksiejczuk,0,0,0.60,0.73,NaN,0.85,0,0,1,1,29,675,0,0,0.80,0.83,NaN,1.00,0,0,0,0,0,219,0.60,0.73,0.80,0.83,Decision - Unanimous,Kerry Hatley,0,2025-12-13,12,20,14,19,25,37,113,126,0,0,6,7,4,5,5,6,6,9,33,35,0,0,1,1,2,7,9,13,7,9,5,6,3,4,0,0,12,17,10,15,0,0,1,1,0,3,3,3,0,1,3,3,2,2,2,3,2,2,0,0,4,5,3,4,0,0,1,1,0,0,1,1,73.0,185.0,74.0,Orthodox,1988-03-28,4.16,0.58,2.32,0.48,0.00,0.00,0.60,0.3,75.0,185.0,75.0,Southpaw,2000-01-06,28.33,1.00,0.00,1.00,0.00,0.00,1.00,0.0
3,Melquizael Costa,Morgan Charriere,1,0,0.44,0.50,NaN,NaN,0,0,0,0,2,0,1,0,0.44,0.50,NaN,NaN,0,0,0,0,2,0,0.44,0.50,0.44,0.50,KO/TKO,Eric McMahon,1,2025-12-13,4,9,2,4,4,9,2,4,0,0,0,0,4,9,2,4,4,9,2,4,0,0,0,0,1,3,0,2,1,1,0,0,2,5,2,2,4,9,2,4,0,0,0,0,0,0,0,0,1,3,0,2,1,1,0,0,2,5,2,2,4,9,2,4,0,0,0,0,0,0,0,0,70.0,145.0,71.0,Southpaw,1996-09-14,4.44,0.49,3.09,0.54,1.96,0.38,0.58,1.2,68.0,145.0,69.0,Orthodox,1995-10-26,4.08,0.50,4.54,0.53,2.11,0.46,0.83,0.3
4,Kennedy Nzechukwu,Marcus Buchecha,0,0,0.50,0.61,NaN,0.23,0,0,0,0,217,380,0,0,0.50,0.22,NaN,0.22,0,0,0,0,38,142,0.50,0.61,0.50,0.22,Decision - Unanimous,Herb Dean,0,2025-12-13,24,48,27,44,58,87,47,66,0,0,3,13,9,18,2,9,23,32,3,10,0,0,2,9,21,43,23,38,3,5,4,6,0,0,0,0,13,32,2,12,2,2,2,4,9,14,23,28,7,16,0,5,2,2,2,4,0,0,0,0,8,16,1,8,1,1,1,1,0,1,0,0,77.0,236.0,83.0,Southpaw,1992-06-13,5.33,0.46,4.89,0.51,0.55,0.45,0.80,0.2,74.0,255.0,77.0,Orthodox,1990-01-08,1.60,0.40,2.73,0.52,1.00,0.09,0.00,0.0
5,King Green,Lance Gibson Jr.,0,0,0.46,0.41,0.50,0.66,0,0,0,0,44,70,0,0,0.43,0.34,0.0,NaN,0,0,0,0,0,0,0.46,0.41,0.43,0.34,Decision - Split,Mark Smith,1,2025-12-13,65,141,30,72,74,150,35,77,1,2,2,3,22,51,12,35,22,51,12,35,0,1,0,0,25,77,9,39,24,40,8,14,16,24,13,19,56,129,27,66,1,1,3,6,8,11,0,0,8,26,4,22,5,14,2,4,9,11,6,9,21,50,11,32,1,1,1,3,0,0,0,0,70.0,155.0,71.0,Orthodox,1986-09-09,6.40,0.52,3.72,0.62,1.22,0.39,0.74,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Neil Magny,Yaroslav Amosov,0,0,0.45,0.47,NaN,0.50,0,1,0,0,0,116,0,0,0.45,0.47,NaN,0.50,0,1,0,0,0,116,0.45,0.47,0.45,0.47,Submission,Herb Dean,0,2025-12-13,5,11,9,19,15,24,13,27,0,0,1,2,5,11,9,19,15,24,13,27,0,0,1,2,2,8,3,12,2,2,0,0,1,1,6,7,5,11,8,17,0,0,0,0,0,0,1,2,2,8,3,12,2,2,0,0,1,1,6,7,5,11,8,17,0,0,0,0,0,0,1,2,75.0,170.0,80.0,Orthodox,1987-08-03,3.41,0.46,2.44,0.51,2.18,0.39,0.55,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Joanderson Brito,Isaac Thomson,0,0,0.57,0.44,0.66,0.80,2,0,1,1,479,180,0,0,0.57,0.60,1.0,1.00,0,0,0,1,89,143,0.57,0.44,0.57,0.60,Decision - Unanimous,Eric McMahon,1,2025-12-13,33,57,21,47,66,93,127,164,8,12,4,5,4,7,6,10,16,19,26,34,3,3,2,2,16,36,14,33,7,10,6,10,10,11,1,4,19,36,14,37,7,10,6,8,7,11,1,2,1,4,6,7,2,2,0,2,1,1,0,1,1,1,0,3,1,2,5,5,2,4,1,2,68.0,145.0,72.0,Orthodox,1995-02-11,2.48,0.50,2.49,0.42,2.49,0.68,0.56,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Sean Sharaf,Steven Asplund,0,0,0.43,0.58,0.00,NaN,0,0,0,0,0,3,0,0,0.48,0.51,NaN,NaN,0,0,0,0,0,3,0.43,0.58,0.48,0.51,KO/TKO,Mark Smith,0,2025-12-13,66,153,170,292,66,154,172,294,0,1,0,0,43,89,71,137,43,90,72,138,0,0,0,0,50,134,154,276,15,18,6,6,1,1,10,10,66,149,166,285,0,4,4,7,0,0,0,0,32,76,61,127,10,12,3,3,1,1,7,7,43,89,70,136,0,0,1,1,0,0,0,0,75.0,252.0,77.0,Orthodox,1993-07-11,7.31,0.44,9.79,0.44,2.07,0.12,0.00,0.0,77.0,261.0,78.0,Orthodox,1998-07-16,41.25,0.64,7.50,0.71,0.00,0.00,0.00,0.0
9,Melissa Croden,Luana Santos,0,0,0.29,0.50,0.00,0.42,0,1,1,0,44,561,0,0,0.25,0.76,0.0,0.33,0,0,1,0,44,111,0.29,0.50,0.25,0.76,Decision - Unanimous,Kerry Hatley,0,2025-12-13,22,74,12,24,56,109,93,110,0,1,3,7,7,27,10,13,21,41,33,37,0,1,1,3,9,53,6,16,7,8,4,5,6,13,2,3,18,69,10,20,4,5,2,3,0,0,0,1,1,17,5,7,4,5,3,4,2,5,2,2,4,23,8,10,3,4,2,3,0,0,0,0,NaN,135.0,NaN,Orthodox,1991-04-12,6.81,0.56,2.89,0.54,2.06,0.66,0.75,0.0,66.0,135.0,67.0,Orthodox,2000-04-16,3.69,0.52,3.40,0.62,1.91,0.50,0.83,1.3
10,Allen Frye Jr.,Guilherme Pat,0,0,0.38,0.64,NaN,NaN,0,0,0,0,475,44,0,0,0.38,0.68,NaN,NaN,0,0,0,0,138,3,0.38,0.64,0.38,0.68,Decision - Unanimous,Eric McMahon,0,2025-12-13,33,86,64,100,73,132,76,114,0,0,0,0,19,49,24,35,32,63,25,37,0,0,0,0,17,65,53,88,12,12,8,9,4,9,3,3,19,69,54,90,14,17,10,10,0,0,0,0,10,37,19,29,7,7,3,4,2,5,2,2,12,40,23,34,7,9,1,1,0,0,0,0,NaN,265.0,NaN,NaN,1998-04-15,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,NaN,265.0,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
11,Jamey-Lyn Horth,Tereza Bleda,0,0,0.72,0.16,NaN,0.00,0,0,0,0,3,80,0,0,0.72,0.16,NaN,0.00,0,0,0,0,3,80,0.72,0.16,0.72,0.16,KO/TKO,Kerry Hatley,1,2025-12-13,16,22,2,12,18,24,2,12,0,0,0,4,16,22,2,12,18,24,2,12,0,0,0,4,12,17,0,8,3,4,2,2,1,1,0,2,9,15,1,11,7,7,1,1,0,0,0,0,12,17,0,8,3,4,2,2,1,1,0,2,9,15,1,11,7,7,1,1,0,0,0,0,67.0,125.0,66.0,Orthodox,1990-03-30,3.52,0.54,2.55,0.62,1.20,0.42,0.76,0.2,69.0,125.0,71.0,Orthodox,2001-11-30,3.02,0.53,1.86,0.46,1.81,0.27,0.83,0.7

In [8]:
f_df = pd.read_csv('ufc_cleaned.csv')

f_df = pd.concat([fights_df, f_df], ignore_index=True)

f_df.to_csv('ufc_cleaned.csv', index=False)