In [16]:
import re
import time
import unicodedata
import requests
from bs4 import BeautifulSoup
import pandas as pd

WEIGH_IN_URL = (
    "https://www.ufc.com/news/official-weigh-results-ufc-fight-night-muhammad-vs-bonfim"
)
MATCHES_CSV = "ufc_fights_data.csv"

SESSION = requests.Session()
SESSION.headers.update({
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    )
})

BOUT_LINE_RE = re.compile(
    r"^(?:(?P<weight_class>.+?):\s*)?"
    r"(?P<f1>.+?)\s*\((?P<w1>\d+(?:\.\d+)?)\*?\)\s*vs\s*"
    r"(?P<f2>.+?)\s*\((?P<w2>\d+(?:\.\d+)?)\*?\)\*?\s*$",
    re.I,
)


def normalize_weight_class(raw: str | None) -> str | None:
    if not raw:
        return None
    wc = raw.strip()
    wc = re.sub(r"^(?:Main Event|Co-Main Event)\s*-\s*", "", wc, flags=re.I)
    wc = re.sub(r"^UFC\s+", "", wc, flags=re.I)
    wc = re.sub(r"\s+Championship$", "", wc, flags=re.I)
    wc = re.sub(r"\s+Bout$", "", wc, flags=re.I)
    return wc.strip()


FIGHTER_ALIASES = {
    "dariya zheleznyakova": "daria zhelezniakova",
}


def normalize_fighter(name: str) -> str:
    name = unicodedata.normalize("NFKD", name)
    name = "".join(c for c in name if not unicodedata.combining(c))
    name = name.replace("'", "'").replace("'", "'").replace("`", "'")
    name = re.sub(r"[-–—]", " ", name)
    name = re.sub(r"\s+", " ", name.strip().lower())
    name = re.sub(r"\s+iii$", "", name)
    return FIGHTER_ALIASES.get(name, name)


def normalize_event_name(name: str) -> str:
    """Normalize event titles for matching article h2 tags to ufcstats names."""
    name = unicodedata.normalize("NFKD", name)
    name = "".join(c for c in name if not unicodedata.combining(c))
    name = name.lower().replace("'", "'")
    name = re.sub(r"\.", "", name)
    name = re.sub(r"[-–—]", " ", name)
    name = re.sub(r"\s+vs\.?\s+", " vs ", name)
    name = re.sub(r"\s+", " ", name.strip())
    return name


OFFICIAL_WEIGH_IN_RESULTS_RE = re.compile(
    r"\s*Official\s+Weigh[- ]?In\s+Results:?\s*$",
    re.I,
)


def parse_event_name(title: str) -> str:
    """Normalize event title from an article heading."""
    parts = [p.strip() for p in title.split("|") if p.strip()]
    name = parts[1] if len(parts) > 1 else parts[0]
    name = re.sub(r"^Official Weigh-In Results\s*", "", name, flags=re.I).strip()
    name = OFFICIAL_WEIGH_IN_RESULTS_RE.sub("", name).strip()

    fight_night = re.match(r"UFC Fight Night:\s*(.+)", name, re.I)
    if fight_night:
        return f"UFC FIGHT NIGHT: {fight_night.group(1).strip().upper()}"

    numbered = re.match(r"UFC\s+(\d+):\s*(.+)", name, re.I)
    if numbered:
        return f"UFC {numbered.group(1)}: {numbered.group(2).strip()}"

    return name


def event_bout_from_name(event_name: str) -> str:
    """Main event bout portion from an event title."""
    bout = re.sub(r"^UFC Fight Night:\s*", "", event_name, flags=re.I)
    bout = re.sub(r"^UFC\s+\d+:\s*", "", bout, flags=re.I)
    return bout.strip()


def extract_rematch_number(text: str) -> int | None:
    """Trailing rematch number, e.g. 'Holloway vs Oliveira 2' -> 2."""
    match = re.search(r"\s+(\d+)\s*$", text.strip())
    if match:
        return int(match.group(1))
    return None


def strip_rematch_suffix(text: str) -> str:
    return re.sub(r"\s+\d+\s*$", "", text.strip())


def parse_fighters_from_bout(bout: str) -> tuple[str, str] | None:
    """Parse main-event fighters from a bout title, stripping rematch suffixes."""
    bout = strip_rematch_suffix(bout)
    match = re.match(r"(.+?)\s+vs\.?\s+(.+)", bout, re.I)
    if not match:
        return None
    return match.group(1).strip(), match.group(2).strip()


def extract_rematch_number_from_soup(soup: BeautifulSoup) -> int | None:
    h2_name = extract_event_name_from_h2(soup)
    if h2_name:
        rematch = extract_rematch_number(event_bout_from_name(h2_name))
        if rematch is not None:
            return rematch

    h1 = soup.find("h1")
    if h1:
        for part in h1.get_text(strip=True).split("|"):
            part = part.strip()
            if not re.search(r"UFC", part, re.I):
                continue
            numbered = re.search(r"UFC\s+\d+:\s*(.+)", part, re.I)
            if numbered:
                rematch = extract_rematch_number(numbered.group(1))
                if rematch is not None:
                    return rematch
            fight_night = re.search(r"UFC Fight Night:\s*(.+)", part, re.I)
            if fight_night:
                rematch = extract_rematch_number(fight_night.group(1))
                if rematch is not None:
                    return rematch
    return None


def fighter_pair_key(f1: str, f2: str) -> tuple[str, str]:
    return tuple(sorted([normalize_fighter(f1), normalize_fighter(f2)]))


def fighters_match(name_a: str, name_b: str) -> bool:
    """Flexible fighter name comparison for article vs stats spelling differences."""
    a = normalize_fighter(name_a)
    b = normalize_fighter(name_b)
    if a == b:
        return True
    if a in b or b in a:
        return True
    a_last, b_last = a.split()[-1], b.split()[-1]
    return len(a_last) > 3 and a_last == b_last


def pair_matches_bout(f1: str, f2: str, p1: str, p2: str) -> bool:
    return (fighters_match(f1, p1) and fighters_match(f2, p2)) or (
        fighters_match(f1, p2) and fighters_match(f2, p1)
    )


def extract_event_name_from_h2(soup: BeautifulSoup) -> str | None:
    for h2 in soup.find_all("h2"):
        text = h2.get_text(strip=True)
        if re.search(r"official\s+weigh[- ]?in\s+results", text, re.I) and re.match(
            r"UFC", text, re.I
        ):
            return parse_event_name(text)
    return None


def extract_ufc_number(soup: BeautifulSoup) -> str | None:
    for tag in soup.find_all(["h1", "title"]):
        text = tag.get_text(strip=True)
        if not re.search(r"weigh", text, re.I):
            continue

        match = re.search(r"UFC\s+(\d+)\s+WEIGH", text, re.I)
        if match:
            return match.group(1)

        match = re.search(r"UFC\s+(\d+)\s*:", text, re.I)
        if match:
            return match.group(1)

        match = re.search(r"UFC\s+(\d+)\b", text, re.I)
        if match:
            return match.group(1)
    return None


def extract_bout_lines(soup: BeautifulSoup) -> list[dict]:
    rows = []
    seen_lines: set[str] = set()
    for text_node in soup.find_all(string=BOUT_LINE_RE):
        line = text_node.strip()
        if line in seen_lines:
            continue
        seen_lines.add(line)

        match = BOUT_LINE_RE.search(line)
        if not match:
            continue

        rows.append(
            {
                "line": line,
                "weight_class": normalize_weight_class(match.group("weight_class")),
                "f1": match.group("f1").strip(),
                "w1": float(match.group("w1")),
                "f2": match.group("f2").strip(),
                "w2": float(match.group("w2")),
            }
        )
    return rows


def extract_main_event_pair(
    soup: BeautifulSoup, bout_lines: list[dict]
) -> tuple[str, str] | None:
    """Main event fighters from a 'Main Event' section, else the first bout line."""
    if not bout_lines:
        return None

    page_text = soup.get_text("\n")
    main_match = re.search(
        r"Main Event\s*\n\s*"
        r"(?P<f1>.+?)\s*\(\d+(?:\.\d+)?\)\s*vs\s*"
        r"(?P<f2>.+?)\s*\(\d+(?:\.\d+)?\)",
        page_text,
        re.I,
    )
    if main_match:
        return main_match.group("f1").strip(), main_match.group("f2").strip()

    first = bout_lines[0]
    return first["f1"], first["f2"]


def bout_lines_to_dataframe(bout_lines: list[dict], event_name: str) -> pd.DataFrame:
    rows = []
    for bout in bout_lines:
        rows.append(
            {
                "fighter": bout["f1"],
                "weigh_in": bout["w1"],
                "weight_class": bout["weight_class"],
                "event": event_name,
            }
        )
        rows.append(
            {
                "fighter": bout["f2"],
                "weigh_in": bout["w2"],
                "weight_class": bout["weight_class"],
                "event": event_name,
            }
        )
    return pd.DataFrame(rows)


def build_ufc_number_index(stats_events: dict[str, str]) -> dict[str, str]:
    index: dict[str, str] = {}
    for event_date, event_name in stats_events.items():
        match = re.match(r"UFC\s+(\d+)\s*:", event_name, re.I)
        if match:
            index[match.group(1)] = event_date
    return index


def find_event_dates_by_main_event_pair(
    f1: str,
    f2: str,
    fights_df: pd.DataFrame,
) -> list[str]:
    matches: list[str] = []
    for event_date in fights_df["event_date"].drop_duplicates():
        card = fights_df[fights_df["event_date"] == event_date]
        if card.empty:
            continue
        main = card.iloc[0]
        if pair_matches_bout(f1, f2, main["p1_fighter"], main["p2_fighter"]):
            matches.append(event_date)
    return matches


def disambiguate_event_dates(
    candidates: list[str],
    stats_events: dict[str, str],
    weigh_in_df: pd.DataFrame,
    fights_df: pd.DataFrame,
    ufc_number: str | None = None,
    rematch_number: int | None = None,
) -> str | None:
    if not candidates:
        return None
    if len(candidates) == 1:
        return candidates[0]

    if ufc_number:
        filtered = [
            event_date
            for event_date in candidates
            if re.match(rf"UFC\s+{ufc_number}\s*:", stats_events[event_date], re.I)
        ]
        if len(filtered) == 1:
            return filtered[0]
        if filtered:
            candidates = filtered

    if rematch_number is not None:
        filtered = [
            event_date
            for event_date in candidates
            if extract_rematch_number(event_bout_from_name(stats_events[event_date]))
            == rematch_number
        ]
        if len(filtered) == 1:
            return filtered[0]
        if filtered:
            candidates = filtered

    weigh_fighters = {normalize_fighter(n) for n in weigh_in_df["fighter"]}
    best_date = None
    best_count = 0
    for event_date in candidates:
        card = fights_df[fights_df["event_date"] == event_date]
        event_fighters = set(card["p1_fighter"].map(normalize_fighter)) | set(
            card["p2_fighter"].map(normalize_fighter)
        )
        overlap = len(weigh_fighters & event_fighters)
        if overlap > best_count:
            best_count = overlap
            best_date = event_date
    return best_date


def find_event_by_main_event_pair(
    f1: str,
    f2: str,
    fights_df: pd.DataFrame,
    stats_events: dict[str, str],
    weigh_in_df: pd.DataFrame,
    ufc_number: str | None = None,
    rematch_number: int | None = None,
) -> str | None:
    candidates = find_event_dates_by_main_event_pair(f1, f2, fights_df)
    return disambiguate_event_dates(
        candidates,
        stats_events,
        weigh_in_df,
        fights_df,
        ufc_number=ufc_number,
        rematch_number=rematch_number,
    )


def find_event_by_fighter_overlap(
    weigh_in_df: pd.DataFrame,
    fights_df: pd.DataFrame,
    min_overlap: int = 4,
) -> str | None:
    weigh_fighters = {normalize_fighter(n) for n in weigh_in_df["fighter"]}
    best_date = None
    best_count = 0

    for event_date in fights_df["event_date"].drop_duplicates():
        card = fights_df[fights_df["event_date"] == event_date]
        event_fighters = set(card["p1_fighter"].map(normalize_fighter)) | set(
            card["p2_fighter"].map(normalize_fighter)
        )
        overlap = len(weigh_fighters & event_fighters)
        if overlap > best_count:
            best_count = overlap
            best_date = event_date

    if best_date and best_count >= min_overlap:
        return best_date
    return None


def match_article_to_event(
    soup: BeautifulSoup,
    weigh_in_df: pd.DataFrame,
    fights_df: pd.DataFrame,
    stats_events: dict[str, str],
    event_name_index: dict[str, str],
    ufc_number_index: dict[str, str],
    bout_lines: list[dict],
) -> tuple[str | None, str, str]:
    """Return (event_date, event_name, match_method)."""
    ufc_number = extract_ufc_number(soup)
    rematch_number = extract_rematch_number_from_soup(soup)

    h2_name = extract_event_name_from_h2(soup)
    if h2_name:
        event_date = event_name_index.get(
            normalize_event_name(
                h2_name.replace("UFC FIGHT NIGHT:", "UFC Fight Night:")
            )
        )
        if event_date and rematch_number is not None:
            event_rematch = extract_rematch_number(
                event_bout_from_name(stats_events[event_date])
            )
            if event_rematch != rematch_number:
                event_date = None
        if event_date:
            return event_date, stats_events[event_date], "h2"

        h2_pair = parse_fighters_from_bout(event_bout_from_name(h2_name))
        if h2_pair:
            event_date = find_event_by_main_event_pair(
                h2_pair[0],
                h2_pair[1],
                fights_df,
                stats_events,
                weigh_in_df,
                ufc_number=ufc_number,
                rematch_number=rematch_number,
            )
            if event_date:
                return event_date, stats_events[event_date], "h2"

    if ufc_number:
        event_date = ufc_number_index.get(ufc_number)
        if event_date:
            return event_date, stats_events[event_date], "ufc_number"

    main_pair = extract_main_event_pair(soup, bout_lines)
    if main_pair:
        event_date = find_event_by_main_event_pair(
            main_pair[0],
            main_pair[1],
            fights_df,
            stats_events,
            weigh_in_df,
            ufc_number=ufc_number,
            rematch_number=rematch_number,
        )
        if event_date:
            return event_date, stats_events[event_date], "main_event_pair"

    event_date = find_event_by_fighter_overlap(weigh_in_df, fights_df)
    if event_date:
        return event_date, stats_events[event_date], "fighter_overlap"

    return None, "", ""


def scrape_weigh_in_page(url: str, retries: int = 3) -> tuple[BeautifulSoup, list[dict], pd.DataFrame]:
    """Fetch a weigh-in article and parse bout lines without requiring h2 tags."""
    last_error = None
    for attempt in range(retries):
        try:
            response = SESSION.get(url, timeout=30)
            response.raise_for_status()
            break
        except requests.RequestException as e:
            last_error = e
            if attempt < retries - 1:
                time.sleep(2 * (attempt + 1))
            else:
                raise last_error

    soup = BeautifulSoup(response.text, "html.parser")
    bout_lines = extract_bout_lines(soup)
    if not bout_lines:
        raise ValueError("No weigh-in results found on page")

    placeholder_event = extract_event_name_from_h2(soup) or "Unknown Event"
    weigh_in_df = bout_lines_to_dataframe(bout_lines, placeholder_event)
    return soup, bout_lines, weigh_in_df


def scrape_weigh_ins(url: str, retries: int = 3) -> tuple[str, pd.DataFrame]:
    """Scrape fighter weigh-in weights from a UFC.com official weigh-in article."""
    soup, bout_lines, weigh_in_df = scrape_weigh_in_page(url, retries=retries)
    event_name = extract_event_name_from_h2(soup)
    if not event_name:
        main_pair = extract_main_event_pair(soup, bout_lines)
        if main_pair:
            event_name = f"{main_pair[0]} vs {main_pair[1]}"
        else:
            h1 = soup.find("h1")
            event_name = h1.get_text(strip=True) if h1 else "Unknown Event"

    weigh_in_df = bout_lines_to_dataframe(bout_lines, event_name)
    return event_name, weigh_in_df


def validate_event_weigh_ins(
    weigh_in_df: pd.DataFrame,
    fights_df: pd.DataFrame,
    event_date: str,
) -> tuple[pd.DataFrame, dict]:
    """Cross-reference weigh-ins against a known event date from scrapeMatches."""
    event_fights = fights_df[fights_df["event_date"] == event_date].copy()
    weigh_in_fighters = {normalize_fighter(n) for n in weigh_in_df["fighter"]}
    event_fighters = set(event_fights["p1_fighter"].map(normalize_fighter)) | set(
        event_fights["p2_fighter"].map(normalize_fighter)
    )

    matched = weigh_in_fighters & event_fighters
    missing_from_weigh_in = sorted(event_fighters - weigh_in_fighters)
    extra_on_weigh_in = sorted(weigh_in_fighters - event_fighters)

    validated = validate_weigh_ins(weigh_in_df, event_fights)
    summary = {
        "matched_event_date": event_date,
        "weigh_in_fighters": len(weigh_in_fighters),
        "matched_fighters": len(matched),
        "event_card_fighters": len(event_fighters),
        "all_fighters_match": not missing_from_weigh_in and not extra_on_weigh_in,
        "missing_from_weigh_in": missing_from_weigh_in,
        "extra_on_weigh_in": extra_on_weigh_in,
    }
    return validated, summary


def validate_weigh_ins(
    weigh_in_df: pd.DataFrame, event_fights: pd.DataFrame
) -> pd.DataFrame:
    """Flag fighters that appear on the weigh-in page but not on the matched event card."""
    if event_fights.empty:
        weigh_in_df = weigh_in_df.copy()
        weigh_in_df["on_event_card"] = False
        return weigh_in_df

    event_fighters = set(event_fights["p1_fighter"].map(normalize_fighter)) | set(
        event_fights["p2_fighter"].map(normalize_fighter)
    )

    validated = weigh_in_df.copy()
    validated["on_event_card"] = validated["fighter"].map(
        lambda n: normalize_fighter(n) in event_fighters
    )
    return validated

In [17]:
# Load scrapeMatches output
fights_df = pd.read_csv(MATCHES_CSV)
print(f"Loaded {len(fights_df)} fights from {MATCHES_CSV}")

# Scrape weigh-in page
event_name, weigh_in_df = scrape_weigh_ins(WEIGH_IN_URL)
print(f"\nScraped event: {event_name}")
print(f"Weigh-in records: {len(weigh_in_df)}")

# Cross-reference with scrapeMatches using the known event date
event_weigh_ins, match_summary = validate_event_weigh_ins(
    weigh_in_df, fights_df, "June 06, 2026"
)

print("\n--- Event cross-reference ---")
print(f"Event exists in scrapeMatches: {match_summary['matched_event_date'] is not None}")
print(f"Matched event date: {match_summary['matched_event_date']}")
print(
    f"Fighters matched: {match_summary['matched_fighters']}/{match_summary['weigh_in_fighters']} "
    f"(event card has {match_summary['event_card_fighters']} fighters)"
)
print(f"Full card alignment: {match_summary['all_fighters_match']}")

weigh_in_df = event_weigh_ins

if not match_summary["all_fighters_match"]:
    if match_summary["missing_from_weigh_in"]:
        print(f"On card but missing from weigh-in page: {match_summary['missing_from_weigh_in']}")
    if match_summary["extra_on_weigh_in"]:
        print(f"On weigh-in page but not on card: {match_summary['extra_on_weigh_in']}")

weigh_in_df

Loaded 8705 fights from ufc_fights_data.csv

Scraped event: UFC FIGHT NIGHT: MUHAMMAD VS BONFIM
Weigh-in records: 24

--- Event cross-reference ---
Event exists in scrapeMatches: True
Matched event date: June 06, 2026
Fighters matched: 24/24 (event card has 24 fighters)
Full card alignment: True

,fighter,weigh_in,weight_class,event,on_event_card
0,Belal Muhammad,170.5,Welterweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
1,Gabriel Bonfim,170.5,Welterweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
2,Brendan Allen,185.5,Middleweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
3,Edmen Shahbazyan,186.0,Middleweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
4,Fares Ziam,156.0,Lightweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
5,Tom Nolan,155.0,Lightweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
6,Bryce Mitchell,135.5,Bantamweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
7,Santiago Luna,136.0,Bantamweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
8,Iwo Baraniewski,206.0,Light Heavyweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
9,Junior Tafa,206.0,Light Heavyweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
10,Matt Schnell,129.5,Catchweight (130-lb),UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
11,Alessandro Costa,129.5,Catchweight (130-lb),UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
12,Marcus McGhee,136.0,Bantamweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
13,John Yannis,136.0,Bantamweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
14,Bruno Silva,126.0,Flyweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
15,Edgar Chairez,126.0,Flyweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
16,Priscila Cachoeira,135.5,Women’s Bantamweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
17,Chelsea Chandler,135.0,Women’s Bantamweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
18,Jordan Leavitt,145.5,Featherweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
19,Joanderson Brito,145.5,Featherweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
20,Jeisla Chaves,124.0,Women’s Flyweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
21,Yuneisy Duben,125.0,Women’s Flyweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
22,Ketlen Souza,116.0,Women’s Strawweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True
23,Ariane Carnelossi,116.0,Women’s Strawweight,UFC FIGHT NIGHT: MUHAMMAD VS BONFIM,True

In [18]:
import hashlib
from urllib.parse import urljoin, urlparse

WEIGH_IN_SEARCH_BASE = (
    "https://www.ufc.com/search?query=weigh%20in%20&type=news&page="
)


def fetch_all_weigh_in_article_urls() -> list[str]:
    """Collect every weigh-in news article from paginated UFC.com search results."""
    urls: list[str] = []
    seen: set[str] = set()
    page = 0

    while True:
        search_url = f"{WEIGH_IN_SEARCH_BASE}{page}"
        response = SESSION.get(search_url, timeout=30)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")

        page_links: list[str] = []
        for anchor in soup.find_all("a", href=True):
            href = anchor["href"]
            if href.startswith("https://www.ufc.com"):
                href = href.replace("https://www.ufc.com", "", 1)
            if not href.startswith("/news/"):
                continue
            if "weigh" not in href.lower():
                continue
            if href in seen:
                continue
            seen.add(href)
            page_links.append(urljoin("https://www.ufc.com", href))

        if not page_links:
            break

        urls.extend(page_links)
        page += 1
        time.sleep(0.2)

    return urls


def fetch_ufcstats_events() -> dict[str, str]:
    """Return {event_date: event_name} for all completed events on ufcstats."""

    def fetch_page(url):
        response = SESSION.get(url)
        if "Checking your browser" not in response.text:
            return response
        match = re.search(r'var nonce="([^"]+)"', response.text)
        if not match:
            return response
        nonce = match.group(1)
        n = 0
        while not hashlib.sha256(f"{nonce}:{n}".encode()).hexdigest().startswith("00"):
            n += 1
        base = f"{urlparse(url).scheme}://{urlparse(url).netloc}"
        SESSION.post(
            f"{base}/__c",
            data={"nonce": nonce, "n": n},
            headers={"Content-Type": "application/x-www-form-urlencoded"},
        )
        return SESSION.get(url)

    response = fetch_page("http://ufcstats.com/statistics/events/completed?page=all")
    response.raise_for_status()
    soup = BeautifulSoup(response.content, "html.parser")

    events = {}
    for row in soup.select("tr.b-statistics__table-row"):
        link = row.select_one("a.b-link.b-link_style_black")
        if not link:
            continue
        date_el = row.select_one("td")
        date_text = date_el.get_text(" ", strip=True) if date_el else ""
        date_match = re.search(r"([A-Za-z]+ \d{1,2}, \d{4})", date_text)
        if date_match:
            events[date_match.group(1)] = link.text.strip()
    return events


def build_event_name_index(stats_events: dict[str, str]) -> dict[str, str]:
    """Map normalized ufcstats event names back to event dates."""
    index: dict[str, str] = {}
    for event_date, event_name in stats_events.items():
        index[normalize_event_name(event_name)] = event_date
    return index


if "fights_df" not in dir():
    fights_df = pd.read_csv(MATCHES_CSV)

stats_events = fetch_ufcstats_events()
event_name_index = build_event_name_index(stats_events)
ufc_number_index = build_ufc_number_index(stats_events)
all_event_dates = fights_df["event_date"].drop_duplicates().tolist()

print("Collecting weigh-in articles from UFC.com search...")
article_urls = fetch_all_weigh_in_article_urls()
print(f"Found {len(article_urls)} weigh-in news articles")

all_weigh_ins = []
scrape_log = []
best_by_event: dict[str, dict] = {}
total_articles = len(article_urls)

for i, url in enumerate(article_urls, 1):
    if i % 25 == 0 or i == 1:
        print(f"Processing article {i}/{total_articles}...")

    time.sleep(0.15)

    try:
        soup, bout_lines, event_weigh_ins = scrape_weigh_in_page(url)
        event_date, event_name, match_method = match_article_to_event(
            soup,
            event_weigh_ins,
            fights_df,
            stats_events,
            event_name_index,
            ufc_number_index,
            bout_lines,
        )

        if event_date is None:
            scrape_log.append(
                {
                    "url": url,
                    "article_event": None,
                    "event_date": None,
                    "event_name": None,
                    "match_method": None,
                    "status": "skipped: no matching event in matches csv",
                }
            )
            continue

        if event_date not in all_event_dates:
            scrape_log.append(
                {
                    "url": url,
                    "article_event": event_name,
                    "event_date": event_date,
                    "event_name": stats_events.get(event_date),
                    "match_method": match_method,
                    "status": "skipped: event not in matches csv",
                }
            )
            continue

        event_weigh_ins = bout_lines_to_dataframe(bout_lines, event_name)
        event_weigh_ins, summary = validate_event_weigh_ins(
            event_weigh_ins, fights_df, event_date
        )

        if summary["matched_fighters"] < 2:
            scrape_log.append(
                {
                    "url": url,
                    "article_event": event_name,
                    "event_date": event_date,
                    "event_name": stats_events[event_date],
                    "match_method": match_method,
                    "status": (
                        "skipped: too few fighters matched "
                        f"({summary['matched_fighters']}/{summary['event_card_fighters']})"
                    ),
                }
            )
            continue

        event_weigh_ins["event_date"] = event_date
        event_weigh_ins["weigh_in_url"] = url

        entry = {
            "url": url,
            "article_event": event_name,
            "event_date": event_date,
            "event_name": stats_events[event_date],
            "scraped_event": event_name,
            "match_method": match_method,
            "matched_fighters": summary["matched_fighters"],
            "event_card_fighters": summary["event_card_fighters"],
            "all_fighters_match": summary["all_fighters_match"],
            "missing_from_weigh_in": ", ".join(summary["missing_from_weigh_in"]),
            "event_weigh_ins": event_weigh_ins,
            "status": "ok",
        }

        existing = best_by_event.get(event_date)
        if existing is None or entry["matched_fighters"] > existing["matched_fighters"]:
            best_by_event[event_date] = entry

    except ValueError as e:
        scrape_log.append(
            {
                "url": url,
                "article_event": None,
                "event_date": None,
                "event_name": None,
                "match_method": None,
                "status": f"skipped: {e}",
            }
        )
    except Exception as e:
        scrape_log.append(
            {
                "url": url,
                "article_event": None,
                "event_date": None,
                "event_name": None,
                "match_method": None,
                "status": f"error: {e}",
            }
        )

for event_date, entry in best_by_event.items():
    event_weigh_ins = entry.pop("event_weigh_ins")
    all_weigh_ins.append(event_weigh_ins)
    scrape_log.append(entry)
    print(
        f"{event_date} | {entry['event_name']} - ok "
        f"({len(event_weigh_ins)} records, "
        f"{entry['matched_fighters']}/{entry['event_card_fighters']} matched)"
    )

weigh_ins_df = pd.concat(all_weigh_ins, ignore_index=True) if all_weigh_ins else pd.DataFrame()
WEIGH_INS_CSV = "ufc_weigh_ins.csv"
weigh_ins_df.to_csv(WEIGH_INS_CSV, index=False)
print(f"Saved {len(weigh_ins_df):,} weigh-in records to {WEIGH_INS_CSV}")

scrape_log_df = pd.DataFrame(scrape_log)

matched_events = set(best_by_event)
missing_events = [
    {"event_date": d, "event_name": stats_events[d]}
    for d in all_event_dates
    if d in stats_events and d not in matched_events
]

ok_count = len(best_by_event)
print(f"\n{'=' * 60}")
print(f"Matched {ok_count}/{len(all_event_dates)} events from {len(article_urls)} articles")
print(f"Total weigh-in records: {len(weigh_ins_df)}")
print(f"Events still missing weigh-in articles: {len(missing_events)}")
if not scrape_log_df.empty:
    ok_rows = scrape_log_df[scrape_log_df["status"] == "ok"]
    if not ok_rows.empty and "match_method" in ok_rows.columns:
        print("\nMatch methods:")
        print(ok_rows["match_method"].value_counts().to_string())
if missing_events[:10]:
    print("First missing events:")
    for item in missing_events[:10]:
        print(f"  {item['event_date']} | {item['event_name']}")

scrape_log_df

Collecting weigh-in articles from UFC.com search...
Found 761 weigh-in news articles
Processing article 1/761...
Processing article 25/761...
Processing article 50/761...
Processing article 75/761...
Processing article 100/761...
Processing article 125/761...
Processing article 150/761...
Processing article 175/761...
Processing article 200/761...
Processing article 225/761...
Processing article 250/761...
Processing article 275/761...
Processing article 300/761...
Processing article 325/761...
Processing article 350/761...
Processing article 375/761...
Processing article 400/761...
Processing article 425/761...
Processing article 450/761...
Processing article 475/761...
Processing article 500/761...
Processing article 525/761...
Processing article 550/761...
Processing article 575/761...
Processing article 600/761...
Processing article 625/761...
Processing article 650/761...
Processing article 675/761...
Processing article 700/761...
Processing article 725/761...
Processing article 750/761...
June 06, 2026 | UFC Fight Night: Muhammad vs. Bonfim - ok (24 records, 24/24 matched)
May 30, 2026 | UFC Fight Night: Song vs. Figueiredo - ok (24 records, 24/26 matched)
May 16, 2026 | UFC Fight Night: Allen vs. Costa - ok (26 records, 26/26 matched)
May 09, 2026 | UFC 328: Chimaev vs. Strickland - ok (26 records, 26/26 matched)
May 02, 2026 | UFC Fight Night: Della Maddalena vs. Prates - ok (26 records, 26/26 matched)
April 25, 2026 | UFC Fight Night: Sterling vs. Zalal - ok (26 records, 26/26 matched)
April 18, 2026 | UFC Fight Night: Burns vs. Malott - ok (24 records, 24/24 matched)
April 11, 2026 | UFC 327: Prochazka vs. Ulberg - ok (22 records, 22/24 matched)
April 04, 2026 | UFC Fight Night: Moicano vs. Duncan - ok (24 records, 24/26 matched)
March 28, 2026 | UFC Fight Night: Adesanya vs. Pyfer - ok (26 records, 25/26 matched)
March 21, 2026 | UFC Fight Night: Evloev vs. Murphy - ok (28 records, 25/26 matched)
March 14, 2026 | UFC Fight Night: Emmett vs. Vallejos - ok (28 records, 27/28 matched)
March 07, 2026 | UFC 326: Holloway vs. Oliveira 2 - ok (24 records, 24/24 matched)
February 28, 2026 | UFC Fight Night: Moreno vs. Kavanagh - ok (26 records, 25/26 matched)
February 21, 2026 | UFC Fight Night: Strickland vs. Hernandez - ok (28 records, 26/28 matched)
February 07, 2026 | UFC Fight Night: Bautista vs. Oliveira - ok (22 records, 22/26 matched)
January 31, 2026 | UFC 325: Volkanovski vs. Lopes 2 - ok (26 records, 26/26 matched)
January 24, 2026 | UFC 324: Gaethje vs. Pimblett - ok (22 records, 19/22 matched)
December 13, 2025 | UFC Fight Night: Royval vs. Kape - ok (26 records, 23/24 matched)
December 06, 2025 | UFC 323: Dvalishvili vs. Yan 2 - ok (26 records, 26/28 matched)
November 22, 2025 | UFC Fight Night: Tsarukyan vs. Hooker - ok (28 records, 28/28 matched)
November 15, 2025 | UFC 322: Della Maddalena vs. Makhachev - ok (26 records, 26/28 matched)
November 08, 2025 | UFC Fight Night: Bonfim vs. Brown - ok (24 records, 24/24 matched)
November 01, 2025 | UFC Fight Night: Garcia vs. Onama - ok (26 records, 25/26 matched)
October 25, 2025 | UFC 321: Aspinall vs. Gane - ok (22 records, 22/26 matched)
October 18, 2025 | UFC Fight Night: De Ridder vs. Allen - ok (26 records, 26/26 matched)
October 11, 2025 | UFC Fight Night: Oliveira vs. Gamrot - ok (24 records, 24/24 matched)
October 04, 2025 | UFC 320: Ankalaev vs. Pereira 2 - ok (26 records, 25/28 matched)
September 27, 2025 | UFC Fight Night: Ulberg vs. Reyes - ok (24 records, 23/24 matched)
September 13, 2025 | UFC Fight Night: Lopes vs. Silva - ok (26 records, 25/28 matched)
September 06, 2025 | UFC Fight Night: Imavov vs. Borralho - ok (28 records, 26/26 matched)
August 23, 2025 | UFC Fight Night: Walker vs. Zhang - ok (24 records, 23/24 matched)
August 16, 2025 | UFC 319: Du Plessis vs. Chimaev - ok (24 records, 23/24 matched)
August 02, 2025 | UFC Fight Night: Taira vs. Park - ok (20 records, 20/24 matched)
July 26, 2025 | UFC Fight Night: Whittaker vs. De Ridder - ok (24 records, 23/24 matched)
July 19, 2025 | UFC 318: Holloway vs. Poirier 3 - ok (28 records, 28/28 matched)
July 12, 2025 | UFC Fight Night: Lewis vs. Teixeira - ok (24 records, 24/24 matched)
June 28, 2025 | UFC 317: Topuria vs. Oliveira - ok (22 records, 21/22 matched)
June 21, 2025 | UFC Fight Night: Hill vs. Rountree Jr. - ok (24 records, 23/24 matched)
June 14, 2025 | UFC Fight Night: Usman vs. Buckley - ok (26 records, 25/26 matched)
June 07, 2025 | UFC 316: Dvalishvili vs. O'Malley 2 - ok (24 records, 23/26 matched)
May 31, 2025 | UFC Fight Night: Blanchfield vs. Barber - ok (18 records, 13/18 matched)
May 17, 2025 | UFC Fight Night: Burns vs. Morales - ok (24 records, 22/22 matched)
May 10, 2025 | UFC 315: Muhammad vs. Della Maddalena - ok (24 records, 24/24 matched)
May 03, 2025 | UFC Fight Night: Sandhagen vs. Figueiredo - ok (24 records, 23/24 matched)
April 26, 2025 | UFC Fight Night: Machado Garry vs. Prates - ok (26 records, 25/28 matched)
April 12, 2025 | UFC 314: Volkanovski vs. Lopes - ok (24 records, 24/26 matched)
April 05, 2025 | UFC Fight Night: Emmett vs. Murphy - ok (22 records, 21/24 matched)
March 29, 2025 | UFC Fight Night: Moreno vs. Erceg - ok (24 records, 22/24 matched)
March 22, 2025 | UFC Fight Night: Edwards vs. Brady - ok (26 records, 25/26 matched)
March 15, 2025 | UFC Fight Night: Vettori vs. Dolidze 2 - ok (22 records, 21/26 matched)
March 08, 2025 | UFC 313: Pereira vs. Ankalaev - ok (24 records, 20/20 matched)
March 01, 2025 | UFC Fight Night: Kape vs. Almabayev - ok (20 records, 19/20 matched)
February 22, 2025 | UFC Fight Night: Cejudo vs. Song - ok (24 records, 24/24 matched)
February 15, 2025 | UFC Fight Night: Cannonier vs. Rodrigues - ok (24 records, 22/24 matched)
February 08, 2025 | UFC 312: Du Plessis vs. Strickland 2 - ok (24 records, 24/24 matched)
February 01, 2025 | UFC Fight Night: Adesanya vs. Imavov - ok (22 records, 21/22 matched)
January 18, 2025 | UFC 311: Makhachev vs. Moicano - ok (24 records, 21/26 matched)
January 11, 2025 | UFC Fight Night: Dern vs. Ribas 2 - ok (24 records, 24/28 matched)
December 14, 2024 | UFC Fight Night: Covington vs. Buckley - ok (26 records, 25/26 matched)
December 07, 2024 | UFC 310: Pantoja vs. Asakura - ok (26 records, 26/28 matched)
November 23, 2024 | UFC Fight Night: Yan vs. Figueiredo - ok (26 records, 25/26 matched)
November 16, 2024 | UFC 309: Jones vs. Miocic - ok (26 records, 24/24 matched)
November 09, 2024 | UFC Fight Night: Magny vs. Prates - ok (18 records, 17/22 matched)
November 02, 2024 | UFC Fight Night: Moreno vs. Albazi - ok (28 records, 26/26 matched)
October 26, 2024 | UFC 308: Topuria vs. Holloway - ok (26 records, 26/26 matched)
October 19, 2024 | UFC Fight Night: Hernandez vs. Pereira - ok (20 records, 20/22 matched)
October 12, 2024 | UFC Fight Night: Royval vs. Taira - ok (24 records, 23/24 matched)
October 05, 2024 | UFC 307: Pereira vs. Rountree Jr. - ok (24 records, 24/24 matched)
September 28, 2024 | UFC Fight Night: Moicano vs. Saint Denis - ok (28 records, 28/28 matched)
September 14, 2024 | UFC 306: Riyadh Season Noche UFC - ok (20 records, 18/20 matched)
September 07, 2024 | UFC Fight Night: Burns vs. Brady - ok (22 records, 21/24 matched)
August 24, 2024 | UFC Fight Night: Cannonier vs. Borralho - ok (24 records, 21/22 matched)
August 17, 2024 | UFC 305: Du Plessis vs. Adesanya - ok (24 records, 23/24 matched)
August 10, 2024 | UFC Fight Night: Tybura vs. Spivac 2 - ok (16 records, 16/20 matched)
August 03, 2024 | UFC Fight Night: Sandhagen vs. Nurmagomedov - ok (26 records, 26/26 matched)
July 27, 2024 | UFC 304: Edwards vs. Muhammad 2 - ok (26 records, 25/28 matched)
July 20, 2024 | UFC Fight Night: Lemos vs. Jandiroba - ok (22 records, 22/22 matched)
July 13, 2024 | UFC Fight Night: Namajunas vs. Cortez - ok (24 records, 23/24 matched)
June 29, 2024 | UFC 303: Pereira vs. Prochazka 2 - ok (24 records, 22/26 matched)
June 22, 2024 | UFC Fight Night: Whittaker vs. Aliskerov - ok (22 records, 22/22 matched)
June 15, 2024 | UFC Fight Night: Perez vs. Taira - ok (22 records, 21/22 matched)
June 08, 2024 | UFC Fight Night: Cannonier vs. Imavov - ok (28 records, 26/28 matched)
June 01, 2024 | UFC 302: Makhachev vs. Poirier - ok (22 records, 22/24 matched)
May 18, 2024 | UFC Fight Night: Barboza vs. Murphy - ok (24 records, 24/24 matched)
May 11, 2024 | UFC Fight Night: Lewis vs. Nascimento - ok (24 records, 23/24 matched)
May 04, 2024 | UFC 301: Pantoja vs. Erceg - ok (28 records, 26/26 matched)
April 27, 2024 | UFC Fight Night: Nicolau vs. Perez - ok (24 records, 23/26 matched)
April 13, 2024 | UFC 300: Pereira vs. Hill - ok (26 records, 25/26 matched)
April 06, 2024 | UFC Fight Night: Allen vs. Curtis 2 - ok (20 records, 20/24 matched)
March 30, 2024 | UFC Fight Night: Blanchfield vs. Fiorot - ok (26 records, 24/26 matched)
March 23, 2024 | UFC Fight Night: Ribas vs. Namajunas - ok (26 records, 25/26 matched)
March 16, 2024 | UFC Fight Night: Tuivasa vs. Tybura - ok (20 records, 19/26 matched)
March 09, 2024 | UFC 299: O'Malley vs. Vera 2 - ok (28 records, 26/28 matched)
March 02, 2024 | UFC Fight Night: Rozenstruik vs. Gaziev - ok (22 records, 22/22 matched)
February 24, 2024 | UFC Fight Night: Moreno vs. Royval 2 - ok (24 records, 22/24 matched)
February 17, 2024 | UFC 298: Volkanovski vs. Topuria - ok (24 records, 23/24 matched)
February 10, 2024 | UFC Fight Night: Hermansson vs. Pyfer - ok (28 records, 27/28 matched)
February 03, 2024 | UFC Fight Night: Dolidze vs. Imavov - ok (24 records, 24/26 matched)
January 20, 2024 | UFC 297: Strickland vs. Du Plessis - ok (20 records, 20/24 matched)
January 13, 2024 | UFC Fight Night: Ankalaev vs. Walker 2 - ok (24 records, 22/22 matched)
December 16, 2023 | UFC 296: Edwards vs. Covington - ok (24 records, 22/24 matched)
December 09, 2023 | UFC Fight Night: Song vs. Gutierrez - ok (20 records, 19/22 matched)
December 02, 2023 | UFC Fight Night: Dariush vs. Tsarukyan - ok (24 records, 22/24 matched)
November 18, 2023 | UFC Fight Night: Allen vs. Craig - ok (26 records, 26/28 matched)
November 11, 2023 | UFC 295: Prochazka vs. Pereira - ok (24 records, 23/26 matched)
November 04, 2023 | UFC Fight Night: Almeida vs. Lewis - ok (20 records, 17/20 matched)
October 21, 2023 | UFC 294: Makhachev vs. Volkanovski 2 - ok (22 records, 22/26 matched)
October 14, 2023 | UFC Fight Night: Yusuff vs. Barboza - ok (22 records, 19/22 matched)
October 07, 2023 | UFC Fight Night: Dawson vs. Green - ok (22 records, 19/20 matched)
September 23, 2023 | UFC Fight Night: Fiziev vs. Gamrot - ok (22 records, 19/22 matched)
September 16, 2023 | UFC Fight Night: Grasso vs. Shevchenko 2 - ok (22 records, 22/22 matched)
September 09, 2023 | UFC 293: Adesanya vs. Strickland - ok (24 records, 24/24 matched)
September 02, 2023 | UFC Fight Night: Gane vs. Spivac - ok (22 records, 21/22 matched)
August 26, 2023 | UFC Fight Night: Holloway vs. The Korean Zombie - ok (26 records, 23/26 matched)
August 19, 2023 | UFC 292: Sterling vs. O'Malley - ok (24 records, 21/24 matched)
August 12, 2023 | UFC Fight Night: Luque vs. Dos Anjos - ok (24 records, 21/26 matched)
August 05, 2023 | UFC Fight Night: Sandhagen vs. Font - ok (24 records, 22/24 matched)
July 29, 2023 | UFC 291: Poirier vs. Gaethje 2 - ok (22 records, 20/22 matched)
July 22, 2023 | UFC Fight Night: Aspinall vs. Tybura - ok (30 records, 30/30 matched)
July 15, 2023 | UFC Fight Night: Holm vs. Bueno Silva - ok (26 records, 25/26 matched)
July 08, 2023 | UFC 290: Volkanovski vs. Rodriguez - ok (26 records, 24/26 matched)
July 01, 2023 | UFC Fight Night: Strickland vs. Magomedov - ok (24 records, 22/24 matched)
June 24, 2023 | UFC Fight Night: Emmett vs. Topuria - ok (26 records, 25/26 matched)
June 17, 2023 | UFC Fight Night: Vettori vs. Cannonier - ok (24 records, 24/24 matched)
June 10, 2023 | UFC 289: Nunes vs. Aldana - ok (22 records, 22/22 matched)
June 03, 2023 | UFC Fight Night: Kara-France vs. Albazi - ok (26 records, 23/26 matched)
May 20, 2023 | UFC Fight Night: Dern vs. Hill - ok (22 records, 22/24 matched)
May 13, 2023 | UFC Fight Night: Rozenstruik vs. Almeida - ok (20 records, 19/22 matched)
May 06, 2023 | UFC 288: Sterling vs. Cejudo - ok (22 records, 22/24 matched)
April 29, 2023 | UFC Fight Night: Song vs. Simon - ok (20 records, 20/22 matched)
April 22, 2023 | UFC Fight Night: Pavlovich vs. Blaydes - ok (24 records, 20/22 matched)
April 15, 2023 | UFC Fight Night: Holloway vs. Allen - ok (26 records, 26/28 matched)
April 08, 2023 | UFC 287: Pereira vs. Adesanya 2 - ok (26 records, 24/24 matched)
March 25, 2023 | UFC Fight Night: Vera vs. Sandhagen - ok (22 records, 19/20 matched)
March 18, 2023 | UFC 286: Edwards vs. Usman 3 - ok (30 records, 29/30 matched)
March 11, 2023 | UFC Fight Night: Yan vs. Dvalishvili - ok (26 records, 25/26 matched)
March 04, 2023 | UFC 285: Jones vs. Gane - ok (28 records, 24/28 matched)
February 25, 2023 | UFC Fight Night: Muniz vs. Allen - ok (22 records, 19/20 matched)
February 18, 2023 | UFC Fight Night: Andrade vs. Blanchfield - ok (22 records, 22/22 matched)
February 11, 2023 | UFC 284: Makhachev vs. Volkanovski - ok (26 records, 23/26 matched)
February 04, 2023 | UFC Fight Night: Lewis vs. Spivac - ok (24 records, 20/22 matched)
January 21, 2023 | UFC 283: Teixeira vs. Hill - ok (30 records, 28/30 matched)
January 14, 2023 | UFC Fight Night: Strickland vs. Imavov - ok (22 records, 21/22 matched)
December 17, 2022 | UFC Fight Night: Cannonier vs. Strickland - ok (26 records, 25/26 matched)
December 10, 2022 | UFC 282: Blachowicz vs. Ankalaev - ok (26 records, 24/24 matched)
December 03, 2022 | UFC Fight Night: Thompson vs. Holland - ok (30 records, 27/28 matched)
November 12, 2022 | UFC 281: Adesanya vs. Pereira - ok (26 records, 24/28 matched)
November 05, 2022 | UFC Fight Night: Rodriguez vs. Lemos - ok (16 records, 14/22 matched)
October 29, 2022 | UFC Fight Night: Kattar vs. Allen - ok (22 records, 21/22 matched)
October 22, 2022 | UFC 280: Oliveira vs. Makhachev - ok (22 records, 21/24 matched)
October 15, 2022 | UFC Fight Night: Grasso vs. Araujo - ok (22 records, 21/22 matched)
October 01, 2022 | UFC Fight Night: Dern vs. Yan - ok (24 records, 22/22 matched)
September 17, 2022 | UFC Fight Night: Sandhagen vs. Song - ok (24 records, 24/26 matched)
September 10, 2022 | UFC 279: Diaz vs. Ferguson - ok (20 records, 20/26 matched)
September 03, 2022 | UFC Fight Night: Gane vs. Tuivasa - ok (24 records, 24/24 matched)
August 20, 2022 | UFC 278: Usman vs. Edwards - ok (24 records, 23/24 matched)
August 13, 2022 | UFC Fight Night: Vera vs. Cruz - ok (26 records, 24/26 matched)
August 06, 2022 | UFC Fight Night: Santos vs. Hill - ok (20 records, 17/20 matched)
July 30, 2022 | UFC 277: Pena vs. Nunes 2 - ok (26 records, 23/26 matched)
July 23, 2022 | UFC Fight Night: Blaydes vs. Aspinall - ok (26 records, 26/28 matched)
July 16, 2022 | UFC Fight Night: Ortega vs. Rodriguez - ok (24 records, 23/24 matched)
July 09, 2022 | UFC Fight Night: Dos Anjos vs. Fiziev - ok (24 records, 22/22 matched)
July 02, 2022 | UFC 276: Adesanya vs. Cannonier - ok (24 records, 22/24 matched)
June 25, 2022 | UFC Fight Night: Tsarukyan vs. Gamrot - ok (22 records, 22/24 matched)
June 18, 2022 | UFC Fight Night: Kattar vs. Emmett - ok (28 records, 26/26 matched)
June 11, 2022 | UFC 275: Teixeira vs. Prochazka - ok (10 records, 10/22 matched)
June 04, 2022 | UFC Fight Night: Volkov vs. Rozenstruik - ok (28 records, 28/28 matched)
May 21, 2022 | UFC Fight Night: Holm vs. Vieira - ok (22 records, 22/22 matched)
May 14, 2022 | UFC Fight Night: Blachowicz vs. Rakic - ok (20 records, 19/22 matched)
May 07, 2022 | UFC 274: Oliveira vs. Gaethje - ok (24 records, 21/28 matched)
April 30, 2022 | UFC Fight Night: Font vs. Vera - ok (22 records, 19/22 matched)
April 23, 2022 | UFC Fight Night: Lemos vs. Andrade - ok (24 records, 21/22 matched)
April 16, 2022 | UFC Fight Night: Luque vs. Muhammad - ok (28 records, 28/28 matched)
April 09, 2022 | UFC 273: Volkanovski vs. The Korean Zombie - ok (24 records, 19/24 matched)
March 26, 2022 | UFC Fight Night: Blaydes vs. Daukaus - ok (26 records, 24/24 matched)
March 19, 2022 | UFC Fight Night: Volkov vs. Aspinall - ok (24 records, 24/24 matched)
March 12, 2022 | UFC Fight Night: Santos vs. Ankalaev - ok (28 records, 27/28 matched)
March 05, 2022 | UFC 272: Covington vs. Masvidal - ok (26 records, 26/26 matched)
February 26, 2022 | UFC Fight Night: Makhachev vs. Green - ok (18 records, 18/22 matched)
February 19, 2022 | UFC Fight Night: Walker vs. Hill - ok (22 records, 22/24 matched)
February 12, 2022 | UFC 271: Adesanya vs. Whittaker 2 - ok (30 records, 24/28 matched)
February 05, 2022 | UFC Fight Night: Hermansson vs. Strickland - ok (22 records, 22/26 matched)
January 22, 2022 | UFC 270: Ngannou vs. Gane - ok (22 records, 22/22 matched)
January 15, 2022 | UFC Fight Night: Kattar vs. Chikadze - ok (20 records, 17/20 matched)
December 18, 2021 | UFC Fight Night: Lewis vs. Daukaus - ok (22 records, 19/26 matched)
December 11, 2021 | UFC 269: Oliveira vs. Poirier - ok (28 records, 26/28 matched)
December 04, 2021 | UFC Fight Night: Font vs. Aldo - ok (30 records, 26/26 matched)
November 20, 2021 | UFC Fight Night: Vieira vs. Tate - ok (24 records, 22/22 matched)
November 13, 2021 | UFC Fight Night: Holloway vs. Rodriguez - ok (22 records, 19/22 matched)
November 06, 2021 | UFC 268: Usman vs. Covington 2 - ok (28 records, 23/28 matched)
October 30, 2021 | UFC 267: Blachowicz vs. Teixeira - ok (26 records, 24/28 matched)
October 23, 2021 | UFC Fight Night: Costa vs. Vettori - ok (28 records, 26/28 matched)
October 16, 2021 | UFC Fight Night: Ladd vs. Dumont - ok (20 records, 19/20 matched)
October 09, 2021 | UFC Fight Night: Dern vs. Rodriguez - ok (18 records, 17/18 matched)
October 02, 2021 | UFC Fight Night: Santos vs. Walker - ok (20 records, 19/24 matched)
September 25, 2021 | UFC 266: Volkanovski vs. Ortega - ok (26 records, 26/26 matched)
September 18, 2021 | UFC Fight Night: Smith vs. Spann - ok (26 records, 24/28 matched)
September 04, 2021 | UFC Fight Night: Brunson vs. Till - ok (18 records, 17/18 matched)
August 28, 2021 | UFC Fight Night: Barboza vs. Chikadze - ok (22 records, 22/24 matched)
August 21, 2021 | UFC Fight Night: Cannonier vs. Gastelum - ok (24 records, 22/24 matched)
August 07, 2021 | UFC 265: Lewis vs. Gane - ok (26 records, 22/26 matched)
July 31, 2021 | UFC Fight Night: Hall vs. Strickland - ok (20 records, 17/20 matched)
July 24, 2021 | UFC Fight Night: Sandhagen vs. Dillashaw - ok (22 records, 22/22 matched)
July 17, 2021 | UFC Fight Night: Makhachev vs. Moises - ok (22 records, 19/20 matched)
July 10, 2021 | UFC 264: Poirier vs. McGregor 3 - ok (26 records, 22/24 matched)
June 26, 2021 | UFC Fight Night: Gane vs. Volkov - ok (26 records, 26/26 matched)
June 19, 2021 | UFC Fight Night: Jung vs. Ige - ok (24 records, 22/24 matched)
June 12, 2021 | UFC 263: Adesanya vs. Vettori 2 - ok (28 records, 27/28 matched)
June 05, 2021 | UFC Fight Night: Rozenstruik vs. Sakai - ok (28 records, 25/26 matched)
May 22, 2021 | UFC Fight Night: Font vs. Garbrandt - ok (26 records, 24/24 matched)
May 15, 2021 | UFC 262: Oliveira vs. Chandler - ok (24 records, 22/24 matched)
May 08, 2021 | UFC Fight Night: Rodriguez vs. Waterson - ok (18 records, 15/18 matched)
May 01, 2021 | UFC Fight Night: Reyes vs. Prochazka - ok (22 records, 21/22 matched)
April 24, 2021 | UFC 261: Usman vs. Masvidal 2 - ok (26 records, 25/26 matched)
April 17, 2021 | UFC Fight Night: Whittaker vs. Gastelum - ok (20 records, 18/20 matched)
April 10, 2021 | UFC Fight Night: Vettori vs. Holland - ok (28 records, 24/26 matched)
March 27, 2021 | UFC 260: Miocic vs. Ngannou - ok (20 records, 19/20 matched)
March 20, 2021 | UFC Fight Night: Brunson vs. Holland - ok (22 records, 18/20 matched)
March 13, 2021 | UFC Fight Night: Edwards vs. Muhammad - ok (26 records, 26/26 matched)
March 06, 2021 | UFC 259: Blachowicz vs. Adesanya - ok (30 records, 30/30 matched)

,url,article_event,event_date,event_name,match_method,status,scraped_event,matched_fighters,event_card_fighters,all_fighters_match,missing_from_weigh_in
0,https://www.ufc.com/news/official-weigh-result...,NaN,NaN,NaN,NaN,skipped: no matching event in matches csv,NaN,NaN,NaN,NaN,NaN
1,https://www.ufc.com/news/official-weigh-in-res...,NaN,NaN,NaN,NaN,skipped: no matching event in matches csv,NaN,NaN,NaN,NaN,NaN
2,https://www.ufc.com/news/official-weigh-result...,NaN,NaN,NaN,NaN,skipped: No weigh-in results found on page,NaN,NaN,NaN,NaN,NaN
3,https://www.ufc.com/news/official-weigh-result...,NaN,NaN,NaN,NaN,skipped: no matching event in matches csv,NaN,NaN,NaN,NaN,NaN
4,https://www.ufc.com/news/official-weigh-result...,NaN,NaN,NaN,NaN,skipped: no matching event in matches csv,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
736,https://www.ufc.com/news/ufc-105-weigh-results,UFC 105: Couture vs Vera,"November 14, 2009",UFC 105: Couture vs Vera,ufc_number,ok,UFC 105: Couture vs Vera,21.0,22.0,False,rolando delgado
737,https://www.ufc.com/news/official-ufc-106-weig...,UFC 106: Ortiz vs Griffin 2,"November 21, 2009",UFC 106: Ortiz vs Griffin 2,ufc_number,ok,UFC 106: Ortiz vs Griffin 2,18.0,20.0,False,"luiz cane, rogerio nogueira"
738,https://www.ufc.com/news/official-tuf-9-finale...,The Ultimate Fighter: United States vs. United...,"June 20, 2009",The Ultimate Fighter: United States vs. United...,main_event_pair,ok,The Ultimate Fighter: United States vs. United...,20.0,20.0,True,
739,https://www.ufc.com/news/ufc-104-weigh-results,UFC 104: Machida vs Shogun,"October 24, 2009",UFC 104: Machida vs Shogun,ufc_number,ok,UFC 104: Machida vs Shogun,15.0,22.0,False,"anthony johnson, antoni hardonk, eric schafer,..."
740,https://www.ufc.com/news/official-ufc-107-weig...,UFC 107: Penn vs Sanchez,"December 12, 2009",UFC 107: Penn vs Sanchez,ufc_number,ok,UFC 107: Penn vs Sanchez,19.0,22.0,False,"damarques johnson, edgar garcia, wilson gouveia"

In [19]:
AUG_CSV = "ufc_aug.csv"
WEIGH_INS_CSV = "ufc_weigh_ins.csv"
OUTPUT_CSV = "ufc_aug_weigh_in.csv"


def parse_event_date(date_str) -> pd.Timestamp | None:
    """Normalize event dates across ufc_aug (ISO) and weigh_ins_df (Month DD, YYYY)."""
    parsed = pd.to_datetime(date_str, errors="coerce")
    return None if pd.isna(parsed) else parsed


def build_weigh_in_index(weigh_ins_df: pd.DataFrame) -> dict:
    """Index validated weigh-in records by event date."""
    index: dict = {}
    if weigh_ins_df.empty:
        return index

    df = weigh_ins_df.copy()
    if "on_event_card" in df.columns:
        df = df[df["on_event_card"].fillna(True)]

    for _, row in df.iterrows():
        event_dt = parse_event_date(row["event_date"])
        if event_dt is None:
            continue
        event_key = event_dt.date()
        index.setdefault(event_key, []).append(
            (normalize_fighter(row["fighter"]), row["fighter"], float(row["weigh_in"]))
        )
    return index


def lookup_weigh_in(
    weigh_in_index: dict,
    event_date,
    fighter_name: str,
) -> float | None:
    event_dt = parse_event_date(event_date)
    if event_dt is None:
        return None

    candidates = weigh_in_index.get(event_dt.date(), [])
    for _, original_name, weight in candidates:
        if fighters_match(fighter_name, original_name):
            return weight
    return None


def attach_weigh_in_columns(fights_df: pd.DataFrame, weigh_in_index: dict) -> pd.DataFrame:
    out = fights_df.copy()
    out["p1_weigh_in"] = out.apply(
        lambda row: lookup_weigh_in(weigh_in_index, row["event_date"], row["p1_fighter"]),
        axis=1,
    )
    out["p2_weigh_in"] = out.apply(
        lambda row: lookup_weigh_in(weigh_in_index, row["event_date"], row["p2_fighter"]),
        axis=1,
    )
    out["weigh_in_diff"] = out["p1_weigh_in"] - out["p2_weigh_in"]
    return out


# Load augmented training data and scraped weigh-ins from CSV
aug_df = pd.read_csv(AUG_CSV)
weigh_ins_df = pd.read_csv(WEIGH_INS_CSV)
if weigh_ins_df.empty:
    raise ValueError(f"{WEIGH_INS_CSV} is empty — run the bulk scrape cell first.")

weigh_in_index = build_weigh_in_index(weigh_ins_df)

# ufc_aug.csv is already augmented; map weigh-ins per row so swapped rows stay consistent
aug_with_weigh_ins = attach_weigh_in_columns(aug_df, weigh_in_index)

matched_rows = aug_with_weigh_ins["p1_weigh_in"].notna() & aug_with_weigh_ins["p2_weigh_in"].notna()
print(f"Loaded {len(aug_df):,} augmented rows from {AUG_CSV}")
print(f"Loaded {len(weigh_ins_df):,} weigh-in records from {WEIGH_INS_CSV}")
print(f"Rows with both weigh-ins mapped: {matched_rows.sum():,} ({matched_rows.mean():.1%})")
print(f"Unique events with weigh-in data: {weigh_ins_df['event_date'].nunique()}")

aug_with_weigh_ins.to_csv(OUTPUT_CSV, index=False)
print(f"Saved {OUTPUT_CSV}")

aug_with_weigh_ins[
    ["p1_fighter", "p2_fighter", "event_date", "p1_weight", "p2_weight", "p1_weigh_in", "p2_weigh_in", "weigh_in_diff"]
].dropna(subset=["p1_weigh_in", "p2_weigh_in"]).head(10)

Loaded 17,508 augmented rows from ufc_aug.csv
Rows with both weigh-ins mapped: 9,530 (54.4%)
Unique events with weigh-in data: 597
Saved ufc_aug_weigh_in.csv

,p1_fighter,p2_fighter,event_date,p1_weight,p2_weight,p1_weigh_in,p2_weigh_in,weigh_in_diff
1798,Jorge Rivera,Martin Kampmann,2008-06-07,185.0,170.0,185.0,186.0,-1.0
1799,Matt Hughes,Thiago Alves,2008-06-07,170.0,170.0,170.0,174.0,-4.0
1800,Marcus Davis,Mike Swick,2008-06-07,170.0,170.0,170.0,170.0,0.0
1801,Nate Marquardt,Thales Leites,2008-06-07,185.0,185.0,185.0,185.0,0.0
1802,Brandon Vera,Fabricio Werdum,2008-06-07,230.0,231.0,228.0,247.0,-19.0
1803,Martin Kampmann,Jorge Rivera,2008-06-07,170.0,185.0,186.0,185.0,1.0
1804,Eddie Sanchez,Antoni Hardonk,2008-06-07,230.0,245.0,244.0,247.0,-3.0
1805,Thiago Tavares,Matt Wiman,2008-06-07,145.0,155.0,154.5,155.0,-0.5
1806,Roan Carneiro,Kevin Burns,2008-06-07,170.0,170.0,171.0,170.0,1.0
1807,Jason Lambert,Luiz Cane,2008-06-07,185.0,185.0,205.0,204.0,1.0

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.impute import SimpleImputer
import xgboost as xgb

# Import the first CSV file
feature_df = pd.read_csv('ufc_aug.csv')

#prepare data for training

# Drop the columns
columns_to_drop = ['p1_fighter', 'p2_fighter', 'event_date'] #method
feature_df = feature_df.drop(columns=columns_to_drop)
cols_to_drop = [col for col in feature_df.columns if col.startswith('method_')]
feature_df.drop(columns=cols_to_drop, inplace=True)

# Clean all column names
def clean_column_name(col):
    return col.lower().replace(' ', '_').replace('.', '').replace('-', '_')

# Apply to all columns
feature_df.columns = [clean_column_name(col) for col in feature_df.columns]

# Identify all categorical columns
categorical_cols = ['p1_stance', 'p2_stance']

# One-hot encode all categorical variables
feature_df = pd.get_dummies(feature_df, columns=categorical_cols)

feature_df = feature_df.sample(frac=1, random_state=42).reset_index(drop=True)

# encode the referee using frequency
ref_counts = feature_df['referee'].value_counts()
feature_df['referee_freq'] = feature_df['referee'].map(ref_counts)
feature_df.drop(columns=['referee'], inplace=True)

# Target setup
X = feature_df.drop(columns=['winner'])
y = feature_df['winner']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Identify numeric columns for imputation
numeric_cols = X_train.select_dtypes(include=['float64', 'int64']).columns.tolist()

# Impute missing values with median
num_imputer = SimpleImputer(strategy='median')
X_train[numeric_cols] = num_imputer.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = num_imputer.transform(X_test[numeric_cols])

# XGBoost model training with evaluation tracking
xgb_model = xgb.XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

# Define evaluation sets for learning curves
evalset = [(X_train, y_train), (X_test, y_test)]

# Fit model with evaluation tracking
xgb_model.fit(X_train, y_train, eval_set=evalset, verbose=False)

# Predictions and evaluation
xgb_pred = xgb_model.predict(X_test)
accuracy = accuracy_score(y_test, xgb_pred)
report = classification_report(y_test, xgb_pred)

print("XGBoost Model Performance:")
print(f"Accuracy: {accuracy:.4f}")
print("Classification Report:")
print(report)

# Feature importance analysis
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': xgb_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print("\nFeature Importances:")
print(feature_importance.to_string())

# Save the model
# xgb_model.save_model('xgb_model_good.json')

# Get the underlying booster and save that
xgb_model.get_booster().save_model('xgb_model_good.json')

/var/folders/nc/04zwxn450f3cllk4tzq8_fp40000gn/T/ipykernel_17491/3800749057.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  feature_df['referee_freq'] = feature_df['referee'].map(ref_counts)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [00:32:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBoost Model Performance:
Accuracy: 0.6759
Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.67      0.67      1744
           1       0.68      0.68      0.68      1758

    accuracy                           0.68      3502
   macro avg       0.68      0.68      0.68      3502
weighted avg       0.68      0.68      0.68      3502


Feature Importances:
                            Feature  Importance
28                        slpm_diff    0.028919
30                        sapm_diff    0.019599
34                       tddef_diff    0.017273
29                      stracc_diff    0.015583
10                       p1_sub_avg    0.013600
53          p2_age_adjusted_str_acc    0.012036
27                         age_diff    0.011594
31                      strdef_diff    0.011532
21                       p2_sub_avg    0.010511
52          p1_age_adjusted_str_acc    0.010366
51             p2_age_adjusted_slpm    0.010056
64          p1_age_adjusted_sub_avg    0.009521
19                        p2_td_acc    0.009520
3                           p1_slpm    0.009507
32                       tdavg_diff    0.009018
62           p1_age_adjusted_td_def    0.008984
8                         p1_td_acc    0.008730
26                      weight_diff    0.008702
56          p1_age_adjusted_str_def    0.008449
14                          p2_slpm    0.008439
65          p2_age_adjusted_sub_avg    0.008257
22                  p1_age_at_event    0.008238
63           p2_age_adjusted_td_def    0.007985
122              p1_body_landed_ema    0.007885
59           p2_age_adjusted_td_avg    0.007594
77                      p2_ctrl_ema    0.007577
48                    p1_win_streak    0.007564
7                         p1_td_avg    0.007401
94            p1_sig_str_landed_ema    0.007134
105             p2_td_attempted_ema    0.007125
16                          p2_sapm    0.007065
121           p2_head_attempted_ema    0.007043
6                        p1_str_def    0.007018
5                           p1_sapm    0.006968
57          p2_age_adjusted_str_def    0.006949
117          p2_r1_td_attempted_ema    0.006943
50             p1_age_adjusted_slpm    0.006939
49                    p2_win_streak    0.006878
78                     p1_r1_kd_ema    0.006798
129            p2_leg_attempted_ema    0.006776
163         p2_r1_ground_landed_ema    0.006613
39                          p1_wins    0.006612
148        p1_r1_body_attempted_ema    0.006526
23                  p2_age_at_event    0.006391
149        p2_r1_body_attempted_ema    0.006390
4                        p1_str_acc    0.006331
9                         p1_td_def    0.006330
18                        p2_td_avg    0.006189
103                p2_td_landed_ema    0.006149
134            p1_clinch_landed_ema    0.006131
60           p1_age_adjusted_td_acc    0.006096
133       p2_distance_attempted_ema    0.006011
135            p2_clinch_landed_ema    0.006006
107        p2_r1_sig_str_landed_ema    0.005993
164      p1_r1_ground_attempted_ema    0.005987
159         p2_r1_clinch_landed_ema    0.005983
45                         win_diff    0.005917
58           p1_age_adjusted_td_avg    0.005902
20                        p2_td_def    0.005895
158         p1_r1_clinch_landed_ema    0.005892
40                        p1_losses    0.005890
95            p2_sig_str_landed_ema    0.005881
114             p1_r1_td_landed_ema    0.005802
17                       p2_str_def    0.005779
141         p2_ground_attempted_ema    0.005760
54             p1_age_adjusted_sapm    0.005743
43                        p2_losses    0.005698
142           p1_r1_head_landed_ema    0.005651
119              p2_head_landed_ema    0.005588
100      p1_total_str_attempted_ema    0.005574
2                          p1_reach    0.005550
61           p2_age_adjusted_td_acc    0.005509
161      p2_r1_clinch_attempted_ema    0.005459
154       p1_r1_distance_landed_ema    0.005429
88                   p1_r1_ctrl_ema    0.005412
115             p2_r1_td_landed_ema    0.005411
38       days_since_last_fight_diff    0.005375
13                         p2_reach    0.005356
146           p1_r1_body_landed_ema    0.005312
79                     p2_r1_kd_ema    0.005254
104             p1_td_attempted_ema    0.005247
165      p2_r1_ground_attempted_ema    0.005231
130          p1_distance_landed_ema    0.005227
86                    p1_r1_rev_ema    0.005190
151            p2_r1_leg_landed_ema    0.005189
36         p1_days_since_last_fight    0.005149
67                        p2_kd_ema    0.005110
15                       p2_str_acc    0.005078
116          p1_r1_td_attempted_ema    0.005073
46                        loss_diff    0.005036
25                       reach_diff    0.005033
123              p2_body_landed_ema    0.005026
33                       tdacc_diff    0.005022
132       p1_distance_attempted_ema    0.005012
102                p1_td_landed_ema    0.005008
136         p1_clinch_attempted_ema    0.005004
73                   p2_sub_att_ema    0.004995
167              p1_stance_Orthodox    0.004953
112   p1_r1_total_str_attempted_ema    0.004927
1                         p1_weight    0.004897
55             p2_age_adjusted_sapm    0.004872
152         p1_r1_leg_attempted_ema    0.004871
74                       p1_rev_ema    0.004818
66                        p1_kd_ema    0.004809
137         p2_clinch_attempted_ema    0.004797
47                       total_diff    0.004760
42                          p2_wins    0.004752
140         p1_ground_attempted_ema    0.004697
131          p2_distance_landed_ema    0.004663
89                   p2_r1_ctrl_ema    0.004652
162         p1_r1_ground_landed_ema    0.004650
83                 p2_r1_td_pct_ema    0.004626
96         p1_sig_str_attempted_ema    0.004612
98          p1_total_str_landed_ema    0.004607
176                    referee_freq    0.004599
160      p1_r1_clinch_attempted_ema    0.004588
138            p1_ground_landed_ema    0.004585
120           p1_head_attempted_ema    0.004581
157    p2_r1_distance_attempted_ema    0.004573
41                         p1_total    0.004563
37         p2_days_since_last_fight    0.004559
169              p1_stance_Southpaw    0.004528
109     p2_r1_sig_str_attempted_ema    0.004484
12                        p2_weight    0.004470
72                   p1_sub_att_ema    0.004469
144        p1_r1_head_attempted_ema    0.004468
126               p1_leg_landed_ema    0.004442
124           p1_body_attempted_ema    0.004415
139            p2_ground_landed_ema    0.004415
71                    p2_td_pct_ema    0.004390
127               p2_leg_landed_ema    0.004386
113   p2_r1_total_str_attempted_ema    0.004378
125           p2_body_attempted_ema    0.004376
156    p1_r1_distance_attempted_ema    0.004301
85                p2_r1_sub_att_ema    0.004295
35                      subavg_diff    0.004276
128            p1_leg_attempted_ema    0.004227
150            p1_r1_leg_landed_ema    0.004219
153         p2_r1_leg_attempted_ema    0.004194
101      p2_total_str_attempted_ema    0.004183
87                    p2_r1_rev_ema    0.004180
147           p2_r1_body_landed_ema    0.004166
0                         p1_height    0.004095
75                       p2_rev_ema    0.004064
110      p1_r1_total_str_landed_ema    0.004007
70                    p1_td_pct_ema    0.004001
69               p2_sig_str_pct_ema    0.003966
80            p1_r1_sig_str_pct_ema    0.003940
106        p1_r1_sig_str_landed_ema    0.003928
76                      p1_ctrl_ema    0.003845
111      p2_r1_total_str_landed_ema    0.003844
118              p1_head_landed_ema    0.003784
143           p2_r1_head_landed_ema    0.003679
11                        p2_height    0.003676
68               p1_sig_str_pct_ema    0.003569
81            p2_r1_sig_str_pct_ema    0.003547
172              p2_stance_Orthodox    0.003452
155       p2_r1_distance_landed_ema    0.003446
24                      height_diff    0.003392
108     p1_r1_sig_str_attempted_ema    0.003319
145        p2_r1_head_attempted_ema    0.003283
82                 p1_r1_td_pct_ema    0.003256
97         p2_sig_str_attempted_ema    0.003196
84                p1_r1_sub_att_ema    0.003173
99          p2_total_str_landed_ema    0.002943
44                         p2_total    0.002840
91      p2_sig_str_pct_detailed_ema    0.000000
90      p1_sig_str_pct_detailed_ema    0.000000
93   p2_r1_sig_str_pct_detailed_ema    0.000000
92   p1_r1_sig_str_pct_detailed_ema    0.000000
166           p1_stance_Open Stance    0.000000
168              p1_stance_Sideways    0.000000
170                p1_stance_Switch    0.000000
171           p2_stance_Open Stance    0.000000
173              p2_stance_Sideways    0.000000
174              p2_stance_Southpaw    0.000000
175                p2_stance_Switch    0.000000